// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> conv_2::ap_ST_fsm_state1 = "1";
const sc_lv<5> conv_2::ap_ST_fsm_state2 = "10";
const sc_lv<5> conv_2::ap_ST_fsm_state3 = "100";
const sc_lv<5> conv_2::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<5> conv_2::ap_ST_fsm_state6 = "10000";
const bool conv_2::ap_const_boolean_1 = true;
const sc_lv<32> conv_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_2::ap_const_lv32_1 = "1";
const sc_lv<1> conv_2::ap_const_lv1_0 = "0";
const sc_lv<32> conv_2::ap_const_lv32_2 = "10";
const sc_lv<32> conv_2::ap_const_lv32_3 = "11";
const bool conv_2::ap_const_boolean_0 = false;
const sc_lv<32> conv_2::ap_const_lv32_4 = "100";
const sc_lv<1> conv_2::ap_const_lv1_1 = "1";
const sc_lv<11> conv_2::ap_const_lv11_0 = "00000000000";
const sc_lv<5> conv_2::ap_const_lv5_0 = "00000";
const sc_lv<8> conv_2::ap_const_lv8_0 = "00000000";
const sc_lv<4> conv_2::ap_const_lv4_0 = "0000";
const sc_lv<3> conv_2::ap_const_lv3_0 = "000";
const sc_lv<6> conv_2::ap_const_lv6_0 = "000000";
const sc_lv<5> conv_2::ap_const_lv5_1 = "1";
const sc_lv<11> conv_2::ap_const_lv11_640 = "11001000000";
const sc_lv<11> conv_2::ap_const_lv11_1 = "1";
const sc_lv<8> conv_2::ap_const_lv8_64 = "1100100";
const sc_lv<4> conv_2::ap_const_lv4_A = "1010";
const sc_lv<4> conv_2::ap_const_lv4_1 = "1";
const sc_lv<2> conv_2::ap_const_lv2_0 = "00";
const sc_lv<8> conv_2::ap_const_lv8_96 = "10010110";
const sc_lv<8> conv_2::ap_const_lv8_1 = "1";
const sc_lv<6> conv_2::ap_const_lv6_19 = "11001";
const sc_lv<3> conv_2::ap_const_lv3_1 = "1";
const sc_lv<3> conv_2::ap_const_lv3_5 = "101";
const sc_lv<6> conv_2::ap_const_lv6_1 = "1";

conv_2::conv_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    c2_weight_U = new conv_2_c2_weight("c2_weight_U");
    c2_weight_U->clk(ap_clk);
    c2_weight_U->reset(ap_rst);
    c2_weight_U->address0(c2_weight_address0);
    c2_weight_U->ce0(c2_weight_ce0);
    c2_weight_U->q0(c2_weight_q0);
    c2_bias_U = new conv_2_c2_bias("c2_bias_U");
    c2_bias_U->clk(ap_clk);
    c2_bias_U->reset(ap_rst);
    c2_bias_U->address0(c2_bias_address0);
    c2_bias_U->ce0(c2_bias_ce0);
    c2_bias_U->q0(c2_bias_q0);
    top_net_fadd_32nsbkb_U14 = new top_net_fadd_32nsbkb<1,1,32,32,32>("top_net_fadd_32nsbkb_U14");
    top_net_fadd_32nsbkb_U14->din0(grp_fu_277_p0);
    top_net_fadd_32nsbkb_U14->din1(output_buffer_2_reg_254);
    top_net_fadd_32nsbkb_U14->dout(grp_fu_277_p2);
    top_net_fmul_32nscud_U15 = new top_net_fmul_32nscud<1,1,32,32,32>("top_net_fmul_32nscud_U15");
    top_net_fmul_32nscud_U15->din0(in_r_q0);
    top_net_fmul_32nscud_U15->din1(c2_weight_q0);
    top_net_fmul_32nscud_U15->dout(tmp_s_fu_283_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( exitcond_flatten7_fu_682_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_346_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_346_p2 );

    SC_METHOD(thread_c2_bias_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c2_bias_load_mid2_fu_450_p1 );

    SC_METHOD(thread_c2_bias_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_c2_bias_load_mid2_fu_450_p1);
    sensitive << ( c2_bias_load_mid2_v_fu_442_p3 );

    SC_METHOD(thread_c2_bias_load_mid2_v_fu_442_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( cout_reg_165 );
    sensitive << ( cout_s_fu_372_p2 );

    SC_METHOD(thread_c2_weight_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_59_fu_1041_p1 );

    SC_METHOD(thread_c2_weight_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_cin_cast3_fu_566_p1);
    sensitive << ( cin_reg_221 );

    SC_METHOD(thread_cin_cast3_mid1_fu_714_p1);
    sensitive << ( cin_s_fu_708_p2 );

    SC_METHOD(thread_cin_mid2_fu_872_p3);
    sensitive << ( cin_reg_221 );
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( cin_s_fu_708_p2 );

    SC_METHOD(thread_cin_s_fu_708_p2);
    sensitive << ( cin_reg_221 );

    SC_METHOD(thread_cout_s_fu_372_p2);
    sensitive << ( cout_reg_165 );

    SC_METHOD(thread_exitcond1_fu_860_p2);
    sensitive << ( x_reg_266 );
    sensitive << ( exitcond_flatten7_fu_682_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond5_mid_fu_481_p2);
    sensitive << ( exitcond_fu_475_p2 );
    sensitive << ( not_exitcond_flatten_8_fu_469_p2 );

    SC_METHOD(thread_exitcond_flatten6_fu_358_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_346_p2 );
    sensitive << ( indvar_flatten4_reg_176 );

    SC_METHOD(thread_exitcond_flatten7_fu_682_p2);
    sensitive << ( indvar_flatten5_reg_210 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten8_fu_694_p2);
    sensitive << ( indvar_flatten_reg_232 );
    sensitive << ( exitcond_flatten7_fu_682_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_346_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten3_reg_154 );

    SC_METHOD(thread_exitcond_fu_475_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_346_p2 );
    sensitive << ( w_reg_199 );

    SC_METHOD(thread_exitcond_mid_fu_866_p2);
    sensitive << ( exitcond1_fu_860_p2 );
    sensitive << ( not_exitcond_flatten_fu_854_p2 );

    SC_METHOD(thread_grp_fu_277_p0);
    sensitive << ( c2_bias_load_reg_1150 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_s_fu_283_p2 );

    SC_METHOD(thread_h_1_fu_487_p2);
    sensitive << ( h_mid_fu_364_p3 );

    SC_METHOD(thread_h_cast2_fu_326_p1);
    sensitive << ( h_reg_188 );

    SC_METHOD(thread_h_cast2_mid1_fu_515_p1);
    sensitive << ( h_1_fu_487_p2 );

    SC_METHOD(thread_h_cast_mid2_cast_fu_543_p1);
    sensitive << ( h_cast_mid2_reg_1138 );

    SC_METHOD(thread_h_cast_mid2_fu_507_p3);
    sensitive << ( h_mid_fu_364_p3 );
    sensitive << ( exitcond5_mid_fu_481_p2 );
    sensitive << ( h_1_fu_487_p2 );

    SC_METHOD(thread_h_mid_fu_364_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( h_reg_188 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_57_fu_1016_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_indvar_flatten51_op_fu_1089_p2);
    sensitive << ( indvar_flatten4_reg_176 );

    SC_METHOD(thread_indvar_flatten_next1_2_fu_1095_p3);
    sensitive << ( exitcond_flatten6_reg_1110 );
    sensitive << ( indvar_flatten51_op_fu_1089_p2 );

    SC_METHOD(thread_indvar_flatten_next1_3_fu_352_p2);
    sensitive << ( indvar_flatten3_reg_154 );

    SC_METHOD(thread_indvar_flatten_next1_fu_688_p2);
    sensitive << ( indvar_flatten5_reg_210 );

    SC_METHOD(thread_indvar_flatten_next_fu_1058_p3);
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( indvar_flatten_op_fu_1052_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_1052_p2);
    sensitive << ( indvar_flatten_reg_232 );

    SC_METHOD(thread_not_exitcond_flatten_8_fu_469_p2);
    sensitive << ( exitcond_flatten6_fu_358_p2 );

    SC_METHOD(thread_not_exitcond_flatten_fu_854_p2);
    sensitive << ( exitcond_flatten8_fu_694_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_47_fu_1079_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( grp_fu_277_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_p_shl1_cast_fu_656_p1);
    sensitive << ( p_shl1_fu_648_p3 );

    SC_METHOD(thread_p_shl1_cast_mid1_fu_935_p1);
    sensitive << ( p_shl1_mid1_fu_927_p3 );

    SC_METHOD(thread_p_shl1_cast_mid_fu_818_p1);
    sensitive << ( p_shl1_mid_fu_810_p3 );

    SC_METHOD(thread_p_shl1_fu_648_p3);
    sensitive << ( tmp_51_fu_635_p2 );

    SC_METHOD(thread_p_shl1_mid1_fu_927_p3);
    sensitive << ( tmp_51_mid1_fu_914_p2 );

    SC_METHOD(thread_p_shl1_mid_fu_810_p3);
    sensitive << ( tmp_51_mid_fu_797_p2 );

    SC_METHOD(thread_p_shl2_cast_fu_302_p1);
    sensitive << ( p_shl2_fu_294_p3 );

    SC_METHOD(thread_p_shl2_cast_mid1_fu_390_p1);
    sensitive << ( p_shl2_mid1_fu_382_p3 );

    SC_METHOD(thread_p_shl2_cast_mid2_cast_fu_402_p1);
    sensitive << ( p_shl2_cast_mid2_fu_394_p3 );

    SC_METHOD(thread_p_shl2_cast_mid2_fu_394_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( p_shl2_fu_294_p3 );
    sensitive << ( p_shl2_mid1_fu_382_p3 );

    SC_METHOD(thread_p_shl2_fu_294_p3);
    sensitive << ( tmp_5_fu_290_p1 );

    SC_METHOD(thread_p_shl2_mid1_fu_382_p3);
    sensitive << ( tmp_7_fu_378_p1 );

    SC_METHOD(thread_p_shl3_cast1_fu_312_p1);
    sensitive << ( tmp_6_fu_306_p2 );

    SC_METHOD(thread_p_shl3_cast1_mid2_cas_fu_420_p1);
    sensitive << ( p_shl3_cast1_mid2_fu_412_p3 );

    SC_METHOD(thread_p_shl3_cast1_mid2_fu_412_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( tmp_6_fu_306_p2 );
    sensitive << ( tmp_8_fu_406_p2 );

    SC_METHOD(thread_p_shl3_cast_fu_316_p1);
    sensitive << ( tmp_6_fu_306_p2 );

    SC_METHOD(thread_p_shl3_cast_mid1_fu_424_p1);
    sensitive << ( tmp_8_fu_406_p2 );

    SC_METHOD(thread_p_shl4_mid277_v_v_fu_461_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( tmp_37_mid_fu_455_p2 );
    sensitive << ( tmp_37_fu_340_p2 );

    SC_METHOD(thread_p_shl4_mid2_fu_546_p3);
    sensitive << ( p_shl4_mid2_v_v_reg_1144 );

    SC_METHOD(thread_p_shl4_mid2_v_v_fu_535_p3);
    sensitive << ( exitcond5_mid_fu_481_p2 );
    sensitive << ( tmp_37_mid1_fu_529_p2 );
    sensitive << ( p_shl4_mid277_v_v_fu_461_p3 );

    SC_METHOD(thread_p_shl5_mid2_fu_553_p3);
    sensitive << ( p_shl4_mid2_v_v_reg_1144 );

    SC_METHOD(thread_p_shl6_cast_fu_617_p1);
    sensitive << ( p_shl6_fu_609_p3 );

    SC_METHOD(thread_p_shl6_cast_mid1_fu_781_p1);
    sensitive << ( p_shl6_mid1_fu_773_p3 );

    SC_METHOD(thread_p_shl6_cast_mid2_cast_fu_793_p1);
    sensitive << ( p_shl6_cast_mid2_fu_785_p3 );

    SC_METHOD(thread_p_shl6_cast_mid2_fu_785_p3);
    sensitive << ( p_shl6_fu_609_p3 );
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( p_shl6_mid1_fu_773_p3 );

    SC_METHOD(thread_p_shl6_fu_609_p3);
    sensitive << ( tmp_43_fu_600_p2 );

    SC_METHOD(thread_p_shl6_mid1_fu_773_p3);
    sensitive << ( tmp_43_mid1_fu_756_p2 );

    SC_METHOD(thread_p_shl7_cast_fu_578_p1);
    sensitive << ( p_shl7_fu_570_p3 );

    SC_METHOD(thread_p_shl7_cast_mid1_fu_726_p1);
    sensitive << ( p_shl7_mid1_fu_718_p3 );

    SC_METHOD(thread_p_shl7_fu_570_p3);
    sensitive << ( cin_reg_221 );

    SC_METHOD(thread_p_shl7_mid1_fu_718_p3);
    sensitive << ( cin_s_fu_708_p2 );

    SC_METHOD(thread_p_shl8_cast_fu_590_p1);
    sensitive << ( p_shl8_fu_582_p3 );

    SC_METHOD(thread_p_shl8_cast_mid1_fu_738_p1);
    sensitive << ( p_shl8_mid1_fu_730_p3 );

    SC_METHOD(thread_p_shl8_fu_582_p3);
    sensitive << ( cin_reg_221 );

    SC_METHOD(thread_p_shl8_mid1_fu_730_p3);
    sensitive << ( cin_s_fu_708_p2 );

    SC_METHOD(thread_p_shl9_mid2_fu_977_p3);
    sensitive << ( tmp_mid2_fu_969_p3 );

    SC_METHOD(thread_p_shl_fu_640_p3);
    sensitive << ( tmp_51_fu_635_p2 );

    SC_METHOD(thread_p_shl_mid1_fu_919_p3);
    sensitive << ( tmp_51_mid1_fu_914_p2 );

    SC_METHOD(thread_p_shl_mid_fu_802_p3);
    sensitive << ( tmp_51_mid_fu_797_p2 );

    SC_METHOD(thread_tmp2_cast_fu_336_p1);
    sensitive << ( tmp2_fu_330_p2 );

    SC_METHOD(thread_tmp2_cast_mid1_fu_525_p1);
    sensitive << ( tmp2_mid1_fu_519_p2 );

    SC_METHOD(thread_tmp2_fu_330_p2);
    sensitive << ( p_shl3_cast1_fu_312_p1 );
    sensitive << ( h_cast2_fu_326_p1 );

    SC_METHOD(thread_tmp2_mid1_fu_519_p2);
    sensitive << ( h_cast2_mid1_fu_515_p1 );
    sensitive << ( p_shl3_cast1_mid2_cas_fu_420_p1 );

    SC_METHOD(thread_tmp3_fu_629_p2);
    sensitive << ( y_cast1_fu_625_p1 );
    sensitive << ( tmp_42_fu_594_p2 );

    SC_METHOD(thread_tmp3_mid1_fu_908_p2);
    sensitive << ( y_cast1_mid1_fu_904_p1 );
    sensitive << ( tmp_42_mid2_fu_748_p3 );

    SC_METHOD(thread_tmp4_cast_fu_672_p1);
    sensitive << ( tmp4_fu_666_p2 );

    SC_METHOD(thread_tmp4_cast_mid1_fu_959_p1);
    sensitive << ( tmp4_mid1_fu_953_p2 );

    SC_METHOD(thread_tmp4_cast_mid_fu_836_p1);
    sensitive << ( tmp_43_mid1_fu_756_p2 );

    SC_METHOD(thread_tmp4_fu_666_p2);
    sensitive << ( tmp_43_cast_fu_605_p1 );
    sensitive << ( y_cast_fu_621_p1 );

    SC_METHOD(thread_tmp4_mid1_fu_953_p2);
    sensitive << ( tmp_43_cast_mid2_cas_fu_769_p1 );
    sensitive << ( y_cast_mid1_fu_900_p1 );

    SC_METHOD(thread_tmp5_fu_1001_p2);
    sensitive << ( x_cast8_fu_997_p1 );
    sensitive << ( tmp_52_mid2_fu_945_p3 );

    SC_METHOD(thread_tmp6_cast_fu_1027_p1);
    sensitive << ( tmp6_fu_1021_p2 );

    SC_METHOD(thread_tmp6_fu_1021_p2);
    sensitive << ( tmp_mid2_fu_969_p3 );
    sensitive << ( x_cast9_fu_993_p1 );

    SC_METHOD(thread_tmp7_cast_fu_1070_p1);
    sensitive << ( tmp7_fu_1066_p2 );

    SC_METHOD(thread_tmp7_fu_1066_p2);
    sensitive << ( p_shl5_mid2_reg_1167 );
    sensitive << ( w_cast_reg_1172 );

    SC_METHOD(thread_tmp_12_fu_493_p2);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( exitcond5_mid_fu_481_p2 );

    SC_METHOD(thread_tmp_13_fu_886_p2);
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( exitcond_mid_fu_866_p2 );

    SC_METHOD(thread_tmp_32_fu_320_p2);
    sensitive << ( p_shl2_cast_fu_302_p1 );
    sensitive << ( p_shl3_cast_fu_316_p1 );

    SC_METHOD(thread_tmp_32_mid1_fu_428_p2);
    sensitive << ( p_shl2_cast_mid1_fu_390_p1 );
    sensitive << ( p_shl3_cast_mid1_fu_424_p1 );

    SC_METHOD(thread_tmp_32_mid2_fu_434_p3);
    sensitive << ( exitcond_flatten6_fu_358_p2 );
    sensitive << ( tmp_32_mid1_fu_428_p2 );
    sensitive << ( tmp_32_fu_320_p2 );

    SC_METHOD(thread_tmp_37_fu_340_p2);
    sensitive << ( p_shl2_cast_fu_302_p1 );
    sensitive << ( tmp2_cast_fu_336_p1 );

    SC_METHOD(thread_tmp_37_mid1_fu_529_p2);
    sensitive << ( p_shl2_cast_mid2_cast_fu_402_p1 );
    sensitive << ( tmp2_cast_mid1_fu_525_p1 );

    SC_METHOD(thread_tmp_37_mid_fu_455_p2);
    sensitive << ( p_shl2_cast_mid1_fu_390_p1 );
    sensitive << ( p_shl3_cast_mid1_fu_424_p1 );

    SC_METHOD(thread_tmp_42_fu_594_p2);
    sensitive << ( p_shl7_cast_fu_578_p1 );
    sensitive << ( p_shl8_cast_fu_590_p1 );

    SC_METHOD(thread_tmp_42_mid1_fu_742_p2);
    sensitive << ( p_shl7_cast_mid1_fu_726_p1 );
    sensitive << ( p_shl8_cast_mid1_fu_738_p1 );

    SC_METHOD(thread_tmp_42_mid2_fu_748_p3);
    sensitive << ( tmp_42_fu_594_p2 );
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( tmp_42_mid1_fu_742_p2 );

    SC_METHOD(thread_tmp_43_cast_fu_605_p1);
    sensitive << ( tmp_43_fu_600_p2 );

    SC_METHOD(thread_tmp_43_cast_mid2_cas_fu_769_p1);
    sensitive << ( tmp_43_cast_mid2_fu_761_p3 );

    SC_METHOD(thread_tmp_43_cast_mid2_fu_761_p3);
    sensitive << ( tmp_43_fu_600_p2 );
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( tmp_43_mid1_fu_756_p2 );

    SC_METHOD(thread_tmp_43_fu_600_p2);
    sensitive << ( tmp_32_mid2_reg_1115 );
    sensitive << ( cin_cast3_fu_566_p1 );

    SC_METHOD(thread_tmp_43_mid1_fu_756_p2);
    sensitive << ( tmp_32_mid2_reg_1115 );
    sensitive << ( cin_cast3_mid1_fu_714_p1 );

    SC_METHOD(thread_tmp_46_fu_1074_p2);
    sensitive << ( p_shl4_mid2_reg_1162 );
    sensitive << ( tmp7_cast_fu_1070_p1 );

    SC_METHOD(thread_tmp_47_fu_1079_p1);
    sensitive << ( tmp_46_fu_1074_p2 );

    SC_METHOD(thread_tmp_51_fu_635_p2);
    sensitive << ( h_cast_mid2_cast_reg_1155 );
    sensitive << ( tmp3_fu_629_p2 );

    SC_METHOD(thread_tmp_51_mid1_fu_914_p2);
    sensitive << ( h_cast_mid2_cast_reg_1155 );
    sensitive << ( tmp3_mid1_fu_908_p2 );

    SC_METHOD(thread_tmp_51_mid_fu_797_p2);
    sensitive << ( h_cast_mid2_cast_reg_1155 );
    sensitive << ( tmp_42_mid1_fu_742_p2 );

    SC_METHOD(thread_tmp_52_fu_660_p2);
    sensitive << ( p_shl_fu_640_p3 );
    sensitive << ( p_shl1_cast_fu_656_p1 );

    SC_METHOD(thread_tmp_52_mid1_fu_939_p2);
    sensitive << ( p_shl_mid1_fu_919_p3 );
    sensitive << ( p_shl1_cast_mid1_fu_935_p1 );

    SC_METHOD(thread_tmp_52_mid2_fu_945_p3);
    sensitive << ( exitcond_mid_fu_866_p2 );
    sensitive << ( tmp_52_mid1_fu_939_p2 );
    sensitive << ( tmp_52_mid3_fu_828_p3 );

    SC_METHOD(thread_tmp_52_mid3_fu_828_p3);
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( tmp_52_mid_fu_822_p2 );
    sensitive << ( tmp_52_fu_660_p2 );

    SC_METHOD(thread_tmp_52_mid_fu_822_p2);
    sensitive << ( p_shl_mid_fu_802_p3 );
    sensitive << ( p_shl1_cast_mid_fu_818_p1 );

    SC_METHOD(thread_tmp_56_cast_fu_1012_p1);
    sensitive << ( tmp_56_fu_1007_p2 );

    SC_METHOD(thread_tmp_56_fu_1007_p2);
    sensitive << ( w_cast2_reg_1177 );
    sensitive << ( tmp5_fu_1001_p2 );

    SC_METHOD(thread_tmp_57_fu_1016_p1);
    sensitive << ( tmp_56_cast_fu_1012_p1 );

    SC_METHOD(thread_tmp_58_cast_fu_1037_p1);
    sensitive << ( tmp_58_fu_1031_p2 );

    SC_METHOD(thread_tmp_58_fu_1031_p2);
    sensitive << ( tmp6_cast_fu_1027_p1 );
    sensitive << ( p_shl9_mid2_fu_977_p3 );

    SC_METHOD(thread_tmp_59_fu_1041_p1);
    sensitive << ( tmp_58_cast_fu_1037_p1 );

    SC_METHOD(thread_tmp_5_fu_290_p1);
    sensitive << ( cout_reg_165 );

    SC_METHOD(thread_tmp_6_fu_306_p2);
    sensitive << ( cout_reg_165 );

    SC_METHOD(thread_tmp_7_fu_378_p1);
    sensitive << ( cout_s_fu_372_p2 );

    SC_METHOD(thread_tmp_8_fu_406_p2);
    sensitive << ( cout_s_fu_372_p2 );

    SC_METHOD(thread_tmp_fu_676_p2);
    sensitive << ( tmp4_cast_fu_672_p1 );
    sensitive << ( p_shl6_cast_fu_617_p1 );

    SC_METHOD(thread_tmp_mid1_fu_963_p2);
    sensitive << ( tmp4_cast_mid1_fu_959_p1 );
    sensitive << ( p_shl6_cast_mid2_cast_fu_793_p1 );

    SC_METHOD(thread_tmp_mid2_fu_969_p3);
    sensitive << ( exitcond_mid_fu_866_p2 );
    sensitive << ( tmp_mid1_fu_963_p2 );
    sensitive << ( tmp_mid4_fu_846_p3 );

    SC_METHOD(thread_tmp_mid4_fu_846_p3);
    sensitive << ( exitcond_flatten8_fu_694_p2 );
    sensitive << ( tmp_mid_fu_840_p2 );
    sensitive << ( tmp_fu_676_p2 );

    SC_METHOD(thread_tmp_mid_fu_840_p2);
    sensitive << ( tmp4_cast_mid_fu_836_p1 );
    sensitive << ( p_shl6_cast_mid1_fu_781_p1 );

    SC_METHOD(thread_w_1_fu_1084_p2);
    sensitive << ( w_mid2_reg_1131 );

    SC_METHOD(thread_w_cast2_fu_563_p1);
    sensitive << ( w_mid2_reg_1131 );

    SC_METHOD(thread_w_cast_fu_560_p1);
    sensitive << ( w_mid2_reg_1131 );

    SC_METHOD(thread_w_mid2_fu_499_p3);
    sensitive << ( w_reg_199 );
    sensitive << ( tmp_12_fu_493_p2 );

    SC_METHOD(thread_x_1_fu_1046_p2);
    sensitive << ( x_mid2_fu_892_p3 );

    SC_METHOD(thread_x_cast8_fu_997_p1);
    sensitive << ( x_mid2_fu_892_p3 );

    SC_METHOD(thread_x_cast9_fu_993_p1);
    sensitive << ( x_mid2_fu_892_p3 );

    SC_METHOD(thread_x_mid2_fu_892_p3);
    sensitive << ( x_reg_266 );
    sensitive << ( tmp_13_fu_886_p2 );

    SC_METHOD(thread_y_1_fu_880_p2);
    sensitive << ( y_mid_fu_700_p3 );

    SC_METHOD(thread_y_cast1_fu_625_p1);
    sensitive << ( y_reg_243 );

    SC_METHOD(thread_y_cast1_mid1_fu_904_p1);
    sensitive << ( y_1_fu_880_p2 );

    SC_METHOD(thread_y_cast_fu_621_p1);
    sensitive << ( y_reg_243 );

    SC_METHOD(thread_y_cast_mid1_fu_900_p1);
    sensitive << ( y_1_fu_880_p2 );

    SC_METHOD(thread_y_mid2_fu_985_p3);
    sensitive << ( y_mid_fu_700_p3 );
    sensitive << ( exitcond_mid_fu_866_p2 );
    sensitive << ( y_1_fu_880_p2 );

    SC_METHOD(thread_y_mid_fu_700_p3);
    sensitive << ( y_reg_243 );
    sensitive << ( exitcond_flatten8_fu_694_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_346_p2 );
    sensitive << ( exitcond_flatten7_fu_682_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, c2_weight_address0, "c2_weight_address0");
    sc_trace(mVcdFile, c2_weight_ce0, "c2_weight_ce0");
    sc_trace(mVcdFile, c2_weight_q0, "c2_weight_q0");
    sc_trace(mVcdFile, c2_bias_address0, "c2_bias_address0");
    sc_trace(mVcdFile, c2_bias_ce0, "c2_bias_ce0");
    sc_trace(mVcdFile, c2_bias_q0, "c2_bias_q0");
    sc_trace(mVcdFile, indvar_flatten5_reg_210, "indvar_flatten5_reg_210");
    sc_trace(mVcdFile, cin_reg_221, "cin_reg_221");
    sc_trace(mVcdFile, indvar_flatten_reg_232, "indvar_flatten_reg_232");
    sc_trace(mVcdFile, y_reg_243, "y_reg_243");
    sc_trace(mVcdFile, output_buffer_2_reg_254, "output_buffer_2_reg_254");
    sc_trace(mVcdFile, x_reg_266, "x_reg_266");
    sc_trace(mVcdFile, indvar_flatten_next1_3_fu_352_p2, "indvar_flatten_next1_3_fu_352_p2");
    sc_trace(mVcdFile, indvar_flatten_next1_3_reg_1105, "indvar_flatten_next1_3_reg_1105");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_flatten6_fu_358_p2, "exitcond_flatten6_fu_358_p2");
    sc_trace(mVcdFile, exitcond_flatten6_reg_1110, "exitcond_flatten6_reg_1110");
    sc_trace(mVcdFile, exitcond_flatten_fu_346_p2, "exitcond_flatten_fu_346_p2");
    sc_trace(mVcdFile, tmp_32_mid2_fu_434_p3, "tmp_32_mid2_fu_434_p3");
    sc_trace(mVcdFile, tmp_32_mid2_reg_1115, "tmp_32_mid2_reg_1115");
    sc_trace(mVcdFile, c2_bias_load_mid2_v_fu_442_p3, "c2_bias_load_mid2_v_fu_442_p3");
    sc_trace(mVcdFile, c2_bias_load_mid2_v_reg_1121, "c2_bias_load_mid2_v_reg_1121");
    sc_trace(mVcdFile, w_mid2_fu_499_p3, "w_mid2_fu_499_p3");
    sc_trace(mVcdFile, w_mid2_reg_1131, "w_mid2_reg_1131");
    sc_trace(mVcdFile, h_cast_mid2_fu_507_p3, "h_cast_mid2_fu_507_p3");
    sc_trace(mVcdFile, h_cast_mid2_reg_1138, "h_cast_mid2_reg_1138");
    sc_trace(mVcdFile, p_shl4_mid2_v_v_fu_535_p3, "p_shl4_mid2_v_v_fu_535_p3");
    sc_trace(mVcdFile, p_shl4_mid2_v_v_reg_1144, "p_shl4_mid2_v_v_reg_1144");
    sc_trace(mVcdFile, c2_bias_load_reg_1150, "c2_bias_load_reg_1150");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, h_cast_mid2_cast_fu_543_p1, "h_cast_mid2_cast_fu_543_p1");
    sc_trace(mVcdFile, h_cast_mid2_cast_reg_1155, "h_cast_mid2_cast_reg_1155");
    sc_trace(mVcdFile, p_shl4_mid2_fu_546_p3, "p_shl4_mid2_fu_546_p3");
    sc_trace(mVcdFile, p_shl4_mid2_reg_1162, "p_shl4_mid2_reg_1162");
    sc_trace(mVcdFile, p_shl5_mid2_fu_553_p3, "p_shl5_mid2_fu_553_p3");
    sc_trace(mVcdFile, p_shl5_mid2_reg_1167, "p_shl5_mid2_reg_1167");
    sc_trace(mVcdFile, w_cast_fu_560_p1, "w_cast_fu_560_p1");
    sc_trace(mVcdFile, w_cast_reg_1172, "w_cast_reg_1172");
    sc_trace(mVcdFile, w_cast2_fu_563_p1, "w_cast2_fu_563_p1");
    sc_trace(mVcdFile, w_cast2_reg_1177, "w_cast2_reg_1177");
    sc_trace(mVcdFile, exitcond_flatten7_fu_682_p2, "exitcond_flatten7_fu_682_p2");
    sc_trace(mVcdFile, exitcond_flatten7_reg_1182, "exitcond_flatten7_reg_1182");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_688_p2, "indvar_flatten_next1_fu_688_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, cin_mid2_fu_872_p3, "cin_mid2_fu_872_p3");
    sc_trace(mVcdFile, y_mid2_fu_985_p3, "y_mid2_fu_985_p3");
    sc_trace(mVcdFile, x_1_fu_1046_p2, "x_1_fu_1046_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_1058_p3, "indvar_flatten_next_fu_1058_p3");
    sc_trace(mVcdFile, grp_fu_277_p2, "grp_fu_277_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, w_1_fu_1084_p2, "w_1_fu_1084_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, indvar_flatten_next1_2_fu_1095_p3, "indvar_flatten_next1_2_fu_1095_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, indvar_flatten3_reg_154, "indvar_flatten3_reg_154");
    sc_trace(mVcdFile, cout_reg_165, "cout_reg_165");
    sc_trace(mVcdFile, indvar_flatten4_reg_176, "indvar_flatten4_reg_176");
    sc_trace(mVcdFile, h_reg_188, "h_reg_188");
    sc_trace(mVcdFile, w_reg_199, "w_reg_199");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, c2_bias_load_mid2_fu_450_p1, "c2_bias_load_mid2_fu_450_p1");
    sc_trace(mVcdFile, tmp_57_fu_1016_p1, "tmp_57_fu_1016_p1");
    sc_trace(mVcdFile, tmp_59_fu_1041_p1, "tmp_59_fu_1041_p1");
    sc_trace(mVcdFile, tmp_47_fu_1079_p1, "tmp_47_fu_1079_p1");
    sc_trace(mVcdFile, grp_fu_277_p0, "grp_fu_277_p0");
    sc_trace(mVcdFile, tmp_s_fu_283_p2, "tmp_s_fu_283_p2");
    sc_trace(mVcdFile, tmp_5_fu_290_p1, "tmp_5_fu_290_p1");
    sc_trace(mVcdFile, p_shl2_fu_294_p3, "p_shl2_fu_294_p3");
    sc_trace(mVcdFile, tmp_6_fu_306_p2, "tmp_6_fu_306_p2");
    sc_trace(mVcdFile, p_shl2_cast_fu_302_p1, "p_shl2_cast_fu_302_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_316_p1, "p_shl3_cast_fu_316_p1");
    sc_trace(mVcdFile, p_shl3_cast1_fu_312_p1, "p_shl3_cast1_fu_312_p1");
    sc_trace(mVcdFile, h_cast2_fu_326_p1, "h_cast2_fu_326_p1");
    sc_trace(mVcdFile, tmp2_fu_330_p2, "tmp2_fu_330_p2");
    sc_trace(mVcdFile, tmp2_cast_fu_336_p1, "tmp2_cast_fu_336_p1");
    sc_trace(mVcdFile, cout_s_fu_372_p2, "cout_s_fu_372_p2");
    sc_trace(mVcdFile, tmp_7_fu_378_p1, "tmp_7_fu_378_p1");
    sc_trace(mVcdFile, p_shl2_mid1_fu_382_p3, "p_shl2_mid1_fu_382_p3");
    sc_trace(mVcdFile, p_shl2_cast_mid2_fu_394_p3, "p_shl2_cast_mid2_fu_394_p3");
    sc_trace(mVcdFile, tmp_8_fu_406_p2, "tmp_8_fu_406_p2");
    sc_trace(mVcdFile, p_shl3_cast1_mid2_fu_412_p3, "p_shl3_cast1_mid2_fu_412_p3");
    sc_trace(mVcdFile, p_shl2_cast_mid1_fu_390_p1, "p_shl2_cast_mid1_fu_390_p1");
    sc_trace(mVcdFile, p_shl3_cast_mid1_fu_424_p1, "p_shl3_cast_mid1_fu_424_p1");
    sc_trace(mVcdFile, tmp_32_mid1_fu_428_p2, "tmp_32_mid1_fu_428_p2");
    sc_trace(mVcdFile, tmp_32_fu_320_p2, "tmp_32_fu_320_p2");
    sc_trace(mVcdFile, tmp_37_mid_fu_455_p2, "tmp_37_mid_fu_455_p2");
    sc_trace(mVcdFile, tmp_37_fu_340_p2, "tmp_37_fu_340_p2");
    sc_trace(mVcdFile, exitcond_fu_475_p2, "exitcond_fu_475_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_8_fu_469_p2, "not_exitcond_flatten_8_fu_469_p2");
    sc_trace(mVcdFile, h_mid_fu_364_p3, "h_mid_fu_364_p3");
    sc_trace(mVcdFile, exitcond5_mid_fu_481_p2, "exitcond5_mid_fu_481_p2");
    sc_trace(mVcdFile, tmp_12_fu_493_p2, "tmp_12_fu_493_p2");
    sc_trace(mVcdFile, h_1_fu_487_p2, "h_1_fu_487_p2");
    sc_trace(mVcdFile, h_cast2_mid1_fu_515_p1, "h_cast2_mid1_fu_515_p1");
    sc_trace(mVcdFile, p_shl3_cast1_mid2_cas_fu_420_p1, "p_shl3_cast1_mid2_cas_fu_420_p1");
    sc_trace(mVcdFile, tmp2_mid1_fu_519_p2, "tmp2_mid1_fu_519_p2");
    sc_trace(mVcdFile, p_shl2_cast_mid2_cast_fu_402_p1, "p_shl2_cast_mid2_cast_fu_402_p1");
    sc_trace(mVcdFile, tmp2_cast_mid1_fu_525_p1, "tmp2_cast_mid1_fu_525_p1");
    sc_trace(mVcdFile, tmp_37_mid1_fu_529_p2, "tmp_37_mid1_fu_529_p2");
    sc_trace(mVcdFile, p_shl4_mid277_v_v_fu_461_p3, "p_shl4_mid277_v_v_fu_461_p3");
    sc_trace(mVcdFile, p_shl7_fu_570_p3, "p_shl7_fu_570_p3");
    sc_trace(mVcdFile, p_shl8_fu_582_p3, "p_shl8_fu_582_p3");
    sc_trace(mVcdFile, p_shl7_cast_fu_578_p1, "p_shl7_cast_fu_578_p1");
    sc_trace(mVcdFile, p_shl8_cast_fu_590_p1, "p_shl8_cast_fu_590_p1");
    sc_trace(mVcdFile, cin_cast3_fu_566_p1, "cin_cast3_fu_566_p1");
    sc_trace(mVcdFile, tmp_43_fu_600_p2, "tmp_43_fu_600_p2");
    sc_trace(mVcdFile, p_shl6_fu_609_p3, "p_shl6_fu_609_p3");
    sc_trace(mVcdFile, y_cast1_fu_625_p1, "y_cast1_fu_625_p1");
    sc_trace(mVcdFile, tmp_42_fu_594_p2, "tmp_42_fu_594_p2");
    sc_trace(mVcdFile, tmp3_fu_629_p2, "tmp3_fu_629_p2");
    sc_trace(mVcdFile, tmp_51_fu_635_p2, "tmp_51_fu_635_p2");
    sc_trace(mVcdFile, p_shl1_fu_648_p3, "p_shl1_fu_648_p3");
    sc_trace(mVcdFile, p_shl_fu_640_p3, "p_shl_fu_640_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_656_p1, "p_shl1_cast_fu_656_p1");
    sc_trace(mVcdFile, tmp_43_cast_fu_605_p1, "tmp_43_cast_fu_605_p1");
    sc_trace(mVcdFile, y_cast_fu_621_p1, "y_cast_fu_621_p1");
    sc_trace(mVcdFile, tmp4_fu_666_p2, "tmp4_fu_666_p2");
    sc_trace(mVcdFile, tmp4_cast_fu_672_p1, "tmp4_cast_fu_672_p1");
    sc_trace(mVcdFile, p_shl6_cast_fu_617_p1, "p_shl6_cast_fu_617_p1");
    sc_trace(mVcdFile, exitcond_flatten8_fu_694_p2, "exitcond_flatten8_fu_694_p2");
    sc_trace(mVcdFile, cin_s_fu_708_p2, "cin_s_fu_708_p2");
    sc_trace(mVcdFile, p_shl7_mid1_fu_718_p3, "p_shl7_mid1_fu_718_p3");
    sc_trace(mVcdFile, p_shl8_mid1_fu_730_p3, "p_shl8_mid1_fu_730_p3");
    sc_trace(mVcdFile, p_shl7_cast_mid1_fu_726_p1, "p_shl7_cast_mid1_fu_726_p1");
    sc_trace(mVcdFile, p_shl8_cast_mid1_fu_738_p1, "p_shl8_cast_mid1_fu_738_p1");
    sc_trace(mVcdFile, tmp_42_mid1_fu_742_p2, "tmp_42_mid1_fu_742_p2");
    sc_trace(mVcdFile, cin_cast3_mid1_fu_714_p1, "cin_cast3_mid1_fu_714_p1");
    sc_trace(mVcdFile, tmp_43_mid1_fu_756_p2, "tmp_43_mid1_fu_756_p2");
    sc_trace(mVcdFile, tmp_43_cast_mid2_fu_761_p3, "tmp_43_cast_mid2_fu_761_p3");
    sc_trace(mVcdFile, p_shl6_mid1_fu_773_p3, "p_shl6_mid1_fu_773_p3");
    sc_trace(mVcdFile, p_shl6_cast_mid2_fu_785_p3, "p_shl6_cast_mid2_fu_785_p3");
    sc_trace(mVcdFile, tmp_51_mid_fu_797_p2, "tmp_51_mid_fu_797_p2");
    sc_trace(mVcdFile, p_shl1_mid_fu_810_p3, "p_shl1_mid_fu_810_p3");
    sc_trace(mVcdFile, p_shl_mid_fu_802_p3, "p_shl_mid_fu_802_p3");
    sc_trace(mVcdFile, p_shl1_cast_mid_fu_818_p1, "p_shl1_cast_mid_fu_818_p1");
    sc_trace(mVcdFile, tmp_52_mid_fu_822_p2, "tmp_52_mid_fu_822_p2");
    sc_trace(mVcdFile, tmp_52_fu_660_p2, "tmp_52_fu_660_p2");
    sc_trace(mVcdFile, tmp4_cast_mid_fu_836_p1, "tmp4_cast_mid_fu_836_p1");
    sc_trace(mVcdFile, p_shl6_cast_mid1_fu_781_p1, "p_shl6_cast_mid1_fu_781_p1");
    sc_trace(mVcdFile, tmp_mid_fu_840_p2, "tmp_mid_fu_840_p2");
    sc_trace(mVcdFile, tmp_fu_676_p2, "tmp_fu_676_p2");
    sc_trace(mVcdFile, exitcond1_fu_860_p2, "exitcond1_fu_860_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_854_p2, "not_exitcond_flatten_fu_854_p2");
    sc_trace(mVcdFile, y_mid_fu_700_p3, "y_mid_fu_700_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_866_p2, "exitcond_mid_fu_866_p2");
    sc_trace(mVcdFile, tmp_13_fu_886_p2, "tmp_13_fu_886_p2");
    sc_trace(mVcdFile, y_1_fu_880_p2, "y_1_fu_880_p2");
    sc_trace(mVcdFile, y_cast1_mid1_fu_904_p1, "y_cast1_mid1_fu_904_p1");
    sc_trace(mVcdFile, tmp_42_mid2_fu_748_p3, "tmp_42_mid2_fu_748_p3");
    sc_trace(mVcdFile, tmp3_mid1_fu_908_p2, "tmp3_mid1_fu_908_p2");
    sc_trace(mVcdFile, tmp_51_mid1_fu_914_p2, "tmp_51_mid1_fu_914_p2");
    sc_trace(mVcdFile, p_shl1_mid1_fu_927_p3, "p_shl1_mid1_fu_927_p3");
    sc_trace(mVcdFile, p_shl_mid1_fu_919_p3, "p_shl_mid1_fu_919_p3");
    sc_trace(mVcdFile, p_shl1_cast_mid1_fu_935_p1, "p_shl1_cast_mid1_fu_935_p1");
    sc_trace(mVcdFile, tmp_52_mid1_fu_939_p2, "tmp_52_mid1_fu_939_p2");
    sc_trace(mVcdFile, tmp_52_mid3_fu_828_p3, "tmp_52_mid3_fu_828_p3");
    sc_trace(mVcdFile, tmp_43_cast_mid2_cas_fu_769_p1, "tmp_43_cast_mid2_cas_fu_769_p1");
    sc_trace(mVcdFile, y_cast_mid1_fu_900_p1, "y_cast_mid1_fu_900_p1");
    sc_trace(mVcdFile, tmp4_mid1_fu_953_p2, "tmp4_mid1_fu_953_p2");
    sc_trace(mVcdFile, tmp4_cast_mid1_fu_959_p1, "tmp4_cast_mid1_fu_959_p1");
    sc_trace(mVcdFile, p_shl6_cast_mid2_cast_fu_793_p1, "p_shl6_cast_mid2_cast_fu_793_p1");
    sc_trace(mVcdFile, tmp_mid1_fu_963_p2, "tmp_mid1_fu_963_p2");
    sc_trace(mVcdFile, tmp_mid4_fu_846_p3, "tmp_mid4_fu_846_p3");
    sc_trace(mVcdFile, tmp_mid2_fu_969_p3, "tmp_mid2_fu_969_p3");
    sc_trace(mVcdFile, x_mid2_fu_892_p3, "x_mid2_fu_892_p3");
    sc_trace(mVcdFile, x_cast8_fu_997_p1, "x_cast8_fu_997_p1");
    sc_trace(mVcdFile, tmp_52_mid2_fu_945_p3, "tmp_52_mid2_fu_945_p3");
    sc_trace(mVcdFile, tmp5_fu_1001_p2, "tmp5_fu_1001_p2");
    sc_trace(mVcdFile, tmp_56_fu_1007_p2, "tmp_56_fu_1007_p2");
    sc_trace(mVcdFile, tmp_56_cast_fu_1012_p1, "tmp_56_cast_fu_1012_p1");
    sc_trace(mVcdFile, x_cast9_fu_993_p1, "x_cast9_fu_993_p1");
    sc_trace(mVcdFile, tmp6_fu_1021_p2, "tmp6_fu_1021_p2");
    sc_trace(mVcdFile, tmp6_cast_fu_1027_p1, "tmp6_cast_fu_1027_p1");
    sc_trace(mVcdFile, p_shl9_mid2_fu_977_p3, "p_shl9_mid2_fu_977_p3");
    sc_trace(mVcdFile, tmp_58_fu_1031_p2, "tmp_58_fu_1031_p2");
    sc_trace(mVcdFile, tmp_58_cast_fu_1037_p1, "tmp_58_cast_fu_1037_p1");
    sc_trace(mVcdFile, indvar_flatten_op_fu_1052_p2, "indvar_flatten_op_fu_1052_p2");
    sc_trace(mVcdFile, tmp7_fu_1066_p2, "tmp7_fu_1066_p2");
    sc_trace(mVcdFile, tmp7_cast_fu_1070_p1, "tmp7_cast_fu_1070_p1");
    sc_trace(mVcdFile, tmp_46_fu_1074_p2, "tmp_46_fu_1074_p2");
    sc_trace(mVcdFile, indvar_flatten51_op_fu_1089_p2, "indvar_flatten51_op_fu_1089_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

conv_2::~conv_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete c2_weight_U;
    delete c2_bias_U;
    delete top_net_fadd_32nsbkb_U14;
    delete top_net_fmul_32nscud_U15;
}

void conv_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_fu_682_p2.read()))) {
        cin_reg_221 = cin_mid2_fu_872_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        cin_reg_221 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        cout_reg_165 = c2_bias_load_mid2_v_reg_1121.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        cout_reg_165 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        h_reg_188 = h_cast_mid2_reg_1138.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        h_reg_188 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten3_reg_154 = indvar_flatten_next1_3_reg_1105.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten3_reg_154 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten4_reg_176 = indvar_flatten_next1_2_fu_1095_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten4_reg_176 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_fu_682_p2.read()))) {
        indvar_flatten5_reg_210 = indvar_flatten_next1_fu_688_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten5_reg_210 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_fu_682_p2.read()))) {
        indvar_flatten_reg_232 = indvar_flatten_next_fu_1058_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten_reg_232 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_reg_1182.read()))) {
        output_buffer_2_reg_254 = grp_fu_277_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_buffer_2_reg_254 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        w_reg_199 = w_1_fu_1084_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        w_reg_199 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_fu_682_p2.read()))) {
        x_reg_266 = x_1_fu_1046_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_reg_266 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten7_fu_682_p2.read()))) {
        y_reg_243 = y_mid2_fu_985_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_reg_243 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_346_p2.read(), ap_const_lv1_0))) {
        c2_bias_load_mid2_v_reg_1121 = c2_bias_load_mid2_v_fu_442_p3.read();
        exitcond_flatten6_reg_1110 = exitcond_flatten6_fu_358_p2.read();
        h_cast_mid2_reg_1138 = h_cast_mid2_fu_507_p3.read();
        p_shl4_mid2_v_v_reg_1144 = p_shl4_mid2_v_v_fu_535_p3.read();
        tmp_32_mid2_reg_1115 = tmp_32_mid2_fu_434_p3.read();
        w_mid2_reg_1131 = w_mid2_fu_499_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c2_bias_load_reg_1150 = c2_bias_q0.read();
        h_cast_mid2_cast_reg_1155 = h_cast_mid2_cast_fu_543_p1.read();
        p_shl4_mid2_reg_1162 = p_shl4_mid2_fu_546_p3.read();
        p_shl5_mid2_reg_1167 = p_shl5_mid2_fu_553_p3.read();
        w_cast2_reg_1177 = w_cast2_fu_563_p1.read();
        w_cast_reg_1172 = w_cast_fu_560_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten7_reg_1182 = exitcond_flatten7_fu_682_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvar_flatten_next1_3_reg_1105 = indvar_flatten_next1_3_fu_352_p2.read();
    }
}

void conv_2::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void conv_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_2::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_2::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void conv_2::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_2::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_2::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_2::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_2::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_2::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_flatten7_fu_682_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void conv_2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten_fu_346_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_2::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_2::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv_2::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_346_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_2::thread_c2_bias_address0() {
    c2_bias_address0 =  (sc_lv<4>) (c2_bias_load_mid2_fu_450_p1.read());
}

void conv_2::thread_c2_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c2_bias_ce0 = ap_const_logic_1;
    } else {
        c2_bias_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_c2_bias_load_mid2_fu_450_p1() {
    c2_bias_load_mid2_fu_450_p1 = esl_zext<64,5>(c2_bias_load_mid2_v_fu_442_p3.read());
}

void conv_2::thread_c2_bias_load_mid2_v_fu_442_p3() {
    c2_bias_load_mid2_v_fu_442_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? cout_s_fu_372_p2.read(): cout_reg_165.read());
}

void conv_2::thread_c2_weight_address0() {
    c2_weight_address0 =  (sc_lv<12>) (tmp_59_fu_1041_p1.read());
}

void conv_2::thread_c2_weight_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        c2_weight_ce0 = ap_const_logic_1;
    } else {
        c2_weight_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_cin_cast3_fu_566_p1() {
    cin_cast3_fu_566_p1 = esl_zext<8,3>(cin_reg_221.read());
}

void conv_2::thread_cin_cast3_mid1_fu_714_p1() {
    cin_cast3_mid1_fu_714_p1 = esl_zext<8,3>(cin_s_fu_708_p2.read());
}

void conv_2::thread_cin_mid2_fu_872_p3() {
    cin_mid2_fu_872_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? cin_s_fu_708_p2.read(): cin_reg_221.read());
}

void conv_2::thread_cin_s_fu_708_p2() {
    cin_s_fu_708_p2 = (!cin_reg_221.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(cin_reg_221.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv_2::thread_cout_s_fu_372_p2() {
    cout_s_fu_372_p2 = (!ap_const_lv5_1.is_01() || !cout_reg_165.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(cout_reg_165.read()));
}

void conv_2::thread_exitcond1_fu_860_p2() {
    exitcond1_fu_860_p2 = (!x_reg_266.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(x_reg_266.read() == ap_const_lv3_5);
}

void conv_2::thread_exitcond5_mid_fu_481_p2() {
    exitcond5_mid_fu_481_p2 = (exitcond_fu_475_p2.read() & not_exitcond_flatten_8_fu_469_p2.read());
}

void conv_2::thread_exitcond_flatten6_fu_358_p2() {
    exitcond_flatten6_fu_358_p2 = (!indvar_flatten4_reg_176.read().is_01() || !ap_const_lv8_64.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten4_reg_176.read() == ap_const_lv8_64);
}

void conv_2::thread_exitcond_flatten7_fu_682_p2() {
    exitcond_flatten7_fu_682_p2 = (!indvar_flatten5_reg_210.read().is_01() || !ap_const_lv8_96.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten5_reg_210.read() == ap_const_lv8_96);
}

void conv_2::thread_exitcond_flatten8_fu_694_p2() {
    exitcond_flatten8_fu_694_p2 = (!indvar_flatten_reg_232.read().is_01() || !ap_const_lv6_19.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_232.read() == ap_const_lv6_19);
}

void conv_2::thread_exitcond_flatten_fu_346_p2() {
    exitcond_flatten_fu_346_p2 = (!indvar_flatten3_reg_154.read().is_01() || !ap_const_lv11_640.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten3_reg_154.read() == ap_const_lv11_640);
}

void conv_2::thread_exitcond_fu_475_p2() {
    exitcond_fu_475_p2 = (!w_reg_199.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(w_reg_199.read() == ap_const_lv4_A);
}

void conv_2::thread_exitcond_mid_fu_866_p2() {
    exitcond_mid_fu_866_p2 = (exitcond1_fu_860_p2.read() & not_exitcond_flatten_fu_854_p2.read());
}

void conv_2::thread_grp_fu_277_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_277_p0 = c2_bias_load_reg_1150.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_277_p0 = tmp_s_fu_283_p2.read();
    } else {
        grp_fu_277_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void conv_2::thread_h_1_fu_487_p2() {
    h_1_fu_487_p2 = (!ap_const_lv4_1.is_01() || !h_mid_fu_364_p3.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(h_mid_fu_364_p3.read()));
}

void conv_2::thread_h_cast2_fu_326_p1() {
    h_cast2_fu_326_p1 = esl_zext<6,4>(h_reg_188.read());
}

void conv_2::thread_h_cast2_mid1_fu_515_p1() {
    h_cast2_mid1_fu_515_p1 = esl_zext<6,4>(h_1_fu_487_p2.read());
}

void conv_2::thread_h_cast_mid2_cast_fu_543_p1() {
    h_cast_mid2_cast_fu_543_p1 = esl_zext<8,4>(h_cast_mid2_reg_1138.read());
}

void conv_2::thread_h_cast_mid2_fu_507_p3() {
    h_cast_mid2_fu_507_p3 = (!exitcond5_mid_fu_481_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond5_mid_fu_481_p2.read()[0].to_bool())? h_1_fu_487_p2.read(): h_mid_fu_364_p3.read());
}

void conv_2::thread_h_mid_fu_364_p3() {
    h_mid_fu_364_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? ap_const_lv4_0: h_reg_188.read());
}

void conv_2::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<11>) (tmp_57_fu_1016_p1.read());
}

void conv_2::thread_in_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_indvar_flatten51_op_fu_1089_p2() {
    indvar_flatten51_op_fu_1089_p2 = (!indvar_flatten4_reg_176.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(indvar_flatten4_reg_176.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void conv_2::thread_indvar_flatten_next1_2_fu_1095_p3() {
    indvar_flatten_next1_2_fu_1095_p3 = (!exitcond_flatten6_reg_1110.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten6_reg_1110.read()[0].to_bool())? ap_const_lv8_1: indvar_flatten51_op_fu_1089_p2.read());
}

void conv_2::thread_indvar_flatten_next1_3_fu_352_p2() {
    indvar_flatten_next1_3_fu_352_p2 = (!ap_const_lv11_1.is_01() || !indvar_flatten3_reg_154.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_1) + sc_biguint<11>(indvar_flatten3_reg_154.read()));
}

void conv_2::thread_indvar_flatten_next1_fu_688_p2() {
    indvar_flatten_next1_fu_688_p2 = (!indvar_flatten5_reg_210.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(indvar_flatten5_reg_210.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void conv_2::thread_indvar_flatten_next_fu_1058_p3() {
    indvar_flatten_next_fu_1058_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<6>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? ap_const_lv6_1: indvar_flatten_op_fu_1052_p2.read());
}

void conv_2::thread_indvar_flatten_op_fu_1052_p2() {
    indvar_flatten_op_fu_1052_p2 = (!indvar_flatten_reg_232.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(indvar_flatten_reg_232.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_2::thread_not_exitcond_flatten_8_fu_469_p2() {
    not_exitcond_flatten_8_fu_469_p2 = (exitcond_flatten6_fu_358_p2.read() ^ ap_const_lv1_1);
}

void conv_2::thread_not_exitcond_flatten_fu_854_p2() {
    not_exitcond_flatten_fu_854_p2 = (exitcond_flatten8_fu_694_p2.read() ^ ap_const_lv1_1);
}

void conv_2::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<11>) (tmp_47_fu_1079_p1.read());
}

void conv_2::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_2::thread_output_r_d0() {
    output_r_d0 = grp_fu_277_p2.read();
}

void conv_2::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_2::thread_p_shl1_cast_fu_656_p1() {
    p_shl1_cast_fu_656_p1 = esl_sext<12,9>(p_shl1_fu_648_p3.read());
}

void conv_2::thread_p_shl1_cast_mid1_fu_935_p1() {
    p_shl1_cast_mid1_fu_935_p1 = esl_sext<12,9>(p_shl1_mid1_fu_927_p3.read());
}

void conv_2::thread_p_shl1_cast_mid_fu_818_p1() {
    p_shl1_cast_mid_fu_818_p1 = esl_sext<12,9>(p_shl1_mid_fu_810_p3.read());
}

void conv_2::thread_p_shl1_fu_648_p3() {
    p_shl1_fu_648_p3 = esl_concat<8,1>(tmp_51_fu_635_p2.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl1_mid1_fu_927_p3() {
    p_shl1_mid1_fu_927_p3 = esl_concat<8,1>(tmp_51_mid1_fu_914_p2.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl1_mid_fu_810_p3() {
    p_shl1_mid_fu_810_p3 = esl_concat<8,1>(tmp_51_mid_fu_797_p2.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl2_cast_fu_302_p1() {
    p_shl2_cast_fu_302_p1 = esl_zext<8,7>(p_shl2_fu_294_p3.read());
}

void conv_2::thread_p_shl2_cast_mid1_fu_390_p1() {
    p_shl2_cast_mid1_fu_390_p1 = esl_zext<8,7>(p_shl2_mid1_fu_382_p3.read());
}

void conv_2::thread_p_shl2_cast_mid2_cast_fu_402_p1() {
    p_shl2_cast_mid2_cast_fu_402_p1 = esl_zext<8,7>(p_shl2_cast_mid2_fu_394_p3.read());
}

void conv_2::thread_p_shl2_cast_mid2_fu_394_p3() {
    p_shl2_cast_mid2_fu_394_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<7>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? p_shl2_mid1_fu_382_p3.read(): p_shl2_fu_294_p3.read());
}

void conv_2::thread_p_shl2_fu_294_p3() {
    p_shl2_fu_294_p3 = esl_concat<4,3>(tmp_5_fu_290_p1.read(), ap_const_lv3_0);
}

void conv_2::thread_p_shl2_mid1_fu_382_p3() {
    p_shl2_mid1_fu_382_p3 = esl_concat<4,3>(tmp_7_fu_378_p1.read(), ap_const_lv3_0);
}

void conv_2::thread_p_shl3_cast1_fu_312_p1() {
    p_shl3_cast1_fu_312_p1 = esl_zext<6,5>(tmp_6_fu_306_p2.read());
}

void conv_2::thread_p_shl3_cast1_mid2_cas_fu_420_p1() {
    p_shl3_cast1_mid2_cas_fu_420_p1 = esl_zext<6,5>(p_shl3_cast1_mid2_fu_412_p3.read());
}

void conv_2::thread_p_shl3_cast1_mid2_fu_412_p3() {
    p_shl3_cast1_mid2_fu_412_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? tmp_8_fu_406_p2.read(): tmp_6_fu_306_p2.read());
}

void conv_2::thread_p_shl3_cast_fu_316_p1() {
    p_shl3_cast_fu_316_p1 = esl_zext<8,5>(tmp_6_fu_306_p2.read());
}

void conv_2::thread_p_shl3_cast_mid1_fu_424_p1() {
    p_shl3_cast_mid1_fu_424_p1 = esl_zext<8,5>(tmp_8_fu_406_p2.read());
}

void conv_2::thread_p_shl4_mid277_v_v_fu_461_p3() {
    p_shl4_mid277_v_v_fu_461_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? tmp_37_mid_fu_455_p2.read(): tmp_37_fu_340_p2.read());
}

void conv_2::thread_p_shl4_mid2_fu_546_p3() {
    p_shl4_mid2_fu_546_p3 = esl_concat<8,3>(p_shl4_mid2_v_v_reg_1144.read(), ap_const_lv3_0);
}

void conv_2::thread_p_shl4_mid2_v_v_fu_535_p3() {
    p_shl4_mid2_v_v_fu_535_p3 = (!exitcond5_mid_fu_481_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond5_mid_fu_481_p2.read()[0].to_bool())? tmp_37_mid1_fu_529_p2.read(): p_shl4_mid277_v_v_fu_461_p3.read());
}

void conv_2::thread_p_shl5_mid2_fu_553_p3() {
    p_shl5_mid2_fu_553_p3 = esl_concat<8,1>(p_shl4_mid2_v_v_reg_1144.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl6_cast_fu_617_p1() {
    p_shl6_cast_fu_617_p1 = esl_sext<11,10>(p_shl6_fu_609_p3.read());
}

void conv_2::thread_p_shl6_cast_mid1_fu_781_p1() {
    p_shl6_cast_mid1_fu_781_p1 = esl_sext<11,10>(p_shl6_mid1_fu_773_p3.read());
}

void conv_2::thread_p_shl6_cast_mid2_cast_fu_793_p1() {
    p_shl6_cast_mid2_cast_fu_793_p1 = esl_sext<11,10>(p_shl6_cast_mid2_fu_785_p3.read());
}

void conv_2::thread_p_shl6_cast_mid2_fu_785_p3() {
    p_shl6_cast_mid2_fu_785_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? p_shl6_mid1_fu_773_p3.read(): p_shl6_fu_609_p3.read());
}

void conv_2::thread_p_shl6_fu_609_p3() {
    p_shl6_fu_609_p3 = esl_concat<8,2>(tmp_43_fu_600_p2.read(), ap_const_lv2_0);
}

void conv_2::thread_p_shl6_mid1_fu_773_p3() {
    p_shl6_mid1_fu_773_p3 = esl_concat<8,2>(tmp_43_mid1_fu_756_p2.read(), ap_const_lv2_0);
}

void conv_2::thread_p_shl7_cast_fu_578_p1() {
    p_shl7_cast_fu_578_p1 = esl_zext<8,7>(p_shl7_fu_570_p3.read());
}

void conv_2::thread_p_shl7_cast_mid1_fu_726_p1() {
    p_shl7_cast_mid1_fu_726_p1 = esl_zext<8,7>(p_shl7_mid1_fu_718_p3.read());
}

void conv_2::thread_p_shl7_fu_570_p3() {
    p_shl7_fu_570_p3 = esl_concat<3,4>(cin_reg_221.read(), ap_const_lv4_0);
}

void conv_2::thread_p_shl7_mid1_fu_718_p3() {
    p_shl7_mid1_fu_718_p3 = esl_concat<3,4>(cin_s_fu_708_p2.read(), ap_const_lv4_0);
}

void conv_2::thread_p_shl8_cast_fu_590_p1() {
    p_shl8_cast_fu_590_p1 = esl_zext<8,4>(p_shl8_fu_582_p3.read());
}

void conv_2::thread_p_shl8_cast_mid1_fu_738_p1() {
    p_shl8_cast_mid1_fu_738_p1 = esl_zext<8,4>(p_shl8_mid1_fu_730_p3.read());
}

void conv_2::thread_p_shl8_fu_582_p3() {
    p_shl8_fu_582_p3 = esl_concat<3,1>(cin_reg_221.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl8_mid1_fu_730_p3() {
    p_shl8_mid1_fu_730_p3 = esl_concat<3,1>(cin_s_fu_708_p2.read(), ap_const_lv1_0);
}

void conv_2::thread_p_shl9_mid2_fu_977_p3() {
    p_shl9_mid2_fu_977_p3 = esl_concat<11,2>(tmp_mid2_fu_969_p3.read(), ap_const_lv2_0);
}

void conv_2::thread_p_shl_fu_640_p3() {
    p_shl_fu_640_p3 = esl_concat<8,4>(tmp_51_fu_635_p2.read(), ap_const_lv4_0);
}

void conv_2::thread_p_shl_mid1_fu_919_p3() {
    p_shl_mid1_fu_919_p3 = esl_concat<8,4>(tmp_51_mid1_fu_914_p2.read(), ap_const_lv4_0);
}

void conv_2::thread_p_shl_mid_fu_802_p3() {
    p_shl_mid_fu_802_p3 = esl_concat<8,4>(tmp_51_mid_fu_797_p2.read(), ap_const_lv4_0);
}

void conv_2::thread_tmp2_cast_fu_336_p1() {
    tmp2_cast_fu_336_p1 = esl_zext<8,6>(tmp2_fu_330_p2.read());
}

void conv_2::thread_tmp2_cast_mid1_fu_525_p1() {
    tmp2_cast_mid1_fu_525_p1 = esl_zext<8,6>(tmp2_mid1_fu_519_p2.read());
}

void conv_2::thread_tmp2_fu_330_p2() {
    tmp2_fu_330_p2 = (!p_shl3_cast1_fu_312_p1.read().is_01() || !h_cast2_fu_326_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(p_shl3_cast1_fu_312_p1.read()) + sc_biguint<6>(h_cast2_fu_326_p1.read()));
}

void conv_2::thread_tmp2_mid1_fu_519_p2() {
    tmp2_mid1_fu_519_p2 = (!h_cast2_mid1_fu_515_p1.read().is_01() || !p_shl3_cast1_mid2_cas_fu_420_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(h_cast2_mid1_fu_515_p1.read()) + sc_biguint<6>(p_shl3_cast1_mid2_cas_fu_420_p1.read()));
}

void conv_2::thread_tmp3_fu_629_p2() {
    tmp3_fu_629_p2 = (!y_cast1_fu_625_p1.read().is_01() || !tmp_42_fu_594_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(y_cast1_fu_625_p1.read()) + sc_biguint<8>(tmp_42_fu_594_p2.read()));
}

void conv_2::thread_tmp3_mid1_fu_908_p2() {
    tmp3_mid1_fu_908_p2 = (!y_cast1_mid1_fu_904_p1.read().is_01() || !tmp_42_mid2_fu_748_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(y_cast1_mid1_fu_904_p1.read()) + sc_biguint<8>(tmp_42_mid2_fu_748_p3.read()));
}

void conv_2::thread_tmp4_cast_fu_672_p1() {
    tmp4_cast_fu_672_p1 = esl_sext<11,9>(tmp4_fu_666_p2.read());
}

void conv_2::thread_tmp4_cast_mid1_fu_959_p1() {
    tmp4_cast_mid1_fu_959_p1 = esl_sext<11,9>(tmp4_mid1_fu_953_p2.read());
}

void conv_2::thread_tmp4_cast_mid_fu_836_p1() {
    tmp4_cast_mid_fu_836_p1 = esl_sext<11,8>(tmp_43_mid1_fu_756_p2.read());
}

void conv_2::thread_tmp4_fu_666_p2() {
    tmp4_fu_666_p2 = (!tmp_43_cast_fu_605_p1.read().is_01() || !y_cast_fu_621_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(tmp_43_cast_fu_605_p1.read()) + sc_biguint<9>(y_cast_fu_621_p1.read()));
}

void conv_2::thread_tmp4_mid1_fu_953_p2() {
    tmp4_mid1_fu_953_p2 = (!tmp_43_cast_mid2_cas_fu_769_p1.read().is_01() || !y_cast_mid1_fu_900_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(tmp_43_cast_mid2_cas_fu_769_p1.read()) + sc_biguint<9>(y_cast_mid1_fu_900_p1.read()));
}

void conv_2::thread_tmp5_fu_1001_p2() {
    tmp5_fu_1001_p2 = (!x_cast8_fu_997_p1.read().is_01() || !tmp_52_mid2_fu_945_p3.read().is_01())? sc_lv<12>(): (sc_biguint<12>(x_cast8_fu_997_p1.read()) + sc_biguint<12>(tmp_52_mid2_fu_945_p3.read()));
}

void conv_2::thread_tmp6_cast_fu_1027_p1() {
    tmp6_cast_fu_1027_p1 = esl_sext<13,11>(tmp6_fu_1021_p2.read());
}

void conv_2::thread_tmp6_fu_1021_p2() {
    tmp6_fu_1021_p2 = (!tmp_mid2_fu_969_p3.read().is_01() || !x_cast9_fu_993_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_mid2_fu_969_p3.read()) + sc_biguint<11>(x_cast9_fu_993_p1.read()));
}

void conv_2::thread_tmp7_cast_fu_1070_p1() {
    tmp7_cast_fu_1070_p1 = esl_zext<11,9>(tmp7_fu_1066_p2.read());
}

void conv_2::thread_tmp7_fu_1066_p2() {
    tmp7_fu_1066_p2 = (!p_shl5_mid2_reg_1167.read().is_01() || !w_cast_reg_1172.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl5_mid2_reg_1167.read()) + sc_biguint<9>(w_cast_reg_1172.read()));
}

void conv_2::thread_tmp_12_fu_493_p2() {
    tmp_12_fu_493_p2 = (exitcond5_mid_fu_481_p2.read() | exitcond_flatten6_fu_358_p2.read());
}

void conv_2::thread_tmp_13_fu_886_p2() {
    tmp_13_fu_886_p2 = (exitcond_mid_fu_866_p2.read() | exitcond_flatten8_fu_694_p2.read());
}

void conv_2::thread_tmp_32_fu_320_p2() {
    tmp_32_fu_320_p2 = (!p_shl2_cast_fu_302_p1.read().is_01() || !p_shl3_cast_fu_316_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl2_cast_fu_302_p1.read()) - sc_biguint<8>(p_shl3_cast_fu_316_p1.read()));
}

void conv_2::thread_tmp_32_mid1_fu_428_p2() {
    tmp_32_mid1_fu_428_p2 = (!p_shl2_cast_mid1_fu_390_p1.read().is_01() || !p_shl3_cast_mid1_fu_424_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl2_cast_mid1_fu_390_p1.read()) - sc_biguint<8>(p_shl3_cast_mid1_fu_424_p1.read()));
}

void conv_2::thread_tmp_32_mid2_fu_434_p3() {
    tmp_32_mid2_fu_434_p3 = (!exitcond_flatten6_fu_358_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten6_fu_358_p2.read()[0].to_bool())? tmp_32_mid1_fu_428_p2.read(): tmp_32_fu_320_p2.read());
}

void conv_2::thread_tmp_37_fu_340_p2() {
    tmp_37_fu_340_p2 = (!tmp2_cast_fu_336_p1.read().is_01() || !p_shl2_cast_fu_302_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp2_cast_fu_336_p1.read()) + sc_biguint<8>(p_shl2_cast_fu_302_p1.read()));
}

void conv_2::thread_tmp_37_mid1_fu_529_p2() {
    tmp_37_mid1_fu_529_p2 = (!p_shl2_cast_mid2_cast_fu_402_p1.read().is_01() || !tmp2_cast_mid1_fu_525_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl2_cast_mid2_cast_fu_402_p1.read()) + sc_biguint<8>(tmp2_cast_mid1_fu_525_p1.read()));
}

void conv_2::thread_tmp_37_mid_fu_455_p2() {
    tmp_37_mid_fu_455_p2 = (!p_shl2_cast_mid1_fu_390_p1.read().is_01() || !p_shl3_cast_mid1_fu_424_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl2_cast_mid1_fu_390_p1.read()) + sc_biguint<8>(p_shl3_cast_mid1_fu_424_p1.read()));
}

void conv_2::thread_tmp_42_fu_594_p2() {
    tmp_42_fu_594_p2 = (!p_shl7_cast_fu_578_p1.read().is_01() || !p_shl8_cast_fu_590_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl7_cast_fu_578_p1.read()) - sc_biguint<8>(p_shl8_cast_fu_590_p1.read()));
}

void conv_2::thread_tmp_42_mid1_fu_742_p2() {
    tmp_42_mid1_fu_742_p2 = (!p_shl7_cast_mid1_fu_726_p1.read().is_01() || !p_shl8_cast_mid1_fu_738_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl7_cast_mid1_fu_726_p1.read()) - sc_biguint<8>(p_shl8_cast_mid1_fu_738_p1.read()));
}

void conv_2::thread_tmp_42_mid2_fu_748_p3() {
    tmp_42_mid2_fu_748_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? tmp_42_mid1_fu_742_p2.read(): tmp_42_fu_594_p2.read());
}

void conv_2::thread_tmp_43_cast_fu_605_p1() {
    tmp_43_cast_fu_605_p1 = esl_sext<9,8>(tmp_43_fu_600_p2.read());
}

void conv_2::thread_tmp_43_cast_mid2_cas_fu_769_p1() {
    tmp_43_cast_mid2_cas_fu_769_p1 = esl_sext<9,8>(tmp_43_cast_mid2_fu_761_p3.read());
}

void conv_2::thread_tmp_43_cast_mid2_fu_761_p3() {
    tmp_43_cast_mid2_fu_761_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? tmp_43_mid1_fu_756_p2.read(): tmp_43_fu_600_p2.read());
}

void conv_2::thread_tmp_43_fu_600_p2() {
    tmp_43_fu_600_p2 = (!tmp_32_mid2_reg_1115.read().is_01() || !cin_cast3_fu_566_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_32_mid2_reg_1115.read()) + sc_biguint<8>(cin_cast3_fu_566_p1.read()));
}

void conv_2::thread_tmp_43_mid1_fu_756_p2() {
    tmp_43_mid1_fu_756_p2 = (!tmp_32_mid2_reg_1115.read().is_01() || !cin_cast3_mid1_fu_714_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_32_mid2_reg_1115.read()) + sc_biguint<8>(cin_cast3_mid1_fu_714_p1.read()));
}

void conv_2::thread_tmp_46_fu_1074_p2() {
    tmp_46_fu_1074_p2 = (!tmp7_cast_fu_1070_p1.read().is_01() || !p_shl4_mid2_reg_1162.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp7_cast_fu_1070_p1.read()) + sc_biguint<11>(p_shl4_mid2_reg_1162.read()));
}

void conv_2::thread_tmp_47_fu_1079_p1() {
    tmp_47_fu_1079_p1 = esl_zext<64,11>(tmp_46_fu_1074_p2.read());
}

void conv_2::thread_tmp_51_fu_635_p2() {
    tmp_51_fu_635_p2 = (!tmp3_fu_629_p2.read().is_01() || !h_cast_mid2_cast_reg_1155.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp3_fu_629_p2.read()) + sc_biguint<8>(h_cast_mid2_cast_reg_1155.read()));
}

void conv_2::thread_tmp_51_mid1_fu_914_p2() {
    tmp_51_mid1_fu_914_p2 = (!tmp3_mid1_fu_908_p2.read().is_01() || !h_cast_mid2_cast_reg_1155.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp3_mid1_fu_908_p2.read()) + sc_biguint<8>(h_cast_mid2_cast_reg_1155.read()));
}

void conv_2::thread_tmp_51_mid_fu_797_p2() {
    tmp_51_mid_fu_797_p2 = (!tmp_42_mid1_fu_742_p2.read().is_01() || !h_cast_mid2_cast_reg_1155.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_42_mid1_fu_742_p2.read()) + sc_biguint<8>(h_cast_mid2_cast_reg_1155.read()));
}

void conv_2::thread_tmp_52_fu_660_p2() {
    tmp_52_fu_660_p2 = (!p_shl_fu_640_p3.read().is_01() || !p_shl1_cast_fu_656_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl_fu_640_p3.read()) - sc_bigint<12>(p_shl1_cast_fu_656_p1.read()));
}

void conv_2::thread_tmp_52_mid1_fu_939_p2() {
    tmp_52_mid1_fu_939_p2 = (!p_shl_mid1_fu_919_p3.read().is_01() || !p_shl1_cast_mid1_fu_935_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl_mid1_fu_919_p3.read()) - sc_bigint<12>(p_shl1_cast_mid1_fu_935_p1.read()));
}

void conv_2::thread_tmp_52_mid2_fu_945_p3() {
    tmp_52_mid2_fu_945_p3 = (!exitcond_mid_fu_866_p2.read()[0].is_01())? sc_lv<12>(): ((exitcond_mid_fu_866_p2.read()[0].to_bool())? tmp_52_mid1_fu_939_p2.read(): tmp_52_mid3_fu_828_p3.read());
}

void conv_2::thread_tmp_52_mid3_fu_828_p3() {
    tmp_52_mid3_fu_828_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<12>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? tmp_52_mid_fu_822_p2.read(): tmp_52_fu_660_p2.read());
}

void conv_2::thread_tmp_52_mid_fu_822_p2() {
    tmp_52_mid_fu_822_p2 = (!p_shl_mid_fu_802_p3.read().is_01() || !p_shl1_cast_mid_fu_818_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl_mid_fu_802_p3.read()) - sc_bigint<12>(p_shl1_cast_mid_fu_818_p1.read()));
}

void conv_2::thread_tmp_56_cast_fu_1012_p1() {
    tmp_56_cast_fu_1012_p1 = esl_sext<32,12>(tmp_56_fu_1007_p2.read());
}

void conv_2::thread_tmp_56_fu_1007_p2() {
    tmp_56_fu_1007_p2 = (!tmp5_fu_1001_p2.read().is_01() || !w_cast2_reg_1177.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp5_fu_1001_p2.read()) + sc_biguint<12>(w_cast2_reg_1177.read()));
}

void conv_2::thread_tmp_57_fu_1016_p1() {
    tmp_57_fu_1016_p1 = esl_zext<64,32>(tmp_56_cast_fu_1012_p1.read());
}

void conv_2::thread_tmp_58_cast_fu_1037_p1() {
    tmp_58_cast_fu_1037_p1 = esl_sext<32,13>(tmp_58_fu_1031_p2.read());
}

void conv_2::thread_tmp_58_fu_1031_p2() {
    tmp_58_fu_1031_p2 = (!tmp6_cast_fu_1027_p1.read().is_01() || !p_shl9_mid2_fu_977_p3.read().is_01())? sc_lv<13>(): (sc_bigint<13>(tmp6_cast_fu_1027_p1.read()) + sc_biguint<13>(p_shl9_mid2_fu_977_p3.read()));
}

void conv_2::thread_tmp_59_fu_1041_p1() {
    tmp_59_fu_1041_p1 = esl_zext<64,32>(tmp_58_cast_fu_1037_p1.read());
}

void conv_2::thread_tmp_5_fu_290_p1() {
    tmp_5_fu_290_p1 = cout_reg_165.read().range(4-1, 0);
}

void conv_2::thread_tmp_6_fu_306_p2() {
    tmp_6_fu_306_p2 = (!ap_const_lv5_1.is_01())? sc_lv<5>(): cout_reg_165.read() << (unsigned short)ap_const_lv5_1.to_uint();
}

void conv_2::thread_tmp_7_fu_378_p1() {
    tmp_7_fu_378_p1 = cout_s_fu_372_p2.read().range(4-1, 0);
}

void conv_2::thread_tmp_8_fu_406_p2() {
    tmp_8_fu_406_p2 = (!ap_const_lv5_1.is_01())? sc_lv<5>(): cout_s_fu_372_p2.read() << (unsigned short)ap_const_lv5_1.to_uint();
}

void conv_2::thread_tmp_fu_676_p2() {
    tmp_fu_676_p2 = (!tmp4_cast_fu_672_p1.read().is_01() || !p_shl6_cast_fu_617_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(tmp4_cast_fu_672_p1.read()) + sc_bigint<11>(p_shl6_cast_fu_617_p1.read()));
}

void conv_2::thread_tmp_mid1_fu_963_p2() {
    tmp_mid1_fu_963_p2 = (!tmp4_cast_mid1_fu_959_p1.read().is_01() || !p_shl6_cast_mid2_cast_fu_793_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(tmp4_cast_mid1_fu_959_p1.read()) + sc_bigint<11>(p_shl6_cast_mid2_cast_fu_793_p1.read()));
}

void conv_2::thread_tmp_mid2_fu_969_p3() {
    tmp_mid2_fu_969_p3 = (!exitcond_mid_fu_866_p2.read()[0].is_01())? sc_lv<11>(): ((exitcond_mid_fu_866_p2.read()[0].to_bool())? tmp_mid1_fu_963_p2.read(): tmp_mid4_fu_846_p3.read());
}

void conv_2::thread_tmp_mid4_fu_846_p3() {
    tmp_mid4_fu_846_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<11>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? tmp_mid_fu_840_p2.read(): tmp_fu_676_p2.read());
}

void conv_2::thread_tmp_mid_fu_840_p2() {
    tmp_mid_fu_840_p2 = (!tmp4_cast_mid_fu_836_p1.read().is_01() || !p_shl6_cast_mid1_fu_781_p1.read().is_01())? sc_lv<11>(): (sc_bigint<11>(tmp4_cast_mid_fu_836_p1.read()) + sc_bigint<11>(p_shl6_cast_mid1_fu_781_p1.read()));
}

void conv_2::thread_w_1_fu_1084_p2() {
    w_1_fu_1084_p2 = (!w_mid2_reg_1131.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(w_mid2_reg_1131.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_2::thread_w_cast2_fu_563_p1() {
    w_cast2_fu_563_p1 = esl_zext<12,4>(w_mid2_reg_1131.read());
}

void conv_2::thread_w_cast_fu_560_p1() {
    w_cast_fu_560_p1 = esl_zext<9,4>(w_mid2_reg_1131.read());
}

void conv_2::thread_w_mid2_fu_499_p3() {
    w_mid2_fu_499_p3 = (!tmp_12_fu_493_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_12_fu_493_p2.read()[0].to_bool())? ap_const_lv4_0: w_reg_199.read());
}

void conv_2::thread_x_1_fu_1046_p2() {
    x_1_fu_1046_p2 = (!x_mid2_fu_892_p3.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(x_mid2_fu_892_p3.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv_2::thread_x_cast8_fu_997_p1() {
    x_cast8_fu_997_p1 = esl_zext<12,3>(x_mid2_fu_892_p3.read());
}

void conv_2::thread_x_cast9_fu_993_p1() {
    x_cast9_fu_993_p1 = esl_zext<11,3>(x_mid2_fu_892_p3.read());
}

void conv_2::thread_x_mid2_fu_892_p3() {
    x_mid2_fu_892_p3 = (!tmp_13_fu_886_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_13_fu_886_p2.read()[0].to_bool())? ap_const_lv3_0: x_reg_266.read());
}

void conv_2::thread_y_1_fu_880_p2() {
    y_1_fu_880_p2 = (!y_mid_fu_700_p3.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(y_mid_fu_700_p3.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void conv_2::thread_y_cast1_fu_625_p1() {
    y_cast1_fu_625_p1 = esl_zext<8,3>(y_reg_243.read());
}

void conv_2::thread_y_cast1_mid1_fu_904_p1() {
    y_cast1_mid1_fu_904_p1 = esl_zext<8,3>(y_1_fu_880_p2.read());
}

void conv_2::thread_y_cast_fu_621_p1() {
    y_cast_fu_621_p1 = esl_zext<9,3>(y_reg_243.read());
}

void conv_2::thread_y_cast_mid1_fu_900_p1() {
    y_cast_mid1_fu_900_p1 = esl_zext<9,3>(y_1_fu_880_p2.read());
}

void conv_2::thread_y_mid2_fu_985_p3() {
    y_mid2_fu_985_p3 = (!exitcond_mid_fu_866_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_mid_fu_866_p2.read()[0].to_bool())? y_1_fu_880_p2.read(): y_mid_fu_700_p3.read());
}

void conv_2::thread_y_mid_fu_700_p3() {
    y_mid_fu_700_p3 = (!exitcond_flatten8_fu_694_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_flatten8_fu_694_p2.read()[0].to_bool())? ap_const_lv3_0: y_reg_243.read());
}

void conv_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten_fu_346_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten7_fu_682_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten7_fu_682_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

