// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_4.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_4::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_4::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> conv_4::ap_ST_fsm_state1 = "1";
const sc_lv<5> conv_4::ap_ST_fsm_state2 = "10";
const sc_lv<5> conv_4::ap_ST_fsm_state3 = "100";
const sc_lv<5> conv_4::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<5> conv_4::ap_ST_fsm_state6 = "10000";
const bool conv_4::ap_const_boolean_1 = true;
const sc_lv<32> conv_4::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_4::ap_const_lv32_1 = "1";
const sc_lv<1> conv_4::ap_const_lv1_0 = "0";
const sc_lv<32> conv_4::ap_const_lv32_2 = "10";
const sc_lv<32> conv_4::ap_const_lv32_3 = "11";
const bool conv_4::ap_const_boolean_0 = false;
const sc_lv<32> conv_4::ap_const_lv32_4 = "100";
const sc_lv<1> conv_4::ap_const_lv1_1 = "1";
const sc_lv<7> conv_4::ap_const_lv7_0 = "0000000";
const sc_lv<2> conv_4::ap_const_lv2_0 = "00";
const sc_lv<3> conv_4::ap_const_lv3_0 = "000";
const sc_lv<7> conv_4::ap_const_lv7_54 = "1010100";
const sc_lv<7> conv_4::ap_const_lv7_1 = "1";
const sc_lv<2> conv_4::ap_const_lv2_1 = "1";
const sc_lv<7> conv_4::ap_const_lv7_78 = "1111000";

conv_4::conv_4(sc_module_name name) : sc_module(name), mVcdFile(0) {
    c4_weight_U = new conv_4_c4_weight("c4_weight_U");
    c4_weight_U->clk(ap_clk);
    c4_weight_U->reset(ap_rst);
    c4_weight_U->address0(c4_weight_address0);
    c4_weight_U->ce0(c4_weight_ce0);
    c4_weight_U->q0(c4_weight_q0);
    c4_bias_U = new conv_4_c4_bias("c4_bias_U");
    c4_bias_U->clk(ap_clk);
    c4_bias_U->reset(ap_rst);
    c4_bias_U->address0(c4_bias_address0);
    c4_bias_U->ce0(c4_bias_ce0);
    c4_bias_U->q0(c4_bias_q0);
    top_net_fadd_32nsbkb_U29 = new top_net_fadd_32nsbkb<1,1,32,32,32>("top_net_fadd_32nsbkb_U29");
    top_net_fadd_32nsbkb_U29->din0(grp_fu_240_p0);
    top_net_fadd_32nsbkb_U29->din1(output_buffer_2_reg_216);
    top_net_fadd_32nsbkb_U29->dout(grp_fu_240_p2);
    top_net_fmul_32nscud_U30 = new top_net_fmul_32nscud<1,1,32,32,32>("top_net_fmul_32nscud_U30");
    top_net_fmul_32nscud_U30->din0(in_r_q0);
    top_net_fmul_32nscud_U30->din1(c4_weight_q0);
    top_net_fmul_32nscud_U30->dout(tmp_42_fu_246_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( exitcond_flatten8_fu_417_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten7_fu_283_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_cin_phi_fu_187_p4);
    sensitive << ( cin_reg_183 );
    sensitive << ( exitcond_flatten8_reg_619 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp4_mid2_v_v_reg_628 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_x_phi_fu_232_p4);
    sensitive << ( x_reg_228 );
    sensitive << ( exitcond_flatten8_reg_619 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_y_phi_fu_209_p4);
    sensitive << ( y_reg_205 );
    sensitive << ( exitcond_flatten8_reg_619 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp1_cast_mid2_v_v_reg_633 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten7_fu_283_p2 );

    SC_METHOD(thread_c4_bias_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( c4_bias_load_mid2_fu_353_p1 );

    SC_METHOD(thread_c4_bias_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_c4_bias_load_mid2_fu_353_p1);
    sensitive << ( c4_bias_load_mid2_v_fu_345_p3 );

    SC_METHOD(thread_c4_bias_load_mid2_v_fu_345_p3);
    sensitive << ( exitcond_flatten_fu_295_p2 );
    sensitive << ( cout_reg_123 );
    sensitive << ( cout_s_fu_301_p2 );

    SC_METHOD(thread_c4_weight_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_41_fu_530_p1 );

    SC_METHOD(thread_c4_weight_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_cin_s_fu_453_p2);
    sensitive << ( ap_phi_mux_cin_phi_fu_187_p4 );

    SC_METHOD(thread_cout_s_fu_301_p2);
    sensitive << ( cout_reg_123 );

    SC_METHOD(thread_exitcond_flatten2_fu_429_p2);
    sensitive << ( indvar_flatten_reg_194 );
    sensitive << ( exitcond_flatten8_fu_417_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten7_fu_283_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten6_reg_112 );

    SC_METHOD(thread_exitcond_flatten8_fu_417_p2);
    sensitive << ( indvar_flatten8_reg_172 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten_fu_295_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten7_fu_283_p2 );
    sensitive << ( indvar_flatten7_reg_134 );

    SC_METHOD(thread_grp_fu_240_p0);
    sensitive << ( c4_bias_load_reg_603 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_42_fu_246_p2 );

    SC_METHOD(thread_h_1_fu_392_p2);
    sensitive << ( exitcond_flatten_reg_579 );
    sensitive << ( h_not_fu_386_p2 );

    SC_METHOD(thread_h_cast9_mid2_cast_fu_405_p1);
    sensitive << ( h_cast9_mid2_fu_397_p3 );

    SC_METHOD(thread_h_cast9_mid2_fu_397_p3);
    sensitive << ( w_mid_fu_369_p2 );
    sensitive << ( h_1_fu_392_p2 );
    sensitive << ( h_cast9_mid_fu_380_p2 );

    SC_METHOD(thread_h_cast9_mid_fu_380_p2);
    sensitive << ( h_reg_146 );
    sensitive << ( not_exitcond_flatten_5_fu_375_p2 );

    SC_METHOD(thread_h_mid2_fu_409_p3);
    sensitive << ( w_mid_fu_369_p2 );
    sensitive << ( h_1_fu_392_p2 );
    sensitive << ( h_mid_fu_363_p2 );

    SC_METHOD(thread_h_mid_fu_363_p2);
    sensitive << ( h_reg_146 );
    sensitive << ( not_exitcond_flatten_4_fu_358_p2 );

    SC_METHOD(thread_h_not_fu_386_p2);
    sensitive << ( h_reg_146 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_39_fu_511_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_indvar_flatten23_op_fu_558_p2);
    sensitive << ( indvar_flatten7_reg_134 );

    SC_METHOD(thread_indvar_flatten_next6_fu_564_p3);
    sensitive << ( exitcond_flatten_reg_579 );
    sensitive << ( indvar_flatten23_op_fu_558_p2 );

    SC_METHOD(thread_indvar_flatten_next7_fu_289_p2);
    sensitive << ( indvar_flatten6_reg_112 );

    SC_METHOD(thread_indvar_flatten_next8_fu_423_p2);
    sensitive << ( indvar_flatten8_reg_172 );

    SC_METHOD(thread_indvar_flatten_next_fu_541_p3);
    sensitive << ( exitcond_flatten2_fu_429_p2 );
    sensitive << ( indvar_flatten_op_fu_535_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_535_p2);
    sensitive << ( indvar_flatten_reg_194 );

    SC_METHOD(thread_not_exitcond_flatten_4_fu_358_p2);
    sensitive << ( exitcond_flatten_reg_579 );

    SC_METHOD(thread_not_exitcond_flatten_5_fu_375_p2);
    sensitive << ( exitcond_flatten_reg_579 );

    SC_METHOD(thread_not_exitcond_flatten_fu_435_p2);
    sensitive << ( exitcond_flatten2_fu_429_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_36_fu_553_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( grp_fu_240_p2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_p_shl1_cast_fu_273_p1);
    sensitive << ( p_shl1_fu_265_p3 );

    SC_METHOD(thread_p_shl1_cast_mid1_fu_327_p1);
    sensitive << ( p_shl1_mid1_fu_319_p3 );

    SC_METHOD(thread_p_shl1_fu_265_p3);
    sensitive << ( cout_reg_123 );

    SC_METHOD(thread_p_shl1_mid1_fu_319_p3);
    sensitive << ( cout_s_fu_301_p2 );

    SC_METHOD(thread_p_shl_cast_fu_261_p1);
    sensitive << ( p_shl_fu_253_p3 );

    SC_METHOD(thread_p_shl_cast_mid1_fu_315_p1);
    sensitive << ( p_shl_mid1_fu_307_p3 );

    SC_METHOD(thread_p_shl_fu_253_p3);
    sensitive << ( cout_reg_123 );

    SC_METHOD(thread_p_shl_mid1_fu_307_p3);
    sensitive << ( cout_s_fu_301_p2 );

    SC_METHOD(thread_tmp1_cast_mid2_fu_501_p1);
    sensitive << ( tmp1_cast_mid2_v_fu_496_p2 );

    SC_METHOD(thread_tmp1_cast_mid2_v_fu_496_p2);
    sensitive << ( h_mid2_reg_613 );
    sensitive << ( tmp1_cast_mid2_v_v_fu_488_p3 );

    SC_METHOD(thread_tmp1_cast_mid2_v_v_fu_488_p3);
    sensitive << ( x_mid_fu_447_p2 );
    sensitive << ( y_1_fu_482_p2 );
    sensitive << ( y_mid_fu_441_p2 );

    SC_METHOD(thread_tmp4_mid2_fu_471_p2);
    sensitive << ( tmp_32_mid2_reg_587 );
    sensitive << ( tmp4_mid2_v_fu_467_p1 );

    SC_METHOD(thread_tmp4_mid2_v_fu_467_p1);
    sensitive << ( tmp4_mid2_v_v_fu_459_p3 );

    SC_METHOD(thread_tmp4_mid2_v_v_fu_459_p3);
    sensitive << ( ap_phi_mux_cin_phi_fu_187_p4 );
    sensitive << ( exitcond_flatten2_fu_429_p2 );
    sensitive << ( cin_s_fu_453_p2 );

    SC_METHOD(thread_tmp5_cast_fu_516_p1);
    sensitive << ( tmp1_cast_mid2_v_v_fu_488_p3 );

    SC_METHOD(thread_tmp_32_fu_277_p2);
    sensitive << ( p_shl_cast_fu_261_p1 );
    sensitive << ( p_shl1_cast_fu_273_p1 );

    SC_METHOD(thread_tmp_32_mid1_fu_331_p2);
    sensitive << ( p_shl_cast_mid1_fu_315_p1 );
    sensitive << ( p_shl1_cast_mid1_fu_327_p1 );

    SC_METHOD(thread_tmp_32_mid2_fu_337_p3);
    sensitive << ( exitcond_flatten_fu_295_p2 );
    sensitive << ( tmp_32_mid1_fu_331_p2 );
    sensitive << ( tmp_32_fu_277_p2 );

    SC_METHOD(thread_tmp_35_fu_549_p2);
    sensitive << ( c4_bias_load_mid2_v_reg_592 );
    sensitive << ( h_cast9_mid2_cast_reg_608 );

    SC_METHOD(thread_tmp_36_fu_553_p1);
    sensitive << ( tmp_35_fu_549_p2 );

    SC_METHOD(thread_tmp_38_fu_505_p2);
    sensitive << ( tmp4_mid2_v_v_fu_459_p3 );
    sensitive << ( tmp1_cast_mid2_fu_501_p1 );

    SC_METHOD(thread_tmp_39_fu_511_p1);
    sensitive << ( tmp_38_fu_505_p2 );

    SC_METHOD(thread_tmp_40_fu_520_p2);
    sensitive << ( tmp5_cast_fu_516_p1 );
    sensitive << ( tmp4_mid2_fu_471_p2 );

    SC_METHOD(thread_tmp_41_fu_530_p1);
    sensitive << ( tmp_55_cast_fu_526_p1 );

    SC_METHOD(thread_tmp_55_cast_fu_526_p1);
    sensitive << ( tmp_40_fu_520_p2 );

    SC_METHOD(thread_w_mid_fu_369_p2);
    sensitive << ( w_reg_158 );
    sensitive << ( not_exitcond_flatten_4_fu_358_p2 );

    SC_METHOD(thread_x_mid_fu_447_p2);
    sensitive << ( ap_phi_mux_x_phi_fu_232_p4 );
    sensitive << ( not_exitcond_flatten_fu_435_p2 );

    SC_METHOD(thread_y_1_fu_482_p2);
    sensitive << ( exitcond_flatten2_fu_429_p2 );
    sensitive << ( y_not_fu_476_p2 );

    SC_METHOD(thread_y_mid_fu_441_p2);
    sensitive << ( ap_phi_mux_y_phi_fu_209_p4 );
    sensitive << ( not_exitcond_flatten_fu_435_p2 );

    SC_METHOD(thread_y_not_fu_476_p2);
    sensitive << ( ap_phi_mux_y_phi_fu_209_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten7_fu_283_p2 );
    sensitive << ( exitcond_flatten8_fu_417_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_4_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, c4_weight_address0, "c4_weight_address0");
    sc_trace(mVcdFile, c4_weight_ce0, "c4_weight_ce0");
    sc_trace(mVcdFile, c4_weight_q0, "c4_weight_q0");
    sc_trace(mVcdFile, c4_bias_address0, "c4_bias_address0");
    sc_trace(mVcdFile, c4_bias_ce0, "c4_bias_ce0");
    sc_trace(mVcdFile, c4_bias_q0, "c4_bias_q0");
    sc_trace(mVcdFile, indvar_flatten8_reg_172, "indvar_flatten8_reg_172");
    sc_trace(mVcdFile, cin_reg_183, "cin_reg_183");
    sc_trace(mVcdFile, indvar_flatten_reg_194, "indvar_flatten_reg_194");
    sc_trace(mVcdFile, y_reg_205, "y_reg_205");
    sc_trace(mVcdFile, output_buffer_2_reg_216, "output_buffer_2_reg_216");
    sc_trace(mVcdFile, x_reg_228, "x_reg_228");
    sc_trace(mVcdFile, indvar_flatten_next7_fu_289_p2, "indvar_flatten_next7_fu_289_p2");
    sc_trace(mVcdFile, indvar_flatten_next7_reg_574, "indvar_flatten_next7_reg_574");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_flatten_fu_295_p2, "exitcond_flatten_fu_295_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_579, "exitcond_flatten_reg_579");
    sc_trace(mVcdFile, exitcond_flatten7_fu_283_p2, "exitcond_flatten7_fu_283_p2");
    sc_trace(mVcdFile, tmp_32_mid2_fu_337_p3, "tmp_32_mid2_fu_337_p3");
    sc_trace(mVcdFile, tmp_32_mid2_reg_587, "tmp_32_mid2_reg_587");
    sc_trace(mVcdFile, c4_bias_load_mid2_v_fu_345_p3, "c4_bias_load_mid2_v_fu_345_p3");
    sc_trace(mVcdFile, c4_bias_load_mid2_v_reg_592, "c4_bias_load_mid2_v_reg_592");
    sc_trace(mVcdFile, c4_bias_load_reg_603, "c4_bias_load_reg_603");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, h_cast9_mid2_cast_fu_405_p1, "h_cast9_mid2_cast_fu_405_p1");
    sc_trace(mVcdFile, h_cast9_mid2_cast_reg_608, "h_cast9_mid2_cast_reg_608");
    sc_trace(mVcdFile, h_mid2_fu_409_p3, "h_mid2_fu_409_p3");
    sc_trace(mVcdFile, h_mid2_reg_613, "h_mid2_reg_613");
    sc_trace(mVcdFile, exitcond_flatten8_fu_417_p2, "exitcond_flatten8_fu_417_p2");
    sc_trace(mVcdFile, exitcond_flatten8_reg_619, "exitcond_flatten8_reg_619");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next8_fu_423_p2, "indvar_flatten_next8_fu_423_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp4_mid2_v_v_fu_459_p3, "tmp4_mid2_v_v_fu_459_p3");
    sc_trace(mVcdFile, tmp4_mid2_v_v_reg_628, "tmp4_mid2_v_v_reg_628");
    sc_trace(mVcdFile, tmp1_cast_mid2_v_v_fu_488_p3, "tmp1_cast_mid2_v_v_fu_488_p3");
    sc_trace(mVcdFile, tmp1_cast_mid2_v_v_reg_633, "tmp1_cast_mid2_v_v_reg_633");
    sc_trace(mVcdFile, indvar_flatten_next_fu_541_p3, "indvar_flatten_next_fu_541_p3");
    sc_trace(mVcdFile, grp_fu_240_p2, "grp_fu_240_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, indvar_flatten_next6_fu_564_p3, "indvar_flatten_next6_fu_564_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, indvar_flatten6_reg_112, "indvar_flatten6_reg_112");
    sc_trace(mVcdFile, cout_reg_123, "cout_reg_123");
    sc_trace(mVcdFile, indvar_flatten7_reg_134, "indvar_flatten7_reg_134");
    sc_trace(mVcdFile, h_reg_146, "h_reg_146");
    sc_trace(mVcdFile, w_reg_158, "w_reg_158");
    sc_trace(mVcdFile, ap_phi_mux_cin_phi_fu_187_p4, "ap_phi_mux_cin_phi_fu_187_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_y_phi_fu_209_p4, "ap_phi_mux_y_phi_fu_209_p4");
    sc_trace(mVcdFile, ap_phi_mux_x_phi_fu_232_p4, "ap_phi_mux_x_phi_fu_232_p4");
    sc_trace(mVcdFile, c4_bias_load_mid2_fu_353_p1, "c4_bias_load_mid2_fu_353_p1");
    sc_trace(mVcdFile, tmp_39_fu_511_p1, "tmp_39_fu_511_p1");
    sc_trace(mVcdFile, tmp_41_fu_530_p1, "tmp_41_fu_530_p1");
    sc_trace(mVcdFile, tmp_36_fu_553_p1, "tmp_36_fu_553_p1");
    sc_trace(mVcdFile, grp_fu_240_p0, "grp_fu_240_p0");
    sc_trace(mVcdFile, tmp_42_fu_246_p2, "tmp_42_fu_246_p2");
    sc_trace(mVcdFile, p_shl_fu_253_p3, "p_shl_fu_253_p3");
    sc_trace(mVcdFile, p_shl1_fu_265_p3, "p_shl1_fu_265_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_261_p1, "p_shl_cast_fu_261_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_273_p1, "p_shl1_cast_fu_273_p1");
    sc_trace(mVcdFile, cout_s_fu_301_p2, "cout_s_fu_301_p2");
    sc_trace(mVcdFile, p_shl_mid1_fu_307_p3, "p_shl_mid1_fu_307_p3");
    sc_trace(mVcdFile, p_shl1_mid1_fu_319_p3, "p_shl1_mid1_fu_319_p3");
    sc_trace(mVcdFile, p_shl_cast_mid1_fu_315_p1, "p_shl_cast_mid1_fu_315_p1");
    sc_trace(mVcdFile, p_shl1_cast_mid1_fu_327_p1, "p_shl1_cast_mid1_fu_327_p1");
    sc_trace(mVcdFile, tmp_32_mid1_fu_331_p2, "tmp_32_mid1_fu_331_p2");
    sc_trace(mVcdFile, tmp_32_fu_277_p2, "tmp_32_fu_277_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_4_fu_358_p2, "not_exitcond_flatten_4_fu_358_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_5_fu_375_p2, "not_exitcond_flatten_5_fu_375_p2");
    sc_trace(mVcdFile, h_not_fu_386_p2, "h_not_fu_386_p2");
    sc_trace(mVcdFile, w_mid_fu_369_p2, "w_mid_fu_369_p2");
    sc_trace(mVcdFile, h_1_fu_392_p2, "h_1_fu_392_p2");
    sc_trace(mVcdFile, h_cast9_mid_fu_380_p2, "h_cast9_mid_fu_380_p2");
    sc_trace(mVcdFile, h_cast9_mid2_fu_397_p3, "h_cast9_mid2_fu_397_p3");
    sc_trace(mVcdFile, h_mid_fu_363_p2, "h_mid_fu_363_p2");
    sc_trace(mVcdFile, exitcond_flatten2_fu_429_p2, "exitcond_flatten2_fu_429_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_435_p2, "not_exitcond_flatten_fu_435_p2");
    sc_trace(mVcdFile, cin_s_fu_453_p2, "cin_s_fu_453_p2");
    sc_trace(mVcdFile, tmp4_mid2_v_fu_467_p1, "tmp4_mid2_v_fu_467_p1");
    sc_trace(mVcdFile, y_not_fu_476_p2, "y_not_fu_476_p2");
    sc_trace(mVcdFile, x_mid_fu_447_p2, "x_mid_fu_447_p2");
    sc_trace(mVcdFile, y_1_fu_482_p2, "y_1_fu_482_p2");
    sc_trace(mVcdFile, y_mid_fu_441_p2, "y_mid_fu_441_p2");
    sc_trace(mVcdFile, tmp1_cast_mid2_v_fu_496_p2, "tmp1_cast_mid2_v_fu_496_p2");
    sc_trace(mVcdFile, tmp1_cast_mid2_fu_501_p1, "tmp1_cast_mid2_fu_501_p1");
    sc_trace(mVcdFile, tmp_38_fu_505_p2, "tmp_38_fu_505_p2");
    sc_trace(mVcdFile, tmp5_cast_fu_516_p1, "tmp5_cast_fu_516_p1");
    sc_trace(mVcdFile, tmp4_mid2_fu_471_p2, "tmp4_mid2_fu_471_p2");
    sc_trace(mVcdFile, tmp_40_fu_520_p2, "tmp_40_fu_520_p2");
    sc_trace(mVcdFile, tmp_55_cast_fu_526_p1, "tmp_55_cast_fu_526_p1");
    sc_trace(mVcdFile, indvar_flatten_op_fu_535_p2, "indvar_flatten_op_fu_535_p2");
    sc_trace(mVcdFile, tmp_35_fu_549_p2, "tmp_35_fu_549_p2");
    sc_trace(mVcdFile, indvar_flatten23_op_fu_558_p2, "indvar_flatten23_op_fu_558_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

conv_4::~conv_4() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete c4_weight_U;
    delete c4_bias_U;
    delete top_net_fadd_32nsbkb_U29;
    delete top_net_fmul_32nscud_U30;
}

void conv_4::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()))) {
        cin_reg_183 = tmp4_mid2_v_v_reg_628.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        cin_reg_183 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        cout_reg_123 = c4_bias_load_mid2_v_reg_592.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        cout_reg_123 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        h_reg_146 = h_mid2_reg_613.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        h_reg_146 = ap_const_lv1_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten6_reg_112 = indvar_flatten_next7_reg_574.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten6_reg_112 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        indvar_flatten7_reg_134 = indvar_flatten_next6_fu_564_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten7_reg_134 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_fu_417_p2.read()))) {
        indvar_flatten8_reg_172 = indvar_flatten_next8_fu_423_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten8_reg_172 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_fu_417_p2.read()))) {
        indvar_flatten_reg_194 = indvar_flatten_next_fu_541_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten_reg_194 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()))) {
        output_buffer_2_reg_216 = grp_fu_240_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_buffer_2_reg_216 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        w_reg_158 = ap_const_lv1_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        w_reg_158 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()))) {
        x_reg_228 = ap_const_lv1_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_reg_228 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()))) {
        y_reg_205 = tmp1_cast_mid2_v_v_reg_633.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_reg_205 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten7_fu_283_p2.read(), ap_const_lv1_0))) {
        c4_bias_load_mid2_v_reg_592 = c4_bias_load_mid2_v_fu_345_p3.read();
        exitcond_flatten_reg_579 = exitcond_flatten_fu_295_p2.read();
        tmp_32_mid2_reg_587 = tmp_32_mid2_fu_337_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        c4_bias_load_reg_603 = c4_bias_q0.read();
        h_cast9_mid2_cast_reg_608 = h_cast9_mid2_cast_fu_405_p1.read();
        h_mid2_reg_613 = h_mid2_fu_409_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten8_reg_619 = exitcond_flatten8_fu_417_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvar_flatten_next7_reg_574 = indvar_flatten_next7_fu_289_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_fu_417_p2.read()))) {
        tmp1_cast_mid2_v_v_reg_633 = tmp1_cast_mid2_v_v_fu_488_p3.read();
        tmp4_mid2_v_v_reg_628 = tmp4_mid2_v_v_fu_459_p3.read();
    }
}

void conv_4::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void conv_4::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_4::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_4::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_4::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void conv_4::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_4::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_4::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_4::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_4::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_4::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_flatten8_fu_417_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void conv_4::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten7_fu_283_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_4::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv_4::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_4::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv_4::thread_ap_phi_mux_cin_phi_fu_187_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_cin_phi_fu_187_p4 = tmp4_mid2_v_v_reg_628.read();
    } else {
        ap_phi_mux_cin_phi_fu_187_p4 = cin_reg_183.read();
    }
}

void conv_4::thread_ap_phi_mux_x_phi_fu_232_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_x_phi_fu_232_p4 = ap_const_lv1_1;
    } else {
        ap_phi_mux_x_phi_fu_232_p4 = x_reg_228.read();
    }
}

void conv_4::thread_ap_phi_mux_y_phi_fu_209_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten8_reg_619.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_y_phi_fu_209_p4 = tmp1_cast_mid2_v_v_reg_633.read();
    } else {
        ap_phi_mux_y_phi_fu_209_p4 = y_reg_205.read();
    }
}

void conv_4::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten7_fu_283_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_4::thread_c4_bias_address0() {
    c4_bias_address0 =  (sc_lv<7>) (c4_bias_load_mid2_fu_353_p1.read());
}

void conv_4::thread_c4_bias_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c4_bias_ce0 = ap_const_logic_1;
    } else {
        c4_bias_ce0 = ap_const_logic_0;
    }
}

void conv_4::thread_c4_bias_load_mid2_fu_353_p1() {
    c4_bias_load_mid2_fu_353_p1 = esl_zext<64,7>(c4_bias_load_mid2_v_fu_345_p3.read());
}

void conv_4::thread_c4_bias_load_mid2_v_fu_345_p3() {
    c4_bias_load_mid2_v_fu_345_p3 = (!exitcond_flatten_fu_295_p2.read()[0].is_01())? sc_lv<7>(): ((exitcond_flatten_fu_295_p2.read()[0].to_bool())? cout_s_fu_301_p2.read(): cout_reg_123.read());
}

void conv_4::thread_c4_weight_address0() {
    c4_weight_address0 =  (sc_lv<14>) (tmp_41_fu_530_p1.read());
}

void conv_4::thread_c4_weight_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        c4_weight_ce0 = ap_const_logic_1;
    } else {
        c4_weight_ce0 = ap_const_logic_0;
    }
}

void conv_4::thread_cin_s_fu_453_p2() {
    cin_s_fu_453_p2 = (!ap_phi_mux_cin_phi_fu_187_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ap_phi_mux_cin_phi_fu_187_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void conv_4::thread_cout_s_fu_301_p2() {
    cout_s_fu_301_p2 = (!cout_reg_123.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(cout_reg_123.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void conv_4::thread_exitcond_flatten2_fu_429_p2() {
    exitcond_flatten2_fu_429_p2 = (!indvar_flatten_reg_194.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_194.read() == ap_const_lv2_1);
}

void conv_4::thread_exitcond_flatten7_fu_283_p2() {
    exitcond_flatten7_fu_283_p2 = (!indvar_flatten6_reg_112.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten6_reg_112.read() == ap_const_lv7_54);
}

void conv_4::thread_exitcond_flatten8_fu_417_p2() {
    exitcond_flatten8_fu_417_p2 = (!indvar_flatten8_reg_172.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten8_reg_172.read() == ap_const_lv7_78);
}

void conv_4::thread_exitcond_flatten_fu_295_p2() {
    exitcond_flatten_fu_295_p2 = (!indvar_flatten7_reg_134.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten7_reg_134.read() == ap_const_lv2_1);
}

void conv_4::thread_grp_fu_240_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_240_p0 = c4_bias_load_reg_603.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_240_p0 = tmp_42_fu_246_p2.read();
    } else {
        grp_fu_240_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void conv_4::thread_h_1_fu_392_p2() {
    h_1_fu_392_p2 = (exitcond_flatten_reg_579.read() | h_not_fu_386_p2.read());
}

void conv_4::thread_h_cast9_mid2_cast_fu_405_p1() {
    h_cast9_mid2_cast_fu_405_p1 = esl_zext<7,1>(h_cast9_mid2_fu_397_p3.read());
}

void conv_4::thread_h_cast9_mid2_fu_397_p3() {
    h_cast9_mid2_fu_397_p3 = (!w_mid_fu_369_p2.read()[0].is_01())? sc_lv<1>(): ((w_mid_fu_369_p2.read()[0].to_bool())? h_1_fu_392_p2.read(): h_cast9_mid_fu_380_p2.read());
}

void conv_4::thread_h_cast9_mid_fu_380_p2() {
    h_cast9_mid_fu_380_p2 = (h_reg_146.read() & not_exitcond_flatten_5_fu_375_p2.read());
}

void conv_4::thread_h_mid2_fu_409_p3() {
    h_mid2_fu_409_p3 = (!w_mid_fu_369_p2.read()[0].is_01())? sc_lv<1>(): ((w_mid_fu_369_p2.read()[0].to_bool())? h_1_fu_392_p2.read(): h_mid_fu_363_p2.read());
}

void conv_4::thread_h_mid_fu_363_p2() {
    h_mid_fu_363_p2 = (h_reg_146.read() & not_exitcond_flatten_4_fu_358_p2.read());
}

void conv_4::thread_h_not_fu_386_p2() {
    h_not_fu_386_p2 = (h_reg_146.read() ^ ap_const_lv1_1);
}

void conv_4::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<7>) (tmp_39_fu_511_p1.read());
}

void conv_4::thread_in_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void conv_4::thread_indvar_flatten23_op_fu_558_p2() {
    indvar_flatten23_op_fu_558_p2 = (!indvar_flatten7_reg_134.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(indvar_flatten7_reg_134.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_4::thread_indvar_flatten_next6_fu_564_p3() {
    indvar_flatten_next6_fu_564_p3 = (!exitcond_flatten_reg_579.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten_reg_579.read()[0].to_bool())? ap_const_lv2_1: indvar_flatten23_op_fu_558_p2.read());
}

void conv_4::thread_indvar_flatten_next7_fu_289_p2() {
    indvar_flatten_next7_fu_289_p2 = (!indvar_flatten6_reg_112.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten6_reg_112.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void conv_4::thread_indvar_flatten_next8_fu_423_p2() {
    indvar_flatten_next8_fu_423_p2 = (!indvar_flatten8_reg_172.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvar_flatten8_reg_172.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void conv_4::thread_indvar_flatten_next_fu_541_p3() {
    indvar_flatten_next_fu_541_p3 = (!exitcond_flatten2_fu_429_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond_flatten2_fu_429_p2.read()[0].to_bool())? ap_const_lv2_1: indvar_flatten_op_fu_535_p2.read());
}

void conv_4::thread_indvar_flatten_op_fu_535_p2() {
    indvar_flatten_op_fu_535_p2 = (!indvar_flatten_reg_194.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(indvar_flatten_reg_194.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_4::thread_not_exitcond_flatten_4_fu_358_p2() {
    not_exitcond_flatten_4_fu_358_p2 = (exitcond_flatten_reg_579.read() ^ ap_const_lv1_1);
}

void conv_4::thread_not_exitcond_flatten_5_fu_375_p2() {
    not_exitcond_flatten_5_fu_375_p2 = (exitcond_flatten_reg_579.read() ^ ap_const_lv1_1);
}

void conv_4::thread_not_exitcond_flatten_fu_435_p2() {
    not_exitcond_flatten_fu_435_p2 = (exitcond_flatten2_fu_429_p2.read() ^ ap_const_lv1_1);
}

void conv_4::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<7>) (tmp_36_fu_553_p1.read());
}

void conv_4::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_4::thread_output_r_d0() {
    output_r_d0 = grp_fu_240_p2.read();
}

void conv_4::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_4::thread_p_shl1_cast_fu_273_p1() {
    p_shl1_cast_fu_273_p1 = esl_zext<15,10>(p_shl1_fu_265_p3.read());
}

void conv_4::thread_p_shl1_cast_mid1_fu_327_p1() {
    p_shl1_cast_mid1_fu_327_p1 = esl_zext<15,10>(p_shl1_mid1_fu_319_p3.read());
}

void conv_4::thread_p_shl1_fu_265_p3() {
    p_shl1_fu_265_p3 = esl_concat<7,3>(cout_reg_123.read(), ap_const_lv3_0);
}

void conv_4::thread_p_shl1_mid1_fu_319_p3() {
    p_shl1_mid1_fu_319_p3 = esl_concat<7,3>(cout_s_fu_301_p2.read(), ap_const_lv3_0);
}

void conv_4::thread_p_shl_cast_fu_261_p1() {
    p_shl_cast_fu_261_p1 = esl_zext<15,14>(p_shl_fu_253_p3.read());
}

void conv_4::thread_p_shl_cast_mid1_fu_315_p1() {
    p_shl_cast_mid1_fu_315_p1 = esl_zext<15,14>(p_shl_mid1_fu_307_p3.read());
}

void conv_4::thread_p_shl_fu_253_p3() {
    p_shl_fu_253_p3 = esl_concat<7,7>(cout_reg_123.read(), ap_const_lv7_0);
}

void conv_4::thread_p_shl_mid1_fu_307_p3() {
    p_shl_mid1_fu_307_p3 = esl_concat<7,7>(cout_s_fu_301_p2.read(), ap_const_lv7_0);
}

void conv_4::thread_tmp1_cast_mid2_fu_501_p1() {
    tmp1_cast_mid2_fu_501_p1 = esl_zext<7,1>(tmp1_cast_mid2_v_fu_496_p2.read());
}

void conv_4::thread_tmp1_cast_mid2_v_fu_496_p2() {
    tmp1_cast_mid2_v_fu_496_p2 = (h_mid2_reg_613.read() ^ tmp1_cast_mid2_v_v_fu_488_p3.read());
}

void conv_4::thread_tmp1_cast_mid2_v_v_fu_488_p3() {
    tmp1_cast_mid2_v_v_fu_488_p3 = (!x_mid_fu_447_p2.read()[0].is_01())? sc_lv<1>(): ((x_mid_fu_447_p2.read()[0].to_bool())? y_1_fu_482_p2.read(): y_mid_fu_441_p2.read());
}

void conv_4::thread_tmp4_mid2_fu_471_p2() {
    tmp4_mid2_fu_471_p2 = (!tmp4_mid2_v_fu_467_p1.read().is_01() || !tmp_32_mid2_reg_587.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp4_mid2_v_fu_467_p1.read()) + sc_biguint<15>(tmp_32_mid2_reg_587.read()));
}

void conv_4::thread_tmp4_mid2_v_fu_467_p1() {
    tmp4_mid2_v_fu_467_p1 = esl_zext<15,7>(tmp4_mid2_v_v_fu_459_p3.read());
}

void conv_4::thread_tmp4_mid2_v_v_fu_459_p3() {
    tmp4_mid2_v_v_fu_459_p3 = (!exitcond_flatten2_fu_429_p2.read()[0].is_01())? sc_lv<7>(): ((exitcond_flatten2_fu_429_p2.read()[0].to_bool())? cin_s_fu_453_p2.read(): ap_phi_mux_cin_phi_fu_187_p4.read());
}

void conv_4::thread_tmp5_cast_fu_516_p1() {
    tmp5_cast_fu_516_p1 = esl_zext<15,1>(tmp1_cast_mid2_v_v_fu_488_p3.read());
}

void conv_4::thread_tmp_32_fu_277_p2() {
    tmp_32_fu_277_p2 = (!p_shl_cast_fu_261_p1.read().is_01() || !p_shl1_cast_fu_273_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl_cast_fu_261_p1.read()) - sc_biguint<15>(p_shl1_cast_fu_273_p1.read()));
}

void conv_4::thread_tmp_32_mid1_fu_331_p2() {
    tmp_32_mid1_fu_331_p2 = (!p_shl_cast_mid1_fu_315_p1.read().is_01() || !p_shl1_cast_mid1_fu_327_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_shl_cast_mid1_fu_315_p1.read()) - sc_biguint<15>(p_shl1_cast_mid1_fu_327_p1.read()));
}

void conv_4::thread_tmp_32_mid2_fu_337_p3() {
    tmp_32_mid2_fu_337_p3 = (!exitcond_flatten_fu_295_p2.read()[0].is_01())? sc_lv<15>(): ((exitcond_flatten_fu_295_p2.read()[0].to_bool())? tmp_32_mid1_fu_331_p2.read(): tmp_32_fu_277_p2.read());
}

void conv_4::thread_tmp_35_fu_549_p2() {
    tmp_35_fu_549_p2 = (!c4_bias_load_mid2_v_reg_592.read().is_01() || !h_cast9_mid2_cast_reg_608.read().is_01())? sc_lv<7>(): (sc_biguint<7>(c4_bias_load_mid2_v_reg_592.read()) + sc_biguint<7>(h_cast9_mid2_cast_reg_608.read()));
}

void conv_4::thread_tmp_36_fu_553_p1() {
    tmp_36_fu_553_p1 = esl_zext<64,7>(tmp_35_fu_549_p2.read());
}

void conv_4::thread_tmp_38_fu_505_p2() {
    tmp_38_fu_505_p2 = (!tmp4_mid2_v_v_fu_459_p3.read().is_01() || !tmp1_cast_mid2_fu_501_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(tmp4_mid2_v_v_fu_459_p3.read()) + sc_biguint<7>(tmp1_cast_mid2_fu_501_p1.read()));
}

void conv_4::thread_tmp_39_fu_511_p1() {
    tmp_39_fu_511_p1 = esl_zext<64,7>(tmp_38_fu_505_p2.read());
}

void conv_4::thread_tmp_40_fu_520_p2() {
    tmp_40_fu_520_p2 = (!tmp5_cast_fu_516_p1.read().is_01() || !tmp4_mid2_fu_471_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp5_cast_fu_516_p1.read()) + sc_biguint<15>(tmp4_mid2_fu_471_p2.read()));
}

void conv_4::thread_tmp_41_fu_530_p1() {
    tmp_41_fu_530_p1 = esl_zext<64,32>(tmp_55_cast_fu_526_p1.read());
}

void conv_4::thread_tmp_55_cast_fu_526_p1() {
    tmp_55_cast_fu_526_p1 = esl_sext<32,15>(tmp_40_fu_520_p2.read());
}

void conv_4::thread_w_mid_fu_369_p2() {
    w_mid_fu_369_p2 = (w_reg_158.read() & not_exitcond_flatten_4_fu_358_p2.read());
}

void conv_4::thread_x_mid_fu_447_p2() {
    x_mid_fu_447_p2 = (ap_phi_mux_x_phi_fu_232_p4.read() & not_exitcond_flatten_fu_435_p2.read());
}

void conv_4::thread_y_1_fu_482_p2() {
    y_1_fu_482_p2 = (exitcond_flatten2_fu_429_p2.read() | y_not_fu_476_p2.read());
}

void conv_4::thread_y_mid_fu_441_p2() {
    y_mid_fu_441_p2 = (ap_phi_mux_y_phi_fu_209_p4.read() & not_exitcond_flatten_fu_435_p2.read());
}

void conv_4::thread_y_not_fu_476_p2() {
    y_not_fu_476_p2 = (ap_phi_mux_y_phi_fu_209_p4.read() ^ ap_const_lv1_1);
}

void conv_4::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten7_fu_283_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten8_fu_417_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten8_fu_417_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

}

