// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool_2D.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool_2D::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool_2D::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> max_pool_2D::ap_ST_fsm_state1 = "1";
const sc_lv<6> max_pool_2D::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> max_pool_2D::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<6> max_pool_2D::ap_ST_fsm_pp0_stage2 = "1000";
const sc_lv<6> max_pool_2D::ap_ST_fsm_pp0_stage3 = "10000";
const sc_lv<6> max_pool_2D::ap_ST_fsm_state7 = "100000";
const bool max_pool_2D::ap_const_boolean_1 = true;
const sc_lv<32> max_pool_2D::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool_2D::ap_const_lv32_1 = "1";
const bool max_pool_2D::ap_const_boolean_0 = false;
const sc_lv<1> max_pool_2D::ap_const_lv1_0 = "0";
const sc_lv<32> max_pool_2D::ap_const_lv32_2 = "10";
const sc_lv<32> max_pool_2D::ap_const_lv32_3 = "11";
const sc_lv<32> max_pool_2D::ap_const_lv32_4 = "100";
const sc_lv<1> max_pool_2D::ap_const_lv1_1 = "1";
const sc_lv<9> max_pool_2D::ap_const_lv9_0 = "000000000";
const sc_lv<3> max_pool_2D::ap_const_lv3_0 = "000";
const sc_lv<8> max_pool_2D::ap_const_lv8_0 = "00000000";
const sc_lv<5> max_pool_2D::ap_const_lv5_0 = "00000";
const sc_lv<4> max_pool_2D::ap_const_lv4_1 = "1";
const sc_lv<9> max_pool_2D::ap_const_lv9_190 = "110010000";
const sc_lv<9> max_pool_2D::ap_const_lv9_1 = "1";
const sc_lv<8> max_pool_2D::ap_const_lv8_50 = "1010000";
const sc_lv<3> max_pool_2D::ap_const_lv3_1 = "1";
const sc_lv<4> max_pool_2D::ap_const_lv4_0 = "0000";
const sc_lv<5> max_pool_2D::ap_const_lv5_10 = "10000";
const sc_lv<5> max_pool_2D::ap_const_lv5_1 = "1";
const sc_lv<8> max_pool_2D::ap_const_lv8_1 = "1";
const sc_lv<2> max_pool_2D::ap_const_lv2_0 = "00";
const sc_lv<5> max_pool_2D::ap_const_lv5_2 = "10";
const sc_lv<32> max_pool_2D::ap_const_lv32_5 = "101";

max_pool_2D::max_pool_2D(sc_module_name name) : sc_module(name), mVcdFile(0) {
    top_net_fcmp_32nsdEe_U20 = new top_net_fcmp_32nsdEe<1,1,32,32,1>("top_net_fcmp_32nsdEe_U20");
    top_net_fcmp_32nsdEe_U20->din0(grp_fu_200_p0);
    top_net_fcmp_32nsdEe_U20->din1(grp_fu_200_p1);
    top_net_fcmp_32nsdEe_U20->opcode(ap_var_for_const0);
    top_net_fcmp_32nsdEe_U20->dout(grp_fu_200_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_00001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_00001);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_00001);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten2_fu_222_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_160_p4);
    sensitive << ( i_reg_156 );
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_cast9_mid2_v_reg_642 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten2_phi_fu_149_p4);
    sensitive << ( indvar_flatten2_reg_145 );
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_next2_reg_637 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_171_p4);
    sensitive << ( indvar_flatten_reg_167 );
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_next_reg_697 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_phi_fu_182_p4);
    sensitive << ( j_reg_178 );
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_cast8_mid2_reg_654 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_n_phi_fu_193_p4);
    sensitive << ( n_reg_189 );
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( n_1_reg_743 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_exitcond_flatten2_fu_222_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten2_phi_fu_149_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_234_p2);
    sensitive << ( exitcond_flatten2_fu_222_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_171_p4 );

    SC_METHOD(thread_exitcond_fu_306_p2);
    sensitive << ( exitcond_flatten2_fu_222_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_n_phi_fu_193_p4 );

    SC_METHOD(thread_exitcond_mid_fu_312_p2);
    sensitive << ( exitcond_fu_306_p2 );
    sensitive << ( not_exitcond_flatten_fu_300_p2 );

    SC_METHOD(thread_grp_fu_200_p0);
    sensitive << ( in_r_q0 );
    sensitive << ( in_r_q1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_grp_fu_200_p1);
    sensitive << ( in_r_q0 );
    sensitive << ( in_r_q1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_i_cast9_mid2_fu_558_p1);
    sensitive << ( i_cast9_mid2_v_reg_642 );

    SC_METHOD(thread_i_cast9_mid2_v_fu_254_p3);
    sensitive << ( ap_phi_mux_i_phi_fu_160_p4 );
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( i_s_fu_248_p2 );

    SC_METHOD(thread_i_s_fu_248_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_160_p4 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_13_fu_454_p1 );
    sensitive << ( tmp_19_fu_528_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_21_fu_543_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( max_val_5_cast_fu_570_p1 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_in_r_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_15_fu_465_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( max_val_1_cast_fu_538_p1 );
    sensitive << ( ap_block_pp0_stage2 );
    sensitive << ( max_val_4_cast_fu_553_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );

    SC_METHOD(thread_in_r_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_block_pp0_stage2_11001 );

    SC_METHOD(thread_indvar_flatten_next2_fu_228_p2);
    sensitive << ( ap_phi_mux_indvar_flatten2_phi_fu_149_p4 );

    SC_METHOD(thread_indvar_flatten_next_fu_520_p3);
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( indvar_flatten_op_fu_514_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_514_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_171_p4 );

    SC_METHOD(thread_j_1_fu_318_p2);
    sensitive << ( j_mid_fu_240_p3 );

    SC_METHOD(thread_j_cast8_mid2_cast_fu_603_p1);
    sensitive << ( j_cast8_mid2_reg_654 );

    SC_METHOD(thread_j_cast8_mid2_fu_338_p3);
    sensitive << ( j_mid_fu_240_p3 );
    sensitive << ( exitcond_mid_fu_312_p2 );
    sensitive << ( j_1_fu_318_p2 );

    SC_METHOD(thread_j_mid_fu_240_p3);
    sensitive << ( ap_phi_mux_j_phi_fu_182_p4 );
    sensitive << ( exitcond_flatten_fu_234_p2 );

    SC_METHOD(thread_max_val_1_cast_fu_538_p1);
    sensitive << ( max_val_1_fu_532_p3 );

    SC_METHOD(thread_max_val_1_fu_532_p3);
    sensitive << ( tmp_12_reg_665 );
    sensitive << ( tmp_14_reg_675 );
    sensitive << ( grp_fu_200_p2 );

    SC_METHOD(thread_max_val_4_cast_fu_553_p1);
    sensitive << ( max_val_4_fu_547_p3 );

    SC_METHOD(thread_max_val_4_fu_547_p3);
    sensitive << ( tmp_18_reg_685 );
    sensitive << ( max_val_1_reg_707 );
    sensitive << ( grp_fu_200_p2 );

    SC_METHOD(thread_max_val_5_cast_fu_570_p1);
    sensitive << ( max_val_5_fu_564_p3 );

    SC_METHOD(thread_max_val_5_fu_564_p3);
    sensitive << ( tmp_20_reg_691 );
    sensitive << ( max_val_4_reg_722 );
    sensitive << ( grp_fu_200_p2 );

    SC_METHOD(thread_n_1_fu_598_p2);
    sensitive << ( n_mid2_reg_648 );

    SC_METHOD(thread_n_cast7_fu_561_p1);
    sensitive << ( n_mid2_reg_648 );

    SC_METHOD(thread_n_mid2_fu_330_p3);
    sensitive << ( ap_phi_mux_n_phi_fu_193_p4 );
    sensitive << ( tmp_fu_324_p2 );

    SC_METHOD(thread_not_exitcond_flatten_fu_300_p2);
    sensitive << ( exitcond_flatten_fu_234_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_24_fu_628_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( in_r_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( exitcond_flatten2_reg_633 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_p_shl1_cast_fu_492_p1);
    sensitive << ( p_shl1_fu_484_p3 );

    SC_METHOD(thread_p_shl1_fu_484_p3);
    sensitive << ( tmp_16_fu_470_p2 );

    SC_METHOD(thread_p_shl2_fu_422_p3);
    sensitive << ( tmp_10_fu_416_p2 );

    SC_METHOD(thread_p_shl3_cast_fu_438_p1);
    sensitive << ( p_shl3_fu_430_p3 );

    SC_METHOD(thread_p_shl3_fu_430_p3);
    sensitive << ( tmp_10_fu_416_p2 );

    SC_METHOD(thread_p_shl4_cast_fu_396_p1);
    sensitive << ( p_shl4_fu_388_p3 );

    SC_METHOD(thread_p_shl4_fu_388_p3);
    sensitive << ( tmp_1_fu_384_p1 );

    SC_METHOD(thread_p_shl5_cast_fu_406_p1);
    sensitive << ( tmp_2_fu_400_p2 );

    SC_METHOD(thread_p_shl6_fu_609_p3);
    sensitive << ( tmp5_reg_737 );

    SC_METHOD(thread_p_shl7_cast_fu_582_p1);
    sensitive << ( p_shl7_fu_575_p3 );

    SC_METHOD(thread_p_shl7_fu_575_p3);
    sensitive << ( tmp_1_reg_660 );

    SC_METHOD(thread_p_shl_fu_476_p3);
    sensitive << ( tmp_16_fu_470_p2 );

    SC_METHOD(thread_tmp3_fu_586_p2);
    sensitive << ( i_cast9_mid2_fu_558_p1 );
    sensitive << ( p_shl7_cast_fu_582_p1 );

    SC_METHOD(thread_tmp4_fu_616_p2);
    sensitive << ( j_cast8_mid2_cast_fu_603_p1 );
    sensitive << ( p_shl6_fu_609_p3 );

    SC_METHOD(thread_tmp5_cast_fu_606_p1);
    sensitive << ( tmp5_reg_737 );

    SC_METHOD(thread_tmp5_fu_592_p2);
    sensitive << ( n_cast7_fu_561_p1 );
    sensitive << ( tmp3_fu_586_p2 );

    SC_METHOD(thread_tmp_10_fu_416_p2);
    sensitive << ( tmp_4_cast_mid2_fu_270_p1 );
    sensitive << ( tmp_9_fu_410_p2 );

    SC_METHOD(thread_tmp_11_fu_442_p2);
    sensitive << ( p_shl2_fu_422_p3 );
    sensitive << ( p_shl3_cast_fu_438_p1 );

    SC_METHOD(thread_tmp_12_fu_448_p2);
    sensitive << ( tmp_7_cast_mid2_cast_fu_362_p1 );
    sensitive << ( tmp_11_fu_442_p2 );

    SC_METHOD(thread_tmp_13_fu_454_p1);
    sensitive << ( tmp_12_fu_448_p2 );

    SC_METHOD(thread_tmp_14_fu_459_p2);
    sensitive << ( tmp_11_fu_442_p2 );
    sensitive << ( tmp_8_cast_mid2_cast_fu_380_p1 );

    SC_METHOD(thread_tmp_15_fu_465_p1);
    sensitive << ( tmp_14_fu_459_p2 );

    SC_METHOD(thread_tmp_16_fu_470_p2);
    sensitive << ( tmp_9_fu_410_p2 );
    sensitive << ( tmp_5_cast_mid2_fu_280_p1 );

    SC_METHOD(thread_tmp_17_fu_496_p2);
    sensitive << ( p_shl_fu_476_p3 );
    sensitive << ( p_shl1_cast_fu_492_p1 );

    SC_METHOD(thread_tmp_18_fu_502_p2);
    sensitive << ( tmp_7_cast_mid2_cast_fu_362_p1 );
    sensitive << ( tmp_17_fu_496_p2 );

    SC_METHOD(thread_tmp_19_fu_528_p1);
    sensitive << ( tmp_18_reg_685 );

    SC_METHOD(thread_tmp_1_fu_384_p1);
    sensitive << ( n_mid2_fu_330_p3 );

    SC_METHOD(thread_tmp_20_fu_508_p2);
    sensitive << ( tmp_8_cast_mid2_cast_fu_380_p1 );
    sensitive << ( tmp_17_fu_496_p2 );

    SC_METHOD(thread_tmp_21_fu_543_p1);
    sensitive << ( tmp_20_reg_691 );

    SC_METHOD(thread_tmp_23_fu_622_p2);
    sensitive << ( tmp5_cast_fu_606_p1 );
    sensitive << ( tmp4_fu_616_p2 );

    SC_METHOD(thread_tmp_24_fu_628_p1);
    sensitive << ( tmp_23_fu_622_p2 );

    SC_METHOD(thread_tmp_2_fu_400_p2);
    sensitive << ( n_mid2_fu_330_p3 );

    SC_METHOD(thread_tmp_4_cast_mid2_fu_270_p1);
    sensitive << ( tmp_4_cast_mid2_v_fu_262_p3 );

    SC_METHOD(thread_tmp_4_cast_mid2_v_fu_262_p3);
    sensitive << ( i_cast9_mid2_v_fu_254_p3 );

    SC_METHOD(thread_tmp_5_cast_mid2_fu_280_p1);
    sensitive << ( tmp_5_cast_mid2_v_fu_274_p2 );

    SC_METHOD(thread_tmp_5_cast_mid2_v_fu_274_p2);
    sensitive << ( tmp_4_cast_mid2_v_fu_262_p3 );

    SC_METHOD(thread_tmp_7_cast_mid2_cast_fu_362_p1);
    sensitive << ( tmp_7_cast_mid2_fu_354_p3 );

    SC_METHOD(thread_tmp_7_cast_mid2_fu_354_p3);
    sensitive << ( exitcond_mid_fu_312_p2 );
    sensitive << ( tmp_7_mid1_fu_346_p3 );
    sensitive << ( tmp_7_cast_mid_fu_284_p3 );

    SC_METHOD(thread_tmp_7_cast_mid_fu_284_p3);
    sensitive << ( tmp_7_fu_208_p3 );
    sensitive << ( exitcond_flatten_fu_234_p2 );

    SC_METHOD(thread_tmp_7_fu_208_p3);
    sensitive << ( ap_phi_mux_j_phi_fu_182_p4 );

    SC_METHOD(thread_tmp_7_mid1_fu_346_p3);
    sensitive << ( j_1_fu_318_p2 );

    SC_METHOD(thread_tmp_8_cast_mid2_cast_fu_380_p1);
    sensitive << ( tmp_8_cast_mid2_fu_372_p3 );

    SC_METHOD(thread_tmp_8_cast_mid2_fu_372_p3);
    sensitive << ( exitcond_mid_fu_312_p2 );
    sensitive << ( tmp_8_mid1_fu_366_p2 );
    sensitive << ( tmp_8_cast_mid_fu_292_p3 );

    SC_METHOD(thread_tmp_8_cast_mid_fu_292_p3);
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( tmp_8_fu_216_p2 );

    SC_METHOD(thread_tmp_8_fu_216_p2);
    sensitive << ( tmp_7_fu_208_p3 );

    SC_METHOD(thread_tmp_8_mid1_fu_366_p2);
    sensitive << ( tmp_7_mid1_fu_346_p3 );

    SC_METHOD(thread_tmp_9_fu_410_p2);
    sensitive << ( p_shl4_cast_fu_396_p1 );
    sensitive << ( p_shl5_cast_fu_406_p1 );

    SC_METHOD(thread_tmp_fu_324_p2);
    sensitive << ( exitcond_flatten_fu_234_p2 );
    sensitive << ( exitcond_mid_fu_312_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond_flatten2_fu_222_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_2D_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, in_r_address1, "(port)in_r_address1");
    sc_trace(mVcdFile, in_r_ce1, "(port)in_r_ce1");
    sc_trace(mVcdFile, in_r_q1, "(port)in_r_q1");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten2_reg_145, "indvar_flatten2_reg_145");
    sc_trace(mVcdFile, i_reg_156, "i_reg_156");
    sc_trace(mVcdFile, indvar_flatten_reg_167, "indvar_flatten_reg_167");
    sc_trace(mVcdFile, j_reg_178, "j_reg_178");
    sc_trace(mVcdFile, n_reg_189, "n_reg_189");
    sc_trace(mVcdFile, exitcond_flatten2_fu_222_p2, "exitcond_flatten2_fu_222_p2");
    sc_trace(mVcdFile, exitcond_flatten2_reg_633, "exitcond_flatten2_reg_633");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter1, "ap_block_state6_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, indvar_flatten_next2_fu_228_p2, "indvar_flatten_next2_fu_228_p2");
    sc_trace(mVcdFile, indvar_flatten_next2_reg_637, "indvar_flatten_next2_reg_637");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, i_cast9_mid2_v_fu_254_p3, "i_cast9_mid2_v_fu_254_p3");
    sc_trace(mVcdFile, i_cast9_mid2_v_reg_642, "i_cast9_mid2_v_reg_642");
    sc_trace(mVcdFile, n_mid2_fu_330_p3, "n_mid2_fu_330_p3");
    sc_trace(mVcdFile, n_mid2_reg_648, "n_mid2_reg_648");
    sc_trace(mVcdFile, j_cast8_mid2_fu_338_p3, "j_cast8_mid2_fu_338_p3");
    sc_trace(mVcdFile, j_cast8_mid2_reg_654, "j_cast8_mid2_reg_654");
    sc_trace(mVcdFile, tmp_1_fu_384_p1, "tmp_1_fu_384_p1");
    sc_trace(mVcdFile, tmp_1_reg_660, "tmp_1_reg_660");
    sc_trace(mVcdFile, tmp_12_fu_448_p2, "tmp_12_fu_448_p2");
    sc_trace(mVcdFile, tmp_12_reg_665, "tmp_12_reg_665");
    sc_trace(mVcdFile, tmp_14_fu_459_p2, "tmp_14_fu_459_p2");
    sc_trace(mVcdFile, tmp_14_reg_675, "tmp_14_reg_675");
    sc_trace(mVcdFile, tmp_18_fu_502_p2, "tmp_18_fu_502_p2");
    sc_trace(mVcdFile, tmp_18_reg_685, "tmp_18_reg_685");
    sc_trace(mVcdFile, tmp_20_fu_508_p2, "tmp_20_fu_508_p2");
    sc_trace(mVcdFile, tmp_20_reg_691, "tmp_20_reg_691");
    sc_trace(mVcdFile, indvar_flatten_next_fu_520_p3, "indvar_flatten_next_fu_520_p3");
    sc_trace(mVcdFile, indvar_flatten_next_reg_697, "indvar_flatten_next_reg_697");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, max_val_1_fu_532_p3, "max_val_1_fu_532_p3");
    sc_trace(mVcdFile, max_val_1_reg_707, "max_val_1_reg_707");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage2_iter0, "ap_block_state4_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, max_val_4_fu_547_p3, "max_val_4_fu_547_p3");
    sc_trace(mVcdFile, max_val_4_reg_722, "max_val_4_reg_722");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage3_iter0, "ap_block_state5_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, tmp5_fu_592_p2, "tmp5_fu_592_p2");
    sc_trace(mVcdFile, tmp5_reg_737, "tmp5_reg_737");
    sc_trace(mVcdFile, n_1_fu_598_p2, "n_1_fu_598_p2");
    sc_trace(mVcdFile, n_1_reg_743, "n_1_reg_743");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten2_phi_fu_149_p4, "ap_phi_mux_indvar_flatten2_phi_fu_149_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_160_p4, "ap_phi_mux_i_phi_fu_160_p4");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_171_p4, "ap_phi_mux_indvar_flatten_phi_fu_171_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_phi_fu_182_p4, "ap_phi_mux_j_phi_fu_182_p4");
    sc_trace(mVcdFile, ap_phi_mux_n_phi_fu_193_p4, "ap_phi_mux_n_phi_fu_193_p4");
    sc_trace(mVcdFile, tmp_13_fu_454_p1, "tmp_13_fu_454_p1");
    sc_trace(mVcdFile, tmp_15_fu_465_p1, "tmp_15_fu_465_p1");
    sc_trace(mVcdFile, tmp_19_fu_528_p1, "tmp_19_fu_528_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, max_val_1_cast_fu_538_p1, "max_val_1_cast_fu_538_p1");
    sc_trace(mVcdFile, tmp_21_fu_543_p1, "tmp_21_fu_543_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, max_val_4_cast_fu_553_p1, "max_val_4_cast_fu_553_p1");
    sc_trace(mVcdFile, max_val_5_cast_fu_570_p1, "max_val_5_cast_fu_570_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, tmp_24_fu_628_p1, "tmp_24_fu_628_p1");
    sc_trace(mVcdFile, grp_fu_200_p0, "grp_fu_200_p0");
    sc_trace(mVcdFile, grp_fu_200_p1, "grp_fu_200_p1");
    sc_trace(mVcdFile, tmp_7_fu_208_p3, "tmp_7_fu_208_p3");
    sc_trace(mVcdFile, exitcond_flatten_fu_234_p2, "exitcond_flatten_fu_234_p2");
    sc_trace(mVcdFile, i_s_fu_248_p2, "i_s_fu_248_p2");
    sc_trace(mVcdFile, tmp_4_cast_mid2_v_fu_262_p3, "tmp_4_cast_mid2_v_fu_262_p3");
    sc_trace(mVcdFile, tmp_5_cast_mid2_v_fu_274_p2, "tmp_5_cast_mid2_v_fu_274_p2");
    sc_trace(mVcdFile, tmp_8_fu_216_p2, "tmp_8_fu_216_p2");
    sc_trace(mVcdFile, exitcond_fu_306_p2, "exitcond_fu_306_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_300_p2, "not_exitcond_flatten_fu_300_p2");
    sc_trace(mVcdFile, j_mid_fu_240_p3, "j_mid_fu_240_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_312_p2, "exitcond_mid_fu_312_p2");
    sc_trace(mVcdFile, tmp_fu_324_p2, "tmp_fu_324_p2");
    sc_trace(mVcdFile, j_1_fu_318_p2, "j_1_fu_318_p2");
    sc_trace(mVcdFile, tmp_7_mid1_fu_346_p3, "tmp_7_mid1_fu_346_p3");
    sc_trace(mVcdFile, tmp_7_cast_mid_fu_284_p3, "tmp_7_cast_mid_fu_284_p3");
    sc_trace(mVcdFile, tmp_7_cast_mid2_fu_354_p3, "tmp_7_cast_mid2_fu_354_p3");
    sc_trace(mVcdFile, tmp_8_mid1_fu_366_p2, "tmp_8_mid1_fu_366_p2");
    sc_trace(mVcdFile, tmp_8_cast_mid_fu_292_p3, "tmp_8_cast_mid_fu_292_p3");
    sc_trace(mVcdFile, tmp_8_cast_mid2_fu_372_p3, "tmp_8_cast_mid2_fu_372_p3");
    sc_trace(mVcdFile, p_shl4_fu_388_p3, "p_shl4_fu_388_p3");
    sc_trace(mVcdFile, tmp_2_fu_400_p2, "tmp_2_fu_400_p2");
    sc_trace(mVcdFile, p_shl4_cast_fu_396_p1, "p_shl4_cast_fu_396_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_406_p1, "p_shl5_cast_fu_406_p1");
    sc_trace(mVcdFile, tmp_4_cast_mid2_fu_270_p1, "tmp_4_cast_mid2_fu_270_p1");
    sc_trace(mVcdFile, tmp_9_fu_410_p2, "tmp_9_fu_410_p2");
    sc_trace(mVcdFile, tmp_10_fu_416_p2, "tmp_10_fu_416_p2");
    sc_trace(mVcdFile, p_shl3_fu_430_p3, "p_shl3_fu_430_p3");
    sc_trace(mVcdFile, p_shl2_fu_422_p3, "p_shl2_fu_422_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_438_p1, "p_shl3_cast_fu_438_p1");
    sc_trace(mVcdFile, tmp_7_cast_mid2_cast_fu_362_p1, "tmp_7_cast_mid2_cast_fu_362_p1");
    sc_trace(mVcdFile, tmp_11_fu_442_p2, "tmp_11_fu_442_p2");
    sc_trace(mVcdFile, tmp_8_cast_mid2_cast_fu_380_p1, "tmp_8_cast_mid2_cast_fu_380_p1");
    sc_trace(mVcdFile, tmp_5_cast_mid2_fu_280_p1, "tmp_5_cast_mid2_fu_280_p1");
    sc_trace(mVcdFile, tmp_16_fu_470_p2, "tmp_16_fu_470_p2");
    sc_trace(mVcdFile, p_shl1_fu_484_p3, "p_shl1_fu_484_p3");
    sc_trace(mVcdFile, p_shl_fu_476_p3, "p_shl_fu_476_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_492_p1, "p_shl1_cast_fu_492_p1");
    sc_trace(mVcdFile, tmp_17_fu_496_p2, "tmp_17_fu_496_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_514_p2, "indvar_flatten_op_fu_514_p2");
    sc_trace(mVcdFile, grp_fu_200_p2, "grp_fu_200_p2");
    sc_trace(mVcdFile, max_val_5_fu_564_p3, "max_val_5_fu_564_p3");
    sc_trace(mVcdFile, p_shl7_fu_575_p3, "p_shl7_fu_575_p3");
    sc_trace(mVcdFile, i_cast9_mid2_fu_558_p1, "i_cast9_mid2_fu_558_p1");
    sc_trace(mVcdFile, p_shl7_cast_fu_582_p1, "p_shl7_cast_fu_582_p1");
    sc_trace(mVcdFile, n_cast7_fu_561_p1, "n_cast7_fu_561_p1");
    sc_trace(mVcdFile, tmp3_fu_586_p2, "tmp3_fu_586_p2");
    sc_trace(mVcdFile, j_cast8_mid2_cast_fu_603_p1, "j_cast8_mid2_cast_fu_603_p1");
    sc_trace(mVcdFile, p_shl6_fu_609_p3, "p_shl6_fu_609_p3");
    sc_trace(mVcdFile, tmp5_cast_fu_606_p1, "tmp5_cast_fu_606_p1");
    sc_trace(mVcdFile, tmp4_fu_616_p2, "tmp4_fu_616_p2");
    sc_trace(mVcdFile, tmp_23_fu_622_p2, "tmp_23_fu_622_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage1_00001, "ap_block_pp0_stage1_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage2_00001, "ap_block_pp0_stage2_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage3_00001, "ap_block_pp0_stage3_00001");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

max_pool_2D::~max_pool_2D() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete top_net_fcmp_32nsdEe_U20;
}

void max_pool_2D::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_2;
}

void max_pool_2D::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_reg_156 = i_cast9_mid2_v_reg_642.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_156 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten2_reg_145 = indvar_flatten_next2_reg_637.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten2_reg_145 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_167 = indvar_flatten_next_reg_697.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_167 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_reg_178 = j_cast8_mid2_reg_654.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_reg_178 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        n_reg_189 = n_1_reg_743.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n_reg_189 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten2_reg_633 = exitcond_flatten2_fu_222_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten2_fu_222_p2.read(), ap_const_lv1_0))) {
        i_cast9_mid2_v_reg_642 = i_cast9_mid2_v_fu_254_p3.read();
        indvar_flatten_next_reg_697 = indvar_flatten_next_fu_520_p3.read();
        j_cast8_mid2_reg_654 = j_cast8_mid2_fu_338_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        indvar_flatten_next2_reg_637 = indvar_flatten_next2_fu_228_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0))) {
        max_val_1_reg_707 = max_val_1_fu_532_p3.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0))) {
        max_val_4_reg_722 = max_val_4_fu_547_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        n_1_reg_743 = n_1_fu_598_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten2_fu_222_p2.read(), ap_const_lv1_0))) {
        n_mid2_reg_648 = n_mid2_fu_330_p3.read();
        tmp_12_reg_665 = tmp_12_fu_448_p2.read();
        tmp_14_reg_675 = tmp_14_fu_459_p2.read();
        tmp_18_reg_685 = tmp_18_fu_502_p2.read();
        tmp_1_reg_660 = tmp_1_fu_384_p1.read();
        tmp_20_reg_691 = tmp_20_fu_508_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0))) {
        tmp5_reg_737 = tmp5_fu_592_p2.read();
    }
}

void max_pool_2D::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void max_pool_2D::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void max_pool_2D::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[3];
}

void max_pool_2D::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[4];
}

void max_pool_2D::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool_2D::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void max_pool_2D::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage1_00001() {
    ap_block_pp0_stage1_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage2_00001() {
    ap_block_pp0_stage2_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage3_00001() {
    ap_block_pp0_stage3_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_state4_pp0_stage2_iter0() {
    ap_block_state4_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_state5_pp0_stage3_iter0() {
    ap_block_state5_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_block_state6_pp0_stage0_iter1() {
    ap_block_state6_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void max_pool_2D::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten2_fu_222_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pool_2D::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void max_pool_2D::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool_2D::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_ap_phi_mux_i_phi_fu_160_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_phi_fu_160_p4 = i_cast9_mid2_v_reg_642.read();
    } else {
        ap_phi_mux_i_phi_fu_160_p4 = i_reg_156.read();
    }
}

void max_pool_2D::thread_ap_phi_mux_indvar_flatten2_phi_fu_149_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten2_phi_fu_149_p4 = indvar_flatten_next2_reg_637.read();
    } else {
        ap_phi_mux_indvar_flatten2_phi_fu_149_p4 = indvar_flatten2_reg_145.read();
    }
}

void max_pool_2D::thread_ap_phi_mux_indvar_flatten_phi_fu_171_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_171_p4 = indvar_flatten_next_reg_697.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_171_p4 = indvar_flatten_reg_167.read();
    }
}

void max_pool_2D::thread_ap_phi_mux_j_phi_fu_182_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_phi_fu_182_p4 = j_cast8_mid2_reg_654.read();
    } else {
        ap_phi_mux_j_phi_fu_182_p4 = j_reg_178.read();
    }
}

void max_pool_2D::thread_ap_phi_mux_n_phi_fu_193_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_n_phi_fu_193_p4 = n_1_reg_743.read();
    } else {
        ap_phi_mux_n_phi_fu_193_p4 = n_reg_189.read();
    }
}

void max_pool_2D::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool_2D::thread_exitcond_flatten2_fu_222_p2() {
    exitcond_flatten2_fu_222_p2 = (!ap_phi_mux_indvar_flatten2_phi_fu_149_p4.read().is_01() || !ap_const_lv9_190.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten2_phi_fu_149_p4.read() == ap_const_lv9_190);
}

void max_pool_2D::thread_exitcond_flatten_fu_234_p2() {
    exitcond_flatten_fu_234_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_171_p4.read().is_01() || !ap_const_lv8_50.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_171_p4.read() == ap_const_lv8_50);
}

void max_pool_2D::thread_exitcond_fu_306_p2() {
    exitcond_fu_306_p2 = (!ap_phi_mux_n_phi_fu_193_p4.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_n_phi_fu_193_p4.read() == ap_const_lv5_10);
}

void max_pool_2D::thread_exitcond_mid_fu_312_p2() {
    exitcond_mid_fu_312_p2 = (exitcond_fu_306_p2.read() & not_exitcond_flatten_fu_300_p2.read());
}

void max_pool_2D::thread_grp_fu_200_p0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0)))) {
        grp_fu_200_p0 = in_r_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_200_p0 = in_r_q1.read();
    } else {
        grp_fu_200_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pool_2D::thread_grp_fu_200_p1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0)))) {
        grp_fu_200_p1 = in_r_q1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_200_p1 = in_r_q0.read();
    } else {
        grp_fu_200_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void max_pool_2D::thread_i_cast9_mid2_fu_558_p1() {
    i_cast9_mid2_fu_558_p1 = esl_zext<7,3>(i_cast9_mid2_v_reg_642.read());
}

void max_pool_2D::thread_i_cast9_mid2_v_fu_254_p3() {
    i_cast9_mid2_v_fu_254_p3 = (!exitcond_flatten_fu_234_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_flatten_fu_234_p2.read()[0].to_bool())? i_s_fu_248_p2.read(): ap_phi_mux_i_phi_fu_160_p4.read());
}

void max_pool_2D::thread_i_s_fu_248_p2() {
    i_s_fu_248_p2 = (!ap_const_lv3_1.is_01() || !ap_phi_mux_i_phi_fu_160_p4.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(ap_phi_mux_i_phi_fu_160_p4.read()));
}

void max_pool_2D::thread_in_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
            in_r_address0 =  (sc_lv<11>) (max_val_5_cast_fu_570_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            in_r_address0 =  (sc_lv<11>) (tmp_21_fu_543_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            in_r_address0 =  (sc_lv<11>) (tmp_19_fu_528_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            in_r_address0 =  (sc_lv<11>) (tmp_13_fu_454_p1.read());
        } else {
            in_r_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        in_r_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void max_pool_2D::thread_in_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
            in_r_address1 =  (sc_lv<11>) (max_val_4_cast_fu_553_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
            in_r_address1 =  (sc_lv<11>) (max_val_1_cast_fu_538_p1.read());
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                    esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
            in_r_address1 =  (sc_lv<11>) (tmp_15_fu_465_p1.read());
        } else {
            in_r_address1 =  (sc_lv<11>) ("XXXXXXXXXXX");
        }
    } else {
        in_r_address1 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void max_pool_2D::thread_in_r_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_in_r_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0)))) {
        in_r_ce1 = ap_const_logic_1;
    } else {
        in_r_ce1 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_indvar_flatten_next2_fu_228_p2() {
    indvar_flatten_next2_fu_228_p2 = (!ap_phi_mux_indvar_flatten2_phi_fu_149_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_indvar_flatten2_phi_fu_149_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void max_pool_2D::thread_indvar_flatten_next_fu_520_p3() {
    indvar_flatten_next_fu_520_p3 = (!exitcond_flatten_fu_234_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond_flatten_fu_234_p2.read()[0].to_bool())? ap_const_lv8_1: indvar_flatten_op_fu_514_p2.read());
}

void max_pool_2D::thread_indvar_flatten_op_fu_514_p2() {
    indvar_flatten_op_fu_514_p2 = (!ap_const_lv8_1.is_01() || !ap_phi_mux_indvar_flatten_phi_fu_171_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_1) + sc_biguint<8>(ap_phi_mux_indvar_flatten_phi_fu_171_p4.read()));
}

void max_pool_2D::thread_j_1_fu_318_p2() {
    j_1_fu_318_p2 = (!ap_const_lv3_1.is_01() || !j_mid_fu_240_p3.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_1) + sc_biguint<3>(j_mid_fu_240_p3.read()));
}

void max_pool_2D::thread_j_cast8_mid2_cast_fu_603_p1() {
    j_cast8_mid2_cast_fu_603_p1 = esl_zext<9,3>(j_cast8_mid2_reg_654.read());
}

void max_pool_2D::thread_j_cast8_mid2_fu_338_p3() {
    j_cast8_mid2_fu_338_p3 = (!exitcond_mid_fu_312_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_mid_fu_312_p2.read()[0].to_bool())? j_1_fu_318_p2.read(): j_mid_fu_240_p3.read());
}

void max_pool_2D::thread_j_mid_fu_240_p3() {
    j_mid_fu_240_p3 = (!exitcond_flatten_fu_234_p2.read()[0].is_01())? sc_lv<3>(): ((exitcond_flatten_fu_234_p2.read()[0].to_bool())? ap_const_lv3_0: ap_phi_mux_j_phi_fu_182_p4.read());
}

void max_pool_2D::thread_max_val_1_cast_fu_538_p1() {
    max_val_1_cast_fu_538_p1 = esl_zext<64,11>(max_val_1_fu_532_p3.read());
}

void max_pool_2D::thread_max_val_1_fu_532_p3() {
    max_val_1_fu_532_p3 = (!grp_fu_200_p2.read()[0].is_01())? sc_lv<11>(): ((grp_fu_200_p2.read()[0].to_bool())? tmp_14_reg_675.read(): tmp_12_reg_665.read());
}

void max_pool_2D::thread_max_val_4_cast_fu_553_p1() {
    max_val_4_cast_fu_553_p1 = esl_zext<64,11>(max_val_4_fu_547_p3.read());
}

void max_pool_2D::thread_max_val_4_fu_547_p3() {
    max_val_4_fu_547_p3 = (!grp_fu_200_p2.read()[0].is_01())? sc_lv<11>(): ((grp_fu_200_p2.read()[0].to_bool())? tmp_18_reg_685.read(): max_val_1_reg_707.read());
}

void max_pool_2D::thread_max_val_5_cast_fu_570_p1() {
    max_val_5_cast_fu_570_p1 = esl_zext<64,11>(max_val_5_fu_564_p3.read());
}

void max_pool_2D::thread_max_val_5_fu_564_p3() {
    max_val_5_fu_564_p3 = (!grp_fu_200_p2.read()[0].is_01())? sc_lv<11>(): ((grp_fu_200_p2.read()[0].to_bool())? tmp_20_reg_691.read(): max_val_4_reg_722.read());
}

void max_pool_2D::thread_n_1_fu_598_p2() {
    n_1_fu_598_p2 = (!ap_const_lv5_1.is_01() || !n_mid2_reg_648.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_1) + sc_biguint<5>(n_mid2_reg_648.read()));
}

void max_pool_2D::thread_n_cast7_fu_561_p1() {
    n_cast7_fu_561_p1 = esl_zext<7,5>(n_mid2_reg_648.read());
}

void max_pool_2D::thread_n_mid2_fu_330_p3() {
    n_mid2_fu_330_p3 = (!tmp_fu_324_p2.read()[0].is_01())? sc_lv<5>(): ((tmp_fu_324_p2.read()[0].to_bool())? ap_const_lv5_0: ap_phi_mux_n_phi_fu_193_p4.read());
}

void max_pool_2D::thread_not_exitcond_flatten_fu_300_p2() {
    not_exitcond_flatten_fu_300_p2 = (exitcond_flatten_fu_234_p2.read() ^ ap_const_lv1_1);
}

void max_pool_2D::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<9>) (tmp_24_fu_628_p1.read());
}

void max_pool_2D::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_output_r_d0() {
    output_r_d0 = in_r_q0.read();
}

void max_pool_2D::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten2_reg_633.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pool_2D::thread_p_shl1_cast_fu_492_p1() {
    p_shl1_cast_fu_492_p1 = esl_zext<11,9>(p_shl1_fu_484_p3.read());
}

void max_pool_2D::thread_p_shl1_fu_484_p3() {
    p_shl1_fu_484_p3 = esl_concat<8,1>(tmp_16_fu_470_p2.read(), ap_const_lv1_0);
}

void max_pool_2D::thread_p_shl2_fu_422_p3() {
    p_shl2_fu_422_p3 = esl_concat<8,3>(tmp_10_fu_416_p2.read(), ap_const_lv3_0);
}

void max_pool_2D::thread_p_shl3_cast_fu_438_p1() {
    p_shl3_cast_fu_438_p1 = esl_zext<11,9>(p_shl3_fu_430_p3.read());
}

void max_pool_2D::thread_p_shl3_fu_430_p3() {
    p_shl3_fu_430_p3 = esl_concat<8,1>(tmp_10_fu_416_p2.read(), ap_const_lv1_0);
}

void max_pool_2D::thread_p_shl4_cast_fu_396_p1() {
    p_shl4_cast_fu_396_p1 = esl_zext<8,7>(p_shl4_fu_388_p3.read());
}

void max_pool_2D::thread_p_shl4_fu_388_p3() {
    p_shl4_fu_388_p3 = esl_concat<4,3>(tmp_1_fu_384_p1.read(), ap_const_lv3_0);
}

void max_pool_2D::thread_p_shl5_cast_fu_406_p1() {
    p_shl5_cast_fu_406_p1 = esl_zext<8,5>(tmp_2_fu_400_p2.read());
}

void max_pool_2D::thread_p_shl6_fu_609_p3() {
    p_shl6_fu_609_p3 = esl_concat<7,2>(tmp5_reg_737.read(), ap_const_lv2_0);
}

void max_pool_2D::thread_p_shl7_cast_fu_582_p1() {
    p_shl7_cast_fu_582_p1 = esl_zext<7,6>(p_shl7_fu_575_p3.read());
}

void max_pool_2D::thread_p_shl7_fu_575_p3() {
    p_shl7_fu_575_p3 = esl_concat<4,2>(tmp_1_reg_660.read(), ap_const_lv2_0);
}

void max_pool_2D::thread_p_shl_fu_476_p3() {
    p_shl_fu_476_p3 = esl_concat<8,3>(tmp_16_fu_470_p2.read(), ap_const_lv3_0);
}

void max_pool_2D::thread_tmp3_fu_586_p2() {
    tmp3_fu_586_p2 = (!i_cast9_mid2_fu_558_p1.read().is_01() || !p_shl7_cast_fu_582_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(i_cast9_mid2_fu_558_p1.read()) + sc_biguint<7>(p_shl7_cast_fu_582_p1.read()));
}

void max_pool_2D::thread_tmp4_fu_616_p2() {
    tmp4_fu_616_p2 = (!j_cast8_mid2_cast_fu_603_p1.read().is_01() || !p_shl6_fu_609_p3.read().is_01())? sc_lv<9>(): (sc_biguint<9>(j_cast8_mid2_cast_fu_603_p1.read()) + sc_biguint<9>(p_shl6_fu_609_p3.read()));
}

void max_pool_2D::thread_tmp5_cast_fu_606_p1() {
    tmp5_cast_fu_606_p1 = esl_zext<9,7>(tmp5_reg_737.read());
}

void max_pool_2D::thread_tmp5_fu_592_p2() {
    tmp5_fu_592_p2 = (!n_cast7_fu_561_p1.read().is_01() || !tmp3_fu_586_p2.read().is_01())? sc_lv<7>(): (sc_biguint<7>(n_cast7_fu_561_p1.read()) + sc_biguint<7>(tmp3_fu_586_p2.read()));
}

void max_pool_2D::thread_tmp_10_fu_416_p2() {
    tmp_10_fu_416_p2 = (!tmp_4_cast_mid2_fu_270_p1.read().is_01() || !tmp_9_fu_410_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_4_cast_mid2_fu_270_p1.read()) + sc_biguint<8>(tmp_9_fu_410_p2.read()));
}

void max_pool_2D::thread_tmp_11_fu_442_p2() {
    tmp_11_fu_442_p2 = (!p_shl2_fu_422_p3.read().is_01() || !p_shl3_cast_fu_438_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl2_fu_422_p3.read()) + sc_biguint<11>(p_shl3_cast_fu_438_p1.read()));
}

void max_pool_2D::thread_tmp_12_fu_448_p2() {
    tmp_12_fu_448_p2 = (!tmp_7_cast_mid2_cast_fu_362_p1.read().is_01() || !tmp_11_fu_442_p2.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_7_cast_mid2_cast_fu_362_p1.read()) + sc_biguint<11>(tmp_11_fu_442_p2.read()));
}

void max_pool_2D::thread_tmp_13_fu_454_p1() {
    tmp_13_fu_454_p1 = esl_zext<64,11>(tmp_12_fu_448_p2.read());
}

void max_pool_2D::thread_tmp_14_fu_459_p2() {
    tmp_14_fu_459_p2 = (!tmp_8_cast_mid2_cast_fu_380_p1.read().is_01() || !tmp_11_fu_442_p2.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_8_cast_mid2_cast_fu_380_p1.read()) + sc_biguint<11>(tmp_11_fu_442_p2.read()));
}

void max_pool_2D::thread_tmp_15_fu_465_p1() {
    tmp_15_fu_465_p1 = esl_zext<64,11>(tmp_14_fu_459_p2.read());
}

void max_pool_2D::thread_tmp_16_fu_470_p2() {
    tmp_16_fu_470_p2 = (!tmp_5_cast_mid2_fu_280_p1.read().is_01() || !tmp_9_fu_410_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_5_cast_mid2_fu_280_p1.read()) + sc_biguint<8>(tmp_9_fu_410_p2.read()));
}

void max_pool_2D::thread_tmp_17_fu_496_p2() {
    tmp_17_fu_496_p2 = (!p_shl_fu_476_p3.read().is_01() || !p_shl1_cast_fu_492_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_fu_476_p3.read()) + sc_biguint<11>(p_shl1_cast_fu_492_p1.read()));
}

void max_pool_2D::thread_tmp_18_fu_502_p2() {
    tmp_18_fu_502_p2 = (!tmp_7_cast_mid2_cast_fu_362_p1.read().is_01() || !tmp_17_fu_496_p2.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_7_cast_mid2_cast_fu_362_p1.read()) + sc_biguint<11>(tmp_17_fu_496_p2.read()));
}

void max_pool_2D::thread_tmp_19_fu_528_p1() {
    tmp_19_fu_528_p1 = esl_zext<64,11>(tmp_18_reg_685.read());
}

void max_pool_2D::thread_tmp_1_fu_384_p1() {
    tmp_1_fu_384_p1 = n_mid2_fu_330_p3.read().range(4-1, 0);
}

void max_pool_2D::thread_tmp_20_fu_508_p2() {
    tmp_20_fu_508_p2 = (!tmp_8_cast_mid2_cast_fu_380_p1.read().is_01() || !tmp_17_fu_496_p2.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_8_cast_mid2_cast_fu_380_p1.read()) + sc_biguint<11>(tmp_17_fu_496_p2.read()));
}

void max_pool_2D::thread_tmp_21_fu_543_p1() {
    tmp_21_fu_543_p1 = esl_zext<64,11>(tmp_20_reg_691.read());
}

void max_pool_2D::thread_tmp_23_fu_622_p2() {
    tmp_23_fu_622_p2 = (!tmp5_cast_fu_606_p1.read().is_01() || !tmp4_fu_616_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp5_cast_fu_606_p1.read()) + sc_biguint<9>(tmp4_fu_616_p2.read()));
}

void max_pool_2D::thread_tmp_24_fu_628_p1() {
    tmp_24_fu_628_p1 = esl_zext<64,9>(tmp_23_fu_622_p2.read());
}

void max_pool_2D::thread_tmp_2_fu_400_p2() {
    tmp_2_fu_400_p2 = (!ap_const_lv5_1.is_01())? sc_lv<5>(): n_mid2_fu_330_p3.read() << (unsigned short)ap_const_lv5_1.to_uint();
}

void max_pool_2D::thread_tmp_4_cast_mid2_fu_270_p1() {
    tmp_4_cast_mid2_fu_270_p1 = esl_zext<8,4>(tmp_4_cast_mid2_v_fu_262_p3.read());
}

void max_pool_2D::thread_tmp_4_cast_mid2_v_fu_262_p3() {
    tmp_4_cast_mid2_v_fu_262_p3 = esl_concat<3,1>(i_cast9_mid2_v_fu_254_p3.read(), ap_const_lv1_0);
}

void max_pool_2D::thread_tmp_5_cast_mid2_fu_280_p1() {
    tmp_5_cast_mid2_fu_280_p1 = esl_zext<8,4>(tmp_5_cast_mid2_v_fu_274_p2.read());
}

void max_pool_2D::thread_tmp_5_cast_mid2_v_fu_274_p2() {
    tmp_5_cast_mid2_v_fu_274_p2 = (tmp_4_cast_mid2_v_fu_262_p3.read() | ap_const_lv4_1);
}

void max_pool_2D::thread_tmp_7_cast_mid2_cast_fu_362_p1() {
    tmp_7_cast_mid2_cast_fu_362_p1 = esl_zext<11,4>(tmp_7_cast_mid2_fu_354_p3.read());
}

void max_pool_2D::thread_tmp_7_cast_mid2_fu_354_p3() {
    tmp_7_cast_mid2_fu_354_p3 = (!exitcond_mid_fu_312_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_mid_fu_312_p2.read()[0].to_bool())? tmp_7_mid1_fu_346_p3.read(): tmp_7_cast_mid_fu_284_p3.read());
}

void max_pool_2D::thread_tmp_7_cast_mid_fu_284_p3() {
    tmp_7_cast_mid_fu_284_p3 = (!exitcond_flatten_fu_234_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_fu_234_p2.read()[0].to_bool())? ap_const_lv4_0: tmp_7_fu_208_p3.read());
}

void max_pool_2D::thread_tmp_7_fu_208_p3() {
    tmp_7_fu_208_p3 = esl_concat<3,1>(ap_phi_mux_j_phi_fu_182_p4.read(), ap_const_lv1_0);
}

void max_pool_2D::thread_tmp_7_mid1_fu_346_p3() {
    tmp_7_mid1_fu_346_p3 = esl_concat<3,1>(j_1_fu_318_p2.read(), ap_const_lv1_0);
}

void max_pool_2D::thread_tmp_8_cast_mid2_cast_fu_380_p1() {
    tmp_8_cast_mid2_cast_fu_380_p1 = esl_zext<11,4>(tmp_8_cast_mid2_fu_372_p3.read());
}

void max_pool_2D::thread_tmp_8_cast_mid2_fu_372_p3() {
    tmp_8_cast_mid2_fu_372_p3 = (!exitcond_mid_fu_312_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_mid_fu_312_p2.read()[0].to_bool())? tmp_8_mid1_fu_366_p2.read(): tmp_8_cast_mid_fu_292_p3.read());
}

void max_pool_2D::thread_tmp_8_cast_mid_fu_292_p3() {
    tmp_8_cast_mid_fu_292_p3 = (!exitcond_flatten_fu_234_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_fu_234_p2.read()[0].to_bool())? ap_const_lv4_1: tmp_8_fu_216_p2.read());
}

void max_pool_2D::thread_tmp_8_fu_216_p2() {
    tmp_8_fu_216_p2 = (tmp_7_fu_208_p3.read() | ap_const_lv4_1);
}

void max_pool_2D::thread_tmp_8_mid1_fu_366_p2() {
    tmp_8_mid1_fu_366_p2 = (tmp_7_mid1_fu_346_p3.read() | ap_const_lv4_1);
}

void max_pool_2D::thread_tmp_9_fu_410_p2() {
    tmp_9_fu_410_p2 = (!p_shl4_cast_fu_396_p1.read().is_01() || !p_shl5_cast_fu_406_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_shl4_cast_fu_396_p1.read()) + sc_biguint<8>(p_shl5_cast_fu_406_p1.read()));
}

void max_pool_2D::thread_tmp_fu_324_p2() {
    tmp_fu_324_p2 = (exitcond_mid_fu_312_p2.read() | exitcond_flatten_fu_234_p2.read());
}

void max_pool_2D::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten2_fu_222_p2.read(), ap_const_lv1_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten2_fu_222_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

