// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top_net.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic top_net::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic top_net::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<24> top_net::ap_ST_fsm_state1 = "1";
const sc_lv<24> top_net::ap_ST_fsm_state2 = "10";
const sc_lv<24> top_net::ap_ST_fsm_state3 = "100";
const sc_lv<24> top_net::ap_ST_fsm_state4 = "1000";
const sc_lv<24> top_net::ap_ST_fsm_state5 = "10000";
const sc_lv<24> top_net::ap_ST_fsm_state6 = "100000";
const sc_lv<24> top_net::ap_ST_fsm_state7 = "1000000";
const sc_lv<24> top_net::ap_ST_fsm_state8 = "10000000";
const sc_lv<24> top_net::ap_ST_fsm_state9 = "100000000";
const sc_lv<24> top_net::ap_ST_fsm_state10 = "1000000000";
const sc_lv<24> top_net::ap_ST_fsm_state11 = "10000000000";
const sc_lv<24> top_net::ap_ST_fsm_state12 = "100000000000";
const sc_lv<24> top_net::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<24> top_net::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<32> top_net::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> top_net::ap_const_lv32_10 = "10000";
const sc_lv<1> top_net::ap_const_lv1_1 = "1";
const sc_lv<32> top_net::ap_const_lv32_12 = "10010";
const sc_lv<32> top_net::ap_const_lv32_17 = "10111";
const int top_net::C_S_AXI_DATA_WIDTH = "100000";
const int top_net::C_M_AXI_GMEM_USER_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int top_net::C_M_AXI_GMEM_PROT_VALUE = "0000000000000000000000000000000000000000000000000000000000000000";
const int top_net::C_M_AXI_GMEM_CACHE_VALUE = "11";
const int top_net::C_M_AXI_DATA_WIDTH = "100000";
const sc_lv<32> top_net::ap_const_lv32_E = "1110";
const sc_lv<32> top_net::ap_const_lv32_F = "1111";
const bool top_net::ap_const_boolean_0 = false;
const sc_lv<1> top_net::ap_const_lv1_0 = "0";
const sc_lv<32> top_net::ap_const_lv32_11 = "10001";
const sc_lv<4> top_net::ap_const_lv4_1 = "1";
const sc_lv<32> top_net::ap_const_lv32_1 = "1";
const sc_lv<32> top_net::ap_const_lv32_4 = "100";
const sc_lv<32> top_net::ap_const_lv32_5 = "101";
const sc_lv<32> top_net::ap_const_lv32_8 = "1000";
const sc_lv<32> top_net::ap_const_lv32_9 = "1001";
const sc_lv<32> top_net::ap_const_lv32_A = "1010";
const sc_lv<32> top_net::ap_const_lv32_B = "1011";
const sc_lv<32> top_net::ap_const_lv32_C = "1100";
const sc_lv<32> top_net::ap_const_lv32_D = "1101";
const sc_lv<32> top_net::ap_const_lv32_2 = "10";
const sc_lv<32> top_net::ap_const_lv32_3 = "11";
const sc_lv<32> top_net::ap_const_lv32_6 = "110";
const sc_lv<32> top_net::ap_const_lv32_7 = "111";
const sc_lv<64> top_net::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<3> top_net::ap_const_lv3_0 = "000";
const sc_lv<2> top_net::ap_const_lv2_0 = "00";
const sc_lv<4> top_net::ap_const_lv4_0 = "0000";
const sc_lv<4> top_net::ap_const_lv4_F = "1111";
const sc_lv<32> top_net::ap_const_lv32_1F = "11111";
const sc_lv<4> top_net::ap_const_lv4_A = "1010";
const sc_lv<5> top_net::ap_const_lv5_2 = "10";
const bool top_net::ap_const_boolean_1 = true;

top_net::top_net(sc_module_name name) : sc_module(name), mVcdFile(0) {
    top_net_AXILiteS_s_axi_U = new top_net_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("top_net_AXILiteS_s_axi_U");
    top_net_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    top_net_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    top_net_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    top_net_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    top_net_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    top_net_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    top_net_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    top_net_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    top_net_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    top_net_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    top_net_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    top_net_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    top_net_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    top_net_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    top_net_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    top_net_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    top_net_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    top_net_AXILiteS_s_axi_U->ACLK(ap_clk);
    top_net_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    top_net_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    top_net_AXILiteS_s_axi_U->ap_start(ap_start);
    top_net_AXILiteS_s_axi_U->interrupt(interrupt);
    top_net_AXILiteS_s_axi_U->ap_ready(ap_ready);
    top_net_AXILiteS_s_axi_U->ap_done(ap_done);
    top_net_AXILiteS_s_axi_U->ap_idle(ap_idle);
    top_net_AXILiteS_s_axi_U->in_r(in_r);
    top_net_AXILiteS_s_axi_U->result(result);
    top_net_gmem_m_axi_U = new top_net_gmem_m_axi<0,32,32,5,16,16,16,16,C_M_AXI_GMEM_ID_WIDTH,C_M_AXI_GMEM_ADDR_WIDTH,C_M_AXI_GMEM_DATA_WIDTH,C_M_AXI_GMEM_AWUSER_WIDTH,C_M_AXI_GMEM_ARUSER_WIDTH,C_M_AXI_GMEM_WUSER_WIDTH,C_M_AXI_GMEM_RUSER_WIDTH,C_M_AXI_GMEM_BUSER_WIDTH,C_M_AXI_GMEM_USER_VALUE,C_M_AXI_GMEM_PROT_VALUE,C_M_AXI_GMEM_CACHE_VALUE>("top_net_gmem_m_axi_U");
    top_net_gmem_m_axi_U->AWVALID(m_axi_gmem_AWVALID);
    top_net_gmem_m_axi_U->AWREADY(m_axi_gmem_AWREADY);
    top_net_gmem_m_axi_U->AWADDR(m_axi_gmem_AWADDR);
    top_net_gmem_m_axi_U->AWID(m_axi_gmem_AWID);
    top_net_gmem_m_axi_U->AWLEN(m_axi_gmem_AWLEN);
    top_net_gmem_m_axi_U->AWSIZE(m_axi_gmem_AWSIZE);
    top_net_gmem_m_axi_U->AWBURST(m_axi_gmem_AWBURST);
    top_net_gmem_m_axi_U->AWLOCK(m_axi_gmem_AWLOCK);
    top_net_gmem_m_axi_U->AWCACHE(m_axi_gmem_AWCACHE);
    top_net_gmem_m_axi_U->AWPROT(m_axi_gmem_AWPROT);
    top_net_gmem_m_axi_U->AWQOS(m_axi_gmem_AWQOS);
    top_net_gmem_m_axi_U->AWREGION(m_axi_gmem_AWREGION);
    top_net_gmem_m_axi_U->AWUSER(m_axi_gmem_AWUSER);
    top_net_gmem_m_axi_U->WVALID(m_axi_gmem_WVALID);
    top_net_gmem_m_axi_U->WREADY(m_axi_gmem_WREADY);
    top_net_gmem_m_axi_U->WDATA(m_axi_gmem_WDATA);
    top_net_gmem_m_axi_U->WSTRB(m_axi_gmem_WSTRB);
    top_net_gmem_m_axi_U->WLAST(m_axi_gmem_WLAST);
    top_net_gmem_m_axi_U->WID(m_axi_gmem_WID);
    top_net_gmem_m_axi_U->WUSER(m_axi_gmem_WUSER);
    top_net_gmem_m_axi_U->ARVALID(m_axi_gmem_ARVALID);
    top_net_gmem_m_axi_U->ARREADY(m_axi_gmem_ARREADY);
    top_net_gmem_m_axi_U->ARADDR(m_axi_gmem_ARADDR);
    top_net_gmem_m_axi_U->ARID(m_axi_gmem_ARID);
    top_net_gmem_m_axi_U->ARLEN(m_axi_gmem_ARLEN);
    top_net_gmem_m_axi_U->ARSIZE(m_axi_gmem_ARSIZE);
    top_net_gmem_m_axi_U->ARBURST(m_axi_gmem_ARBURST);
    top_net_gmem_m_axi_U->ARLOCK(m_axi_gmem_ARLOCK);
    top_net_gmem_m_axi_U->ARCACHE(m_axi_gmem_ARCACHE);
    top_net_gmem_m_axi_U->ARPROT(m_axi_gmem_ARPROT);
    top_net_gmem_m_axi_U->ARQOS(m_axi_gmem_ARQOS);
    top_net_gmem_m_axi_U->ARREGION(m_axi_gmem_ARREGION);
    top_net_gmem_m_axi_U->ARUSER(m_axi_gmem_ARUSER);
    top_net_gmem_m_axi_U->RVALID(m_axi_gmem_RVALID);
    top_net_gmem_m_axi_U->RREADY(m_axi_gmem_RREADY);
    top_net_gmem_m_axi_U->RDATA(m_axi_gmem_RDATA);
    top_net_gmem_m_axi_U->RLAST(m_axi_gmem_RLAST);
    top_net_gmem_m_axi_U->RID(m_axi_gmem_RID);
    top_net_gmem_m_axi_U->RUSER(m_axi_gmem_RUSER);
    top_net_gmem_m_axi_U->RRESP(m_axi_gmem_RRESP);
    top_net_gmem_m_axi_U->BVALID(m_axi_gmem_BVALID);
    top_net_gmem_m_axi_U->BREADY(m_axi_gmem_BREADY);
    top_net_gmem_m_axi_U->BRESP(m_axi_gmem_BRESP);
    top_net_gmem_m_axi_U->BID(m_axi_gmem_BID);
    top_net_gmem_m_axi_U->BUSER(m_axi_gmem_BUSER);
    top_net_gmem_m_axi_U->ACLK(ap_clk);
    top_net_gmem_m_axi_U->ARESET(ap_rst_n_inv);
    top_net_gmem_m_axi_U->ACLK_EN(ap_var_for_const0);
    top_net_gmem_m_axi_U->I_ARVALID(gmem_ARVALID);
    top_net_gmem_m_axi_U->I_ARREADY(gmem_ARREADY);
    top_net_gmem_m_axi_U->I_ARADDR(grp_conv_1_fu_212_m_axi_in_r_ARADDR);
    top_net_gmem_m_axi_U->I_ARID(grp_conv_1_fu_212_m_axi_in_r_ARID);
    top_net_gmem_m_axi_U->I_ARLEN(grp_conv_1_fu_212_m_axi_in_r_ARLEN);
    top_net_gmem_m_axi_U->I_ARSIZE(grp_conv_1_fu_212_m_axi_in_r_ARSIZE);
    top_net_gmem_m_axi_U->I_ARLOCK(grp_conv_1_fu_212_m_axi_in_r_ARLOCK);
    top_net_gmem_m_axi_U->I_ARCACHE(grp_conv_1_fu_212_m_axi_in_r_ARCACHE);
    top_net_gmem_m_axi_U->I_ARQOS(grp_conv_1_fu_212_m_axi_in_r_ARQOS);
    top_net_gmem_m_axi_U->I_ARPROT(grp_conv_1_fu_212_m_axi_in_r_ARPROT);
    top_net_gmem_m_axi_U->I_ARUSER(grp_conv_1_fu_212_m_axi_in_r_ARUSER);
    top_net_gmem_m_axi_U->I_ARBURST(grp_conv_1_fu_212_m_axi_in_r_ARBURST);
    top_net_gmem_m_axi_U->I_ARREGION(grp_conv_1_fu_212_m_axi_in_r_ARREGION);
    top_net_gmem_m_axi_U->I_RVALID(gmem_RVALID);
    top_net_gmem_m_axi_U->I_RREADY(gmem_RREADY);
    top_net_gmem_m_axi_U->I_RDATA(gmem_RDATA);
    top_net_gmem_m_axi_U->I_RID(gmem_RID);
    top_net_gmem_m_axi_U->I_RUSER(gmem_RUSER);
    top_net_gmem_m_axi_U->I_RRESP(gmem_RRESP);
    top_net_gmem_m_axi_U->I_RLAST(gmem_RLAST);
    top_net_gmem_m_axi_U->I_AWVALID(gmem_AWVALID);
    top_net_gmem_m_axi_U->I_AWREADY(gmem_AWREADY);
    top_net_gmem_m_axi_U->I_AWADDR(gmem_addr_reg_364);
    top_net_gmem_m_axi_U->I_AWID(ap_var_for_const1);
    top_net_gmem_m_axi_U->I_AWLEN(ap_var_for_const2);
    top_net_gmem_m_axi_U->I_AWSIZE(ap_var_for_const3);
    top_net_gmem_m_axi_U->I_AWLOCK(ap_var_for_const4);
    top_net_gmem_m_axi_U->I_AWCACHE(ap_var_for_const5);
    top_net_gmem_m_axi_U->I_AWQOS(ap_var_for_const5);
    top_net_gmem_m_axi_U->I_AWPROT(ap_var_for_const3);
    top_net_gmem_m_axi_U->I_AWUSER(ap_var_for_const1);
    top_net_gmem_m_axi_U->I_AWBURST(ap_var_for_const4);
    top_net_gmem_m_axi_U->I_AWREGION(ap_var_for_const5);
    top_net_gmem_m_axi_U->I_WVALID(gmem_WVALID);
    top_net_gmem_m_axi_U->I_WREADY(gmem_WREADY);
    top_net_gmem_m_axi_U->I_WDATA(max_index_i_reg_178);
    top_net_gmem_m_axi_U->I_WID(ap_var_for_const1);
    top_net_gmem_m_axi_U->I_WUSER(ap_var_for_const1);
    top_net_gmem_m_axi_U->I_WLAST(ap_var_for_const6);
    top_net_gmem_m_axi_U->I_WSTRB(ap_var_for_const7);
    top_net_gmem_m_axi_U->I_BVALID(gmem_BVALID);
    top_net_gmem_m_axi_U->I_BREADY(gmem_BREADY);
    top_net_gmem_m_axi_U->I_BRESP(gmem_BRESP);
    top_net_gmem_m_axi_U->I_BID(gmem_BID);
    top_net_gmem_m_axi_U->I_BUSER(gmem_BUSER);
    c1_output_U = new top_net_c1_output("c1_output_U");
    c1_output_U->clk(ap_clk);
    c1_output_U->reset(ap_rst_n_inv);
    c1_output_U->address0(c1_output_address0);
    c1_output_U->ce0(c1_output_ce0);
    c1_output_U->we0(c1_output_we0);
    c1_output_U->d0(grp_conv_1_fu_212_output_r_d0);
    c1_output_U->q0(c1_output_q0);
    c1_output_U->address1(grp_max_pool_2D_1_fu_265_in_r_address1);
    c1_output_U->ce1(c1_output_ce1);
    c1_output_U->q1(c1_output_q1);
    p1_output_U = new top_net_p1_output("p1_output_U");
    p1_output_U->clk(ap_clk);
    p1_output_U->reset(ap_rst_n_inv);
    p1_output_U->address0(p1_output_address0);
    p1_output_U->ce0(p1_output_ce0);
    p1_output_U->we0(p1_output_we0);
    p1_output_U->d0(grp_max_pool_2D_1_fu_265_output_r_d0);
    p1_output_U->q0(p1_output_q0);
    c2_output_U = new top_net_c2_output("c2_output_U");
    c2_output_U->clk(ap_clk);
    c2_output_U->reset(ap_rst_n_inv);
    c2_output_U->address0(c2_output_address0);
    c2_output_U->ce0(c2_output_ce0);
    c2_output_U->we0(c2_output_we0);
    c2_output_U->d0(grp_conv_2_fu_225_output_r_d0);
    c2_output_U->q0(c2_output_q0);
    c2_output_U->address1(grp_max_pool_2D_fu_271_in_r_address1);
    c2_output_U->ce1(c2_output_ce1);
    c2_output_U->q1(c2_output_q1);
    p2_output_U = new top_net_p2_output("p2_output_U");
    p2_output_U->clk(ap_clk);
    p2_output_U->reset(ap_rst_n_inv);
    p2_output_U->address0(p2_output_address0);
    p2_output_U->ce0(p2_output_ce0);
    p2_output_U->we0(p2_output_we0);
    p2_output_U->d0(grp_max_pool_2D_fu_271_output_r_d0);
    p2_output_U->q0(p2_output_q0);
    c3_output_U = new top_net_c3_output("c3_output_U");
    c3_output_U->clk(ap_clk);
    c3_output_U->reset(ap_rst_n_inv);
    c3_output_U->address0(c3_output_address0);
    c3_output_U->ce0(c3_output_ce0);
    c3_output_U->we0(c3_output_we0);
    c3_output_U->d0(grp_conv_3_fu_235_output_r_d0);
    c3_output_U->q0(c3_output_q0);
    c4_output_U = new top_net_c4_output("c4_output_U");
    c4_output_U->clk(ap_clk);
    c4_output_U->reset(ap_rst_n_inv);
    c4_output_U->address0(c4_output_address0);
    c4_output_U->ce0(c4_output_ce0);
    c4_output_U->we0(c4_output_we0);
    c4_output_U->d0(grp_conv_4_fu_245_output_r_d0);
    c4_output_U->q0(c4_output_q0);
    c5_output_U = new top_net_c5_output("c5_output_U");
    c5_output_U->clk(ap_clk);
    c5_output_U->reset(ap_rst_n_inv);
    c5_output_U->address0(c5_output_address0);
    c5_output_U->ce0(c5_output_ce0);
    c5_output_U->we0(c5_output_we0);
    c5_output_U->d0(grp_conv_5_fu_255_output_r_d0);
    c5_output_U->q0(c5_output_q0);
    grp_conv_1_fu_212 = new conv_1("grp_conv_1_fu_212");
    grp_conv_1_fu_212->ap_clk(ap_clk);
    grp_conv_1_fu_212->ap_rst(ap_rst_n_inv);
    grp_conv_1_fu_212->ap_start(grp_conv_1_fu_212_ap_start);
    grp_conv_1_fu_212->ap_done(grp_conv_1_fu_212_ap_done);
    grp_conv_1_fu_212->ap_idle(grp_conv_1_fu_212_ap_idle);
    grp_conv_1_fu_212->ap_ready(grp_conv_1_fu_212_ap_ready);
    grp_conv_1_fu_212->m_axi_in_r_AWVALID(grp_conv_1_fu_212_m_axi_in_r_AWVALID);
    grp_conv_1_fu_212->m_axi_in_r_AWREADY(ap_var_for_const6);
    grp_conv_1_fu_212->m_axi_in_r_AWADDR(grp_conv_1_fu_212_m_axi_in_r_AWADDR);
    grp_conv_1_fu_212->m_axi_in_r_AWID(grp_conv_1_fu_212_m_axi_in_r_AWID);
    grp_conv_1_fu_212->m_axi_in_r_AWLEN(grp_conv_1_fu_212_m_axi_in_r_AWLEN);
    grp_conv_1_fu_212->m_axi_in_r_AWSIZE(grp_conv_1_fu_212_m_axi_in_r_AWSIZE);
    grp_conv_1_fu_212->m_axi_in_r_AWBURST(grp_conv_1_fu_212_m_axi_in_r_AWBURST);
    grp_conv_1_fu_212->m_axi_in_r_AWLOCK(grp_conv_1_fu_212_m_axi_in_r_AWLOCK);
    grp_conv_1_fu_212->m_axi_in_r_AWCACHE(grp_conv_1_fu_212_m_axi_in_r_AWCACHE);
    grp_conv_1_fu_212->m_axi_in_r_AWPROT(grp_conv_1_fu_212_m_axi_in_r_AWPROT);
    grp_conv_1_fu_212->m_axi_in_r_AWQOS(grp_conv_1_fu_212_m_axi_in_r_AWQOS);
    grp_conv_1_fu_212->m_axi_in_r_AWREGION(grp_conv_1_fu_212_m_axi_in_r_AWREGION);
    grp_conv_1_fu_212->m_axi_in_r_AWUSER(grp_conv_1_fu_212_m_axi_in_r_AWUSER);
    grp_conv_1_fu_212->m_axi_in_r_WVALID(grp_conv_1_fu_212_m_axi_in_r_WVALID);
    grp_conv_1_fu_212->m_axi_in_r_WREADY(ap_var_for_const6);
    grp_conv_1_fu_212->m_axi_in_r_WDATA(grp_conv_1_fu_212_m_axi_in_r_WDATA);
    grp_conv_1_fu_212->m_axi_in_r_WSTRB(grp_conv_1_fu_212_m_axi_in_r_WSTRB);
    grp_conv_1_fu_212->m_axi_in_r_WLAST(grp_conv_1_fu_212_m_axi_in_r_WLAST);
    grp_conv_1_fu_212->m_axi_in_r_WID(grp_conv_1_fu_212_m_axi_in_r_WID);
    grp_conv_1_fu_212->m_axi_in_r_WUSER(grp_conv_1_fu_212_m_axi_in_r_WUSER);
    grp_conv_1_fu_212->m_axi_in_r_ARVALID(grp_conv_1_fu_212_m_axi_in_r_ARVALID);
    grp_conv_1_fu_212->m_axi_in_r_ARREADY(gmem_ARREADY);
    grp_conv_1_fu_212->m_axi_in_r_ARADDR(grp_conv_1_fu_212_m_axi_in_r_ARADDR);
    grp_conv_1_fu_212->m_axi_in_r_ARID(grp_conv_1_fu_212_m_axi_in_r_ARID);
    grp_conv_1_fu_212->m_axi_in_r_ARLEN(grp_conv_1_fu_212_m_axi_in_r_ARLEN);
    grp_conv_1_fu_212->m_axi_in_r_ARSIZE(grp_conv_1_fu_212_m_axi_in_r_ARSIZE);
    grp_conv_1_fu_212->m_axi_in_r_ARBURST(grp_conv_1_fu_212_m_axi_in_r_ARBURST);
    grp_conv_1_fu_212->m_axi_in_r_ARLOCK(grp_conv_1_fu_212_m_axi_in_r_ARLOCK);
    grp_conv_1_fu_212->m_axi_in_r_ARCACHE(grp_conv_1_fu_212_m_axi_in_r_ARCACHE);
    grp_conv_1_fu_212->m_axi_in_r_ARPROT(grp_conv_1_fu_212_m_axi_in_r_ARPROT);
    grp_conv_1_fu_212->m_axi_in_r_ARQOS(grp_conv_1_fu_212_m_axi_in_r_ARQOS);
    grp_conv_1_fu_212->m_axi_in_r_ARREGION(grp_conv_1_fu_212_m_axi_in_r_ARREGION);
    grp_conv_1_fu_212->m_axi_in_r_ARUSER(grp_conv_1_fu_212_m_axi_in_r_ARUSER);
    grp_conv_1_fu_212->m_axi_in_r_RVALID(gmem_RVALID);
    grp_conv_1_fu_212->m_axi_in_r_RREADY(grp_conv_1_fu_212_m_axi_in_r_RREADY);
    grp_conv_1_fu_212->m_axi_in_r_RDATA(gmem_RDATA);
    grp_conv_1_fu_212->m_axi_in_r_RLAST(gmem_RLAST);
    grp_conv_1_fu_212->m_axi_in_r_RID(gmem_RID);
    grp_conv_1_fu_212->m_axi_in_r_RUSER(gmem_RUSER);
    grp_conv_1_fu_212->m_axi_in_r_RRESP(gmem_RRESP);
    grp_conv_1_fu_212->m_axi_in_r_BVALID(ap_var_for_const6);
    grp_conv_1_fu_212->m_axi_in_r_BREADY(grp_conv_1_fu_212_m_axi_in_r_BREADY);
    grp_conv_1_fu_212->m_axi_in_r_BRESP(ap_var_for_const4);
    grp_conv_1_fu_212->m_axi_in_r_BID(ap_var_for_const1);
    grp_conv_1_fu_212->m_axi_in_r_BUSER(ap_var_for_const1);
    grp_conv_1_fu_212->in_offset(in1_reg_354);
    grp_conv_1_fu_212->output_r_address0(grp_conv_1_fu_212_output_r_address0);
    grp_conv_1_fu_212->output_r_ce0(grp_conv_1_fu_212_output_r_ce0);
    grp_conv_1_fu_212->output_r_we0(grp_conv_1_fu_212_output_r_we0);
    grp_conv_1_fu_212->output_r_d0(grp_conv_1_fu_212_output_r_d0);
    grp_conv_2_fu_225 = new conv_2("grp_conv_2_fu_225");
    grp_conv_2_fu_225->ap_clk(ap_clk);
    grp_conv_2_fu_225->ap_rst(ap_rst_n_inv);
    grp_conv_2_fu_225->ap_start(grp_conv_2_fu_225_ap_start);
    grp_conv_2_fu_225->ap_done(grp_conv_2_fu_225_ap_done);
    grp_conv_2_fu_225->ap_idle(grp_conv_2_fu_225_ap_idle);
    grp_conv_2_fu_225->ap_ready(grp_conv_2_fu_225_ap_ready);
    grp_conv_2_fu_225->in_r_address0(grp_conv_2_fu_225_in_r_address0);
    grp_conv_2_fu_225->in_r_ce0(grp_conv_2_fu_225_in_r_ce0);
    grp_conv_2_fu_225->in_r_q0(p1_output_q0);
    grp_conv_2_fu_225->output_r_address0(grp_conv_2_fu_225_output_r_address0);
    grp_conv_2_fu_225->output_r_ce0(grp_conv_2_fu_225_output_r_ce0);
    grp_conv_2_fu_225->output_r_we0(grp_conv_2_fu_225_output_r_we0);
    grp_conv_2_fu_225->output_r_d0(grp_conv_2_fu_225_output_r_d0);
    grp_conv_3_fu_235 = new conv_3("grp_conv_3_fu_235");
    grp_conv_3_fu_235->ap_clk(ap_clk);
    grp_conv_3_fu_235->ap_rst(ap_rst_n_inv);
    grp_conv_3_fu_235->ap_start(grp_conv_3_fu_235_ap_start);
    grp_conv_3_fu_235->ap_done(grp_conv_3_fu_235_ap_done);
    grp_conv_3_fu_235->ap_idle(grp_conv_3_fu_235_ap_idle);
    grp_conv_3_fu_235->ap_ready(grp_conv_3_fu_235_ap_ready);
    grp_conv_3_fu_235->in_r_address0(grp_conv_3_fu_235_in_r_address0);
    grp_conv_3_fu_235->in_r_ce0(grp_conv_3_fu_235_in_r_ce0);
    grp_conv_3_fu_235->in_r_q0(p2_output_q0);
    grp_conv_3_fu_235->output_r_address0(grp_conv_3_fu_235_output_r_address0);
    grp_conv_3_fu_235->output_r_ce0(grp_conv_3_fu_235_output_r_ce0);
    grp_conv_3_fu_235->output_r_we0(grp_conv_3_fu_235_output_r_we0);
    grp_conv_3_fu_235->output_r_d0(grp_conv_3_fu_235_output_r_d0);
    grp_conv_4_fu_245 = new conv_4("grp_conv_4_fu_245");
    grp_conv_4_fu_245->ap_clk(ap_clk);
    grp_conv_4_fu_245->ap_rst(ap_rst_n_inv);
    grp_conv_4_fu_245->ap_start(grp_conv_4_fu_245_ap_start);
    grp_conv_4_fu_245->ap_done(grp_conv_4_fu_245_ap_done);
    grp_conv_4_fu_245->ap_idle(grp_conv_4_fu_245_ap_idle);
    grp_conv_4_fu_245->ap_ready(grp_conv_4_fu_245_ap_ready);
    grp_conv_4_fu_245->in_r_address0(grp_conv_4_fu_245_in_r_address0);
    grp_conv_4_fu_245->in_r_ce0(grp_conv_4_fu_245_in_r_ce0);
    grp_conv_4_fu_245->in_r_q0(c3_output_q0);
    grp_conv_4_fu_245->output_r_address0(grp_conv_4_fu_245_output_r_address0);
    grp_conv_4_fu_245->output_r_ce0(grp_conv_4_fu_245_output_r_ce0);
    grp_conv_4_fu_245->output_r_we0(grp_conv_4_fu_245_output_r_we0);
    grp_conv_4_fu_245->output_r_d0(grp_conv_4_fu_245_output_r_d0);
    grp_conv_5_fu_255 = new conv_5("grp_conv_5_fu_255");
    grp_conv_5_fu_255->ap_clk(ap_clk);
    grp_conv_5_fu_255->ap_rst(ap_rst_n_inv);
    grp_conv_5_fu_255->ap_start(grp_conv_5_fu_255_ap_start);
    grp_conv_5_fu_255->ap_done(grp_conv_5_fu_255_ap_done);
    grp_conv_5_fu_255->ap_idle(grp_conv_5_fu_255_ap_idle);
    grp_conv_5_fu_255->ap_ready(grp_conv_5_fu_255_ap_ready);
    grp_conv_5_fu_255->in_r_address0(grp_conv_5_fu_255_in_r_address0);
    grp_conv_5_fu_255->in_r_ce0(grp_conv_5_fu_255_in_r_ce0);
    grp_conv_5_fu_255->in_r_q0(c4_output_q0);
    grp_conv_5_fu_255->output_r_address0(grp_conv_5_fu_255_output_r_address0);
    grp_conv_5_fu_255->output_r_ce0(grp_conv_5_fu_255_output_r_ce0);
    grp_conv_5_fu_255->output_r_we0(grp_conv_5_fu_255_output_r_we0);
    grp_conv_5_fu_255->output_r_d0(grp_conv_5_fu_255_output_r_d0);
    grp_max_pool_2D_1_fu_265 = new max_pool_2D_1("grp_max_pool_2D_1_fu_265");
    grp_max_pool_2D_1_fu_265->ap_clk(ap_clk);
    grp_max_pool_2D_1_fu_265->ap_rst(ap_rst_n_inv);
    grp_max_pool_2D_1_fu_265->ap_start(grp_max_pool_2D_1_fu_265_ap_start);
    grp_max_pool_2D_1_fu_265->ap_done(grp_max_pool_2D_1_fu_265_ap_done);
    grp_max_pool_2D_1_fu_265->ap_idle(grp_max_pool_2D_1_fu_265_ap_idle);
    grp_max_pool_2D_1_fu_265->ap_ready(grp_max_pool_2D_1_fu_265_ap_ready);
    grp_max_pool_2D_1_fu_265->in_r_address0(grp_max_pool_2D_1_fu_265_in_r_address0);
    grp_max_pool_2D_1_fu_265->in_r_ce0(grp_max_pool_2D_1_fu_265_in_r_ce0);
    grp_max_pool_2D_1_fu_265->in_r_q0(c1_output_q0);
    grp_max_pool_2D_1_fu_265->in_r_address1(grp_max_pool_2D_1_fu_265_in_r_address1);
    grp_max_pool_2D_1_fu_265->in_r_ce1(grp_max_pool_2D_1_fu_265_in_r_ce1);
    grp_max_pool_2D_1_fu_265->in_r_q1(c1_output_q1);
    grp_max_pool_2D_1_fu_265->output_r_address0(grp_max_pool_2D_1_fu_265_output_r_address0);
    grp_max_pool_2D_1_fu_265->output_r_ce0(grp_max_pool_2D_1_fu_265_output_r_ce0);
    grp_max_pool_2D_1_fu_265->output_r_we0(grp_max_pool_2D_1_fu_265_output_r_we0);
    grp_max_pool_2D_1_fu_265->output_r_d0(grp_max_pool_2D_1_fu_265_output_r_d0);
    grp_max_pool_2D_fu_271 = new max_pool_2D("grp_max_pool_2D_fu_271");
    grp_max_pool_2D_fu_271->ap_clk(ap_clk);
    grp_max_pool_2D_fu_271->ap_rst(ap_rst_n_inv);
    grp_max_pool_2D_fu_271->ap_start(grp_max_pool_2D_fu_271_ap_start);
    grp_max_pool_2D_fu_271->ap_done(grp_max_pool_2D_fu_271_ap_done);
    grp_max_pool_2D_fu_271->ap_idle(grp_max_pool_2D_fu_271_ap_idle);
    grp_max_pool_2D_fu_271->ap_ready(grp_max_pool_2D_fu_271_ap_ready);
    grp_max_pool_2D_fu_271->in_r_address0(grp_max_pool_2D_fu_271_in_r_address0);
    grp_max_pool_2D_fu_271->in_r_ce0(grp_max_pool_2D_fu_271_in_r_ce0);
    grp_max_pool_2D_fu_271->in_r_q0(c2_output_q0);
    grp_max_pool_2D_fu_271->in_r_address1(grp_max_pool_2D_fu_271_in_r_address1);
    grp_max_pool_2D_fu_271->in_r_ce1(grp_max_pool_2D_fu_271_in_r_ce1);
    grp_max_pool_2D_fu_271->in_r_q1(c2_output_q1);
    grp_max_pool_2D_fu_271->output_r_address0(grp_max_pool_2D_fu_271_output_r_address0);
    grp_max_pool_2D_fu_271->output_r_ce0(grp_max_pool_2D_fu_271_output_r_ce0);
    grp_max_pool_2D_fu_271->output_r_we0(grp_max_pool_2D_fu_271_output_r_we0);
    grp_max_pool_2D_fu_271->output_r_d0(grp_max_pool_2D_fu_271_output_r_d0);
    top_net_fcmp_32nsdEe_U41 = new top_net_fcmp_32nsdEe<1,1,32,32,1>("top_net_fcmp_32nsdEe_U41");
    top_net_fcmp_32nsdEe_U41->din0(c5_output_q0);
    top_net_fcmp_32nsdEe_U41->din1(max_value1_i_reg_191);
    top_net_fcmp_32nsdEe_U41->opcode(ap_var_for_const8);
    top_net_fcmp_32nsdEe_U41->dout(tmp_i_5_fu_277_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state17_io);
    sensitive << ( exitcond_i_fu_317_p2 );
    sensitive << ( ap_sig_ioackin_gmem_AWREADY );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( gmem_BVALID );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( gmem_BVALID );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sig_ioackin_gmem_AWREADY);
    sensitive << ( gmem_AWREADY );
    sensitive << ( ap_reg_ioackin_gmem_AWREADY );

    SC_METHOD(thread_ap_sig_ioackin_gmem_WREADY);
    sensitive << ( gmem_WREADY );
    sensitive << ( ap_reg_ioackin_gmem_WREADY );

    SC_METHOD(thread_c1_output_address0);
    sensitive << ( grp_conv_1_fu_212_output_r_address0 );
    sensitive << ( grp_max_pool_2D_1_fu_265_in_r_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_c1_output_ce0);
    sensitive << ( grp_conv_1_fu_212_output_r_ce0 );
    sensitive << ( grp_max_pool_2D_1_fu_265_in_r_ce0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_c1_output_ce1);
    sensitive << ( grp_max_pool_2D_1_fu_265_in_r_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_c1_output_we0);
    sensitive << ( grp_conv_1_fu_212_output_r_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_c2_output_address0);
    sensitive << ( grp_conv_2_fu_225_output_r_address0 );
    sensitive << ( grp_max_pool_2D_fu_271_in_r_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_c2_output_ce0);
    sensitive << ( grp_conv_2_fu_225_output_r_ce0 );
    sensitive << ( grp_max_pool_2D_fu_271_in_r_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_c2_output_ce1);
    sensitive << ( grp_max_pool_2D_fu_271_in_r_ce1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_c2_output_we0);
    sensitive << ( grp_conv_2_fu_225_output_r_we0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_c3_output_address0);
    sensitive << ( grp_conv_3_fu_235_output_r_address0 );
    sensitive << ( grp_conv_4_fu_245_in_r_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_c3_output_ce0);
    sensitive << ( grp_conv_3_fu_235_output_r_ce0 );
    sensitive << ( grp_conv_4_fu_245_in_r_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_c3_output_we0);
    sensitive << ( grp_conv_3_fu_235_output_r_we0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_c4_output_address0);
    sensitive << ( grp_conv_4_fu_245_output_r_address0 );
    sensitive << ( grp_conv_5_fu_255_in_r_address0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_c4_output_ce0);
    sensitive << ( grp_conv_4_fu_245_output_r_ce0 );
    sensitive << ( grp_conv_5_fu_255_in_r_ce0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_c4_output_we0);
    sensitive << ( grp_conv_4_fu_245_output_r_we0 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_c5_output_address0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( grp_conv_5_fu_255_output_r_address0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_i_fu_323_p1 );

    SC_METHOD(thread_c5_output_ce0);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_block_state17_io );
    sensitive << ( grp_conv_5_fu_255_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_c5_output_we0);
    sensitive << ( grp_conv_5_fu_255_output_r_we0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_exitcond_i_fu_317_p2);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_block_state17_io );
    sensitive << ( max_index_reg_201 );

    SC_METHOD(thread_gmem_ARVALID);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_conv_1_fu_212_m_axi_in_r_ARVALID );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_gmem_AWVALID);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( exitcond_i_fu_317_p2 );
    sensitive << ( ap_reg_ioackin_gmem_AWREADY );

    SC_METHOD(thread_gmem_BREADY);
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( gmem_BVALID );

    SC_METHOD(thread_gmem_RREADY);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_conv_1_fu_212_m_axi_in_r_RREADY );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_gmem_WVALID);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_reg_ioackin_gmem_WREADY );

    SC_METHOD(thread_gmem_blk_n_AW);
    sensitive << ( m_axi_gmem_AWREADY );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( exitcond_i_fu_317_p2 );

    SC_METHOD(thread_gmem_blk_n_B);
    sensitive << ( m_axi_gmem_BVALID );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_gmem_blk_n_W);
    sensitive << ( m_axi_gmem_WREADY );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_conv_1_fu_212_ap_start);
    sensitive << ( grp_conv_1_fu_212_ap_start_reg );

    SC_METHOD(thread_grp_conv_2_fu_225_ap_start);
    sensitive << ( grp_conv_2_fu_225_ap_start_reg );

    SC_METHOD(thread_grp_conv_3_fu_235_ap_start);
    sensitive << ( grp_conv_3_fu_235_ap_start_reg );

    SC_METHOD(thread_grp_conv_4_fu_245_ap_start);
    sensitive << ( grp_conv_4_fu_245_ap_start_reg );

    SC_METHOD(thread_grp_conv_5_fu_255_ap_start);
    sensitive << ( grp_conv_5_fu_255_ap_start_reg );

    SC_METHOD(thread_grp_max_pool_2D_1_fu_265_ap_start);
    sensitive << ( grp_max_pool_2D_1_fu_265_ap_start_reg );

    SC_METHOD(thread_grp_max_pool_2D_fu_271_ap_start);
    sensitive << ( grp_max_pool_2D_fu_271_ap_start_reg );

    SC_METHOD(thread_i_fu_328_p2);
    sensitive << ( max_index_reg_201 );

    SC_METHOD(thread_max_index_1_fu_334_p3);
    sensitive << ( max_index_cast1_reg_375 );
    sensitive << ( max_index_i_reg_178 );
    sensitive << ( tmp_i_5_fu_277_p2 );

    SC_METHOD(thread_max_index_cast1_fu_313_p1);
    sensitive << ( max_index_reg_201 );

    SC_METHOD(thread_max_value_2_fu_341_p3);
    sensitive << ( c5_output_q0 );
    sensitive << ( max_value1_i_reg_191 );
    sensitive << ( tmp_i_5_fu_277_p2 );

    SC_METHOD(thread_p1_output_address0);
    sensitive << ( grp_conv_2_fu_225_in_r_address0 );
    sensitive << ( grp_max_pool_2D_1_fu_265_output_r_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_p1_output_ce0);
    sensitive << ( grp_conv_2_fu_225_in_r_ce0 );
    sensitive << ( grp_max_pool_2D_1_fu_265_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_p1_output_we0);
    sensitive << ( grp_max_pool_2D_1_fu_265_output_r_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_p2_output_address0);
    sensitive << ( grp_conv_3_fu_235_in_r_address0 );
    sensitive << ( grp_max_pool_2D_fu_271_output_r_address0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_p2_output_ce0);
    sensitive << ( grp_conv_3_fu_235_in_r_ce0 );
    sensitive << ( grp_max_pool_2D_fu_271_output_r_ce0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_p2_output_we0);
    sensitive << ( grp_max_pool_2D_fu_271_output_r_we0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_tmp_fu_304_p1);
    sensitive << ( result3_reg_349 );

    SC_METHOD(thread_tmp_i_fu_323_p1);
    sensitive << ( max_index_reg_201 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( exitcond_i_fu_317_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( gmem_BVALID );
    sensitive << ( ap_block_state17_io );
    sensitive << ( grp_conv_1_fu_212_ap_done );
    sensitive << ( grp_conv_2_fu_225_ap_done );
    sensitive << ( grp_conv_3_fu_235_ap_done );
    sensitive << ( grp_conv_4_fu_245_ap_done );
    sensitive << ( grp_conv_5_fu_255_ap_done );
    sensitive << ( grp_max_pool_2D_1_fu_265_ap_done );
    sensitive << ( grp_max_pool_2D_fu_271_ap_done );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_sig_ioackin_gmem_WREADY );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const6);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const4);

    SC_THREAD(thread_ap_var_for_const5);

    SC_THREAD(thread_ap_var_for_const7);

    SC_THREAD(thread_ap_var_for_const8);

    ap_CS_fsm = "000000000000000000000001";
    grp_conv_1_fu_212_ap_start_reg = SC_LOGIC_0;
    grp_conv_2_fu_225_ap_start_reg = SC_LOGIC_0;
    grp_conv_3_fu_235_ap_start_reg = SC_LOGIC_0;
    grp_conv_4_fu_245_ap_start_reg = SC_LOGIC_0;
    grp_conv_5_fu_255_ap_start_reg = SC_LOGIC_0;
    grp_max_pool_2D_1_fu_265_ap_start_reg = SC_LOGIC_0;
    grp_max_pool_2D_fu_271_ap_start_reg = SC_LOGIC_0;
    ap_reg_ioackin_gmem_AWREADY = SC_LOGIC_0;
    ap_reg_ioackin_gmem_WREADY = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_net_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, m_axi_gmem_AWVALID, "(port)m_axi_gmem_AWVALID");
    sc_trace(mVcdFile, m_axi_gmem_AWREADY, "(port)m_axi_gmem_AWREADY");
    sc_trace(mVcdFile, m_axi_gmem_AWADDR, "(port)m_axi_gmem_AWADDR");
    sc_trace(mVcdFile, m_axi_gmem_AWID, "(port)m_axi_gmem_AWID");
    sc_trace(mVcdFile, m_axi_gmem_AWLEN, "(port)m_axi_gmem_AWLEN");
    sc_trace(mVcdFile, m_axi_gmem_AWSIZE, "(port)m_axi_gmem_AWSIZE");
    sc_trace(mVcdFile, m_axi_gmem_AWBURST, "(port)m_axi_gmem_AWBURST");
    sc_trace(mVcdFile, m_axi_gmem_AWLOCK, "(port)m_axi_gmem_AWLOCK");
    sc_trace(mVcdFile, m_axi_gmem_AWCACHE, "(port)m_axi_gmem_AWCACHE");
    sc_trace(mVcdFile, m_axi_gmem_AWPROT, "(port)m_axi_gmem_AWPROT");
    sc_trace(mVcdFile, m_axi_gmem_AWQOS, "(port)m_axi_gmem_AWQOS");
    sc_trace(mVcdFile, m_axi_gmem_AWREGION, "(port)m_axi_gmem_AWREGION");
    sc_trace(mVcdFile, m_axi_gmem_AWUSER, "(port)m_axi_gmem_AWUSER");
    sc_trace(mVcdFile, m_axi_gmem_WVALID, "(port)m_axi_gmem_WVALID");
    sc_trace(mVcdFile, m_axi_gmem_WREADY, "(port)m_axi_gmem_WREADY");
    sc_trace(mVcdFile, m_axi_gmem_WDATA, "(port)m_axi_gmem_WDATA");
    sc_trace(mVcdFile, m_axi_gmem_WSTRB, "(port)m_axi_gmem_WSTRB");
    sc_trace(mVcdFile, m_axi_gmem_WLAST, "(port)m_axi_gmem_WLAST");
    sc_trace(mVcdFile, m_axi_gmem_WID, "(port)m_axi_gmem_WID");
    sc_trace(mVcdFile, m_axi_gmem_WUSER, "(port)m_axi_gmem_WUSER");
    sc_trace(mVcdFile, m_axi_gmem_ARVALID, "(port)m_axi_gmem_ARVALID");
    sc_trace(mVcdFile, m_axi_gmem_ARREADY, "(port)m_axi_gmem_ARREADY");
    sc_trace(mVcdFile, m_axi_gmem_ARADDR, "(port)m_axi_gmem_ARADDR");
    sc_trace(mVcdFile, m_axi_gmem_ARID, "(port)m_axi_gmem_ARID");
    sc_trace(mVcdFile, m_axi_gmem_ARLEN, "(port)m_axi_gmem_ARLEN");
    sc_trace(mVcdFile, m_axi_gmem_ARSIZE, "(port)m_axi_gmem_ARSIZE");
    sc_trace(mVcdFile, m_axi_gmem_ARBURST, "(port)m_axi_gmem_ARBURST");
    sc_trace(mVcdFile, m_axi_gmem_ARLOCK, "(port)m_axi_gmem_ARLOCK");
    sc_trace(mVcdFile, m_axi_gmem_ARCACHE, "(port)m_axi_gmem_ARCACHE");
    sc_trace(mVcdFile, m_axi_gmem_ARPROT, "(port)m_axi_gmem_ARPROT");
    sc_trace(mVcdFile, m_axi_gmem_ARQOS, "(port)m_axi_gmem_ARQOS");
    sc_trace(mVcdFile, m_axi_gmem_ARREGION, "(port)m_axi_gmem_ARREGION");
    sc_trace(mVcdFile, m_axi_gmem_ARUSER, "(port)m_axi_gmem_ARUSER");
    sc_trace(mVcdFile, m_axi_gmem_RVALID, "(port)m_axi_gmem_RVALID");
    sc_trace(mVcdFile, m_axi_gmem_RREADY, "(port)m_axi_gmem_RREADY");
    sc_trace(mVcdFile, m_axi_gmem_RDATA, "(port)m_axi_gmem_RDATA");
    sc_trace(mVcdFile, m_axi_gmem_RLAST, "(port)m_axi_gmem_RLAST");
    sc_trace(mVcdFile, m_axi_gmem_RID, "(port)m_axi_gmem_RID");
    sc_trace(mVcdFile, m_axi_gmem_RUSER, "(port)m_axi_gmem_RUSER");
    sc_trace(mVcdFile, m_axi_gmem_RRESP, "(port)m_axi_gmem_RRESP");
    sc_trace(mVcdFile, m_axi_gmem_BVALID, "(port)m_axi_gmem_BVALID");
    sc_trace(mVcdFile, m_axi_gmem_BREADY, "(port)m_axi_gmem_BREADY");
    sc_trace(mVcdFile, m_axi_gmem_BRESP, "(port)m_axi_gmem_BRESP");
    sc_trace(mVcdFile, m_axi_gmem_BID, "(port)m_axi_gmem_BID");
    sc_trace(mVcdFile, m_axi_gmem_BUSER, "(port)m_axi_gmem_BUSER");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, in_r, "in_r");
    sc_trace(mVcdFile, result, "result");
    sc_trace(mVcdFile, gmem_blk_n_AW, "gmem_blk_n_AW");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, exitcond_i_fu_317_p2, "exitcond_i_fu_317_p2");
    sc_trace(mVcdFile, gmem_blk_n_W, "gmem_blk_n_W");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, gmem_blk_n_B, "gmem_blk_n_B");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, gmem_AWVALID, "gmem_AWVALID");
    sc_trace(mVcdFile, gmem_AWREADY, "gmem_AWREADY");
    sc_trace(mVcdFile, gmem_WVALID, "gmem_WVALID");
    sc_trace(mVcdFile, gmem_WREADY, "gmem_WREADY");
    sc_trace(mVcdFile, gmem_ARVALID, "gmem_ARVALID");
    sc_trace(mVcdFile, gmem_ARREADY, "gmem_ARREADY");
    sc_trace(mVcdFile, gmem_RVALID, "gmem_RVALID");
    sc_trace(mVcdFile, gmem_RREADY, "gmem_RREADY");
    sc_trace(mVcdFile, gmem_RDATA, "gmem_RDATA");
    sc_trace(mVcdFile, gmem_RLAST, "gmem_RLAST");
    sc_trace(mVcdFile, gmem_RID, "gmem_RID");
    sc_trace(mVcdFile, gmem_RUSER, "gmem_RUSER");
    sc_trace(mVcdFile, gmem_RRESP, "gmem_RRESP");
    sc_trace(mVcdFile, gmem_BVALID, "gmem_BVALID");
    sc_trace(mVcdFile, gmem_BREADY, "gmem_BREADY");
    sc_trace(mVcdFile, gmem_BRESP, "gmem_BRESP");
    sc_trace(mVcdFile, gmem_BID, "gmem_BID");
    sc_trace(mVcdFile, gmem_BUSER, "gmem_BUSER");
    sc_trace(mVcdFile, result3_reg_349, "result3_reg_349");
    sc_trace(mVcdFile, in1_reg_354, "in1_reg_354");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, gmem_addr_reg_364, "gmem_addr_reg_364");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, c5_output_q0, "c5_output_q0");
    sc_trace(mVcdFile, max_index_cast1_fu_313_p1, "max_index_cast1_fu_313_p1");
    sc_trace(mVcdFile, max_index_cast1_reg_375, "max_index_cast1_reg_375");
    sc_trace(mVcdFile, ap_sig_ioackin_gmem_AWREADY, "ap_sig_ioackin_gmem_AWREADY");
    sc_trace(mVcdFile, ap_block_state17_io, "ap_block_state17_io");
    sc_trace(mVcdFile, i_fu_328_p2, "i_fu_328_p2");
    sc_trace(mVcdFile, i_reg_388, "i_reg_388");
    sc_trace(mVcdFile, max_index_1_fu_334_p3, "max_index_1_fu_334_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, max_value_2_fu_341_p3, "max_value_2_fu_341_p3");
    sc_trace(mVcdFile, c1_output_address0, "c1_output_address0");
    sc_trace(mVcdFile, c1_output_ce0, "c1_output_ce0");
    sc_trace(mVcdFile, c1_output_we0, "c1_output_we0");
    sc_trace(mVcdFile, c1_output_q0, "c1_output_q0");
    sc_trace(mVcdFile, c1_output_ce1, "c1_output_ce1");
    sc_trace(mVcdFile, c1_output_q1, "c1_output_q1");
    sc_trace(mVcdFile, p1_output_address0, "p1_output_address0");
    sc_trace(mVcdFile, p1_output_ce0, "p1_output_ce0");
    sc_trace(mVcdFile, p1_output_we0, "p1_output_we0");
    sc_trace(mVcdFile, p1_output_q0, "p1_output_q0");
    sc_trace(mVcdFile, c2_output_address0, "c2_output_address0");
    sc_trace(mVcdFile, c2_output_ce0, "c2_output_ce0");
    sc_trace(mVcdFile, c2_output_we0, "c2_output_we0");
    sc_trace(mVcdFile, c2_output_q0, "c2_output_q0");
    sc_trace(mVcdFile, c2_output_ce1, "c2_output_ce1");
    sc_trace(mVcdFile, c2_output_q1, "c2_output_q1");
    sc_trace(mVcdFile, p2_output_address0, "p2_output_address0");
    sc_trace(mVcdFile, p2_output_ce0, "p2_output_ce0");
    sc_trace(mVcdFile, p2_output_we0, "p2_output_we0");
    sc_trace(mVcdFile, p2_output_q0, "p2_output_q0");
    sc_trace(mVcdFile, c3_output_address0, "c3_output_address0");
    sc_trace(mVcdFile, c3_output_ce0, "c3_output_ce0");
    sc_trace(mVcdFile, c3_output_we0, "c3_output_we0");
    sc_trace(mVcdFile, c3_output_q0, "c3_output_q0");
    sc_trace(mVcdFile, c4_output_address0, "c4_output_address0");
    sc_trace(mVcdFile, c4_output_ce0, "c4_output_ce0");
    sc_trace(mVcdFile, c4_output_we0, "c4_output_we0");
    sc_trace(mVcdFile, c4_output_q0, "c4_output_q0");
    sc_trace(mVcdFile, c5_output_address0, "c5_output_address0");
    sc_trace(mVcdFile, c5_output_ce0, "c5_output_ce0");
    sc_trace(mVcdFile, c5_output_we0, "c5_output_we0");
    sc_trace(mVcdFile, grp_conv_1_fu_212_ap_start, "grp_conv_1_fu_212_ap_start");
    sc_trace(mVcdFile, grp_conv_1_fu_212_ap_done, "grp_conv_1_fu_212_ap_done");
    sc_trace(mVcdFile, grp_conv_1_fu_212_ap_idle, "grp_conv_1_fu_212_ap_idle");
    sc_trace(mVcdFile, grp_conv_1_fu_212_ap_ready, "grp_conv_1_fu_212_ap_ready");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWVALID, "grp_conv_1_fu_212_m_axi_in_r_AWVALID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWADDR, "grp_conv_1_fu_212_m_axi_in_r_AWADDR");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWID, "grp_conv_1_fu_212_m_axi_in_r_AWID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWLEN, "grp_conv_1_fu_212_m_axi_in_r_AWLEN");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWSIZE, "grp_conv_1_fu_212_m_axi_in_r_AWSIZE");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWBURST, "grp_conv_1_fu_212_m_axi_in_r_AWBURST");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWLOCK, "grp_conv_1_fu_212_m_axi_in_r_AWLOCK");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWCACHE, "grp_conv_1_fu_212_m_axi_in_r_AWCACHE");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWPROT, "grp_conv_1_fu_212_m_axi_in_r_AWPROT");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWQOS, "grp_conv_1_fu_212_m_axi_in_r_AWQOS");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWREGION, "grp_conv_1_fu_212_m_axi_in_r_AWREGION");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_AWUSER, "grp_conv_1_fu_212_m_axi_in_r_AWUSER");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WVALID, "grp_conv_1_fu_212_m_axi_in_r_WVALID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WDATA, "grp_conv_1_fu_212_m_axi_in_r_WDATA");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WSTRB, "grp_conv_1_fu_212_m_axi_in_r_WSTRB");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WLAST, "grp_conv_1_fu_212_m_axi_in_r_WLAST");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WID, "grp_conv_1_fu_212_m_axi_in_r_WID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_WUSER, "grp_conv_1_fu_212_m_axi_in_r_WUSER");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARVALID, "grp_conv_1_fu_212_m_axi_in_r_ARVALID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARADDR, "grp_conv_1_fu_212_m_axi_in_r_ARADDR");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARID, "grp_conv_1_fu_212_m_axi_in_r_ARID");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARLEN, "grp_conv_1_fu_212_m_axi_in_r_ARLEN");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARSIZE, "grp_conv_1_fu_212_m_axi_in_r_ARSIZE");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARBURST, "grp_conv_1_fu_212_m_axi_in_r_ARBURST");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARLOCK, "grp_conv_1_fu_212_m_axi_in_r_ARLOCK");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARCACHE, "grp_conv_1_fu_212_m_axi_in_r_ARCACHE");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARPROT, "grp_conv_1_fu_212_m_axi_in_r_ARPROT");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARQOS, "grp_conv_1_fu_212_m_axi_in_r_ARQOS");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARREGION, "grp_conv_1_fu_212_m_axi_in_r_ARREGION");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_ARUSER, "grp_conv_1_fu_212_m_axi_in_r_ARUSER");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_RREADY, "grp_conv_1_fu_212_m_axi_in_r_RREADY");
    sc_trace(mVcdFile, grp_conv_1_fu_212_m_axi_in_r_BREADY, "grp_conv_1_fu_212_m_axi_in_r_BREADY");
    sc_trace(mVcdFile, grp_conv_1_fu_212_output_r_address0, "grp_conv_1_fu_212_output_r_address0");
    sc_trace(mVcdFile, grp_conv_1_fu_212_output_r_ce0, "grp_conv_1_fu_212_output_r_ce0");
    sc_trace(mVcdFile, grp_conv_1_fu_212_output_r_we0, "grp_conv_1_fu_212_output_r_we0");
    sc_trace(mVcdFile, grp_conv_1_fu_212_output_r_d0, "grp_conv_1_fu_212_output_r_d0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_ap_start, "grp_conv_2_fu_225_ap_start");
    sc_trace(mVcdFile, grp_conv_2_fu_225_ap_done, "grp_conv_2_fu_225_ap_done");
    sc_trace(mVcdFile, grp_conv_2_fu_225_ap_idle, "grp_conv_2_fu_225_ap_idle");
    sc_trace(mVcdFile, grp_conv_2_fu_225_ap_ready, "grp_conv_2_fu_225_ap_ready");
    sc_trace(mVcdFile, grp_conv_2_fu_225_in_r_address0, "grp_conv_2_fu_225_in_r_address0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_in_r_ce0, "grp_conv_2_fu_225_in_r_ce0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_output_r_address0, "grp_conv_2_fu_225_output_r_address0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_output_r_ce0, "grp_conv_2_fu_225_output_r_ce0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_output_r_we0, "grp_conv_2_fu_225_output_r_we0");
    sc_trace(mVcdFile, grp_conv_2_fu_225_output_r_d0, "grp_conv_2_fu_225_output_r_d0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_ap_start, "grp_conv_3_fu_235_ap_start");
    sc_trace(mVcdFile, grp_conv_3_fu_235_ap_done, "grp_conv_3_fu_235_ap_done");
    sc_trace(mVcdFile, grp_conv_3_fu_235_ap_idle, "grp_conv_3_fu_235_ap_idle");
    sc_trace(mVcdFile, grp_conv_3_fu_235_ap_ready, "grp_conv_3_fu_235_ap_ready");
    sc_trace(mVcdFile, grp_conv_3_fu_235_in_r_address0, "grp_conv_3_fu_235_in_r_address0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_in_r_ce0, "grp_conv_3_fu_235_in_r_ce0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_output_r_address0, "grp_conv_3_fu_235_output_r_address0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_output_r_ce0, "grp_conv_3_fu_235_output_r_ce0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_output_r_we0, "grp_conv_3_fu_235_output_r_we0");
    sc_trace(mVcdFile, grp_conv_3_fu_235_output_r_d0, "grp_conv_3_fu_235_output_r_d0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_ap_start, "grp_conv_4_fu_245_ap_start");
    sc_trace(mVcdFile, grp_conv_4_fu_245_ap_done, "grp_conv_4_fu_245_ap_done");
    sc_trace(mVcdFile, grp_conv_4_fu_245_ap_idle, "grp_conv_4_fu_245_ap_idle");
    sc_trace(mVcdFile, grp_conv_4_fu_245_ap_ready, "grp_conv_4_fu_245_ap_ready");
    sc_trace(mVcdFile, grp_conv_4_fu_245_in_r_address0, "grp_conv_4_fu_245_in_r_address0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_in_r_ce0, "grp_conv_4_fu_245_in_r_ce0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_output_r_address0, "grp_conv_4_fu_245_output_r_address0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_output_r_ce0, "grp_conv_4_fu_245_output_r_ce0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_output_r_we0, "grp_conv_4_fu_245_output_r_we0");
    sc_trace(mVcdFile, grp_conv_4_fu_245_output_r_d0, "grp_conv_4_fu_245_output_r_d0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_ap_start, "grp_conv_5_fu_255_ap_start");
    sc_trace(mVcdFile, grp_conv_5_fu_255_ap_done, "grp_conv_5_fu_255_ap_done");
    sc_trace(mVcdFile, grp_conv_5_fu_255_ap_idle, "grp_conv_5_fu_255_ap_idle");
    sc_trace(mVcdFile, grp_conv_5_fu_255_ap_ready, "grp_conv_5_fu_255_ap_ready");
    sc_trace(mVcdFile, grp_conv_5_fu_255_in_r_address0, "grp_conv_5_fu_255_in_r_address0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_in_r_ce0, "grp_conv_5_fu_255_in_r_ce0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_output_r_address0, "grp_conv_5_fu_255_output_r_address0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_output_r_ce0, "grp_conv_5_fu_255_output_r_ce0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_output_r_we0, "grp_conv_5_fu_255_output_r_we0");
    sc_trace(mVcdFile, grp_conv_5_fu_255_output_r_d0, "grp_conv_5_fu_255_output_r_d0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_ap_start, "grp_max_pool_2D_1_fu_265_ap_start");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_ap_done, "grp_max_pool_2D_1_fu_265_ap_done");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_ap_idle, "grp_max_pool_2D_1_fu_265_ap_idle");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_ap_ready, "grp_max_pool_2D_1_fu_265_ap_ready");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_in_r_address0, "grp_max_pool_2D_1_fu_265_in_r_address0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_in_r_ce0, "grp_max_pool_2D_1_fu_265_in_r_ce0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_in_r_address1, "grp_max_pool_2D_1_fu_265_in_r_address1");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_in_r_ce1, "grp_max_pool_2D_1_fu_265_in_r_ce1");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_output_r_address0, "grp_max_pool_2D_1_fu_265_output_r_address0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_output_r_ce0, "grp_max_pool_2D_1_fu_265_output_r_ce0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_output_r_we0, "grp_max_pool_2D_1_fu_265_output_r_we0");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_output_r_d0, "grp_max_pool_2D_1_fu_265_output_r_d0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_ap_start, "grp_max_pool_2D_fu_271_ap_start");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_ap_done, "grp_max_pool_2D_fu_271_ap_done");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_ap_idle, "grp_max_pool_2D_fu_271_ap_idle");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_ap_ready, "grp_max_pool_2D_fu_271_ap_ready");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_in_r_address0, "grp_max_pool_2D_fu_271_in_r_address0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_in_r_ce0, "grp_max_pool_2D_fu_271_in_r_ce0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_in_r_address1, "grp_max_pool_2D_fu_271_in_r_address1");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_in_r_ce1, "grp_max_pool_2D_fu_271_in_r_ce1");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_output_r_address0, "grp_max_pool_2D_fu_271_output_r_address0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_output_r_ce0, "grp_max_pool_2D_fu_271_output_r_ce0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_output_r_we0, "grp_max_pool_2D_fu_271_output_r_we0");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_output_r_d0, "grp_max_pool_2D_fu_271_output_r_d0");
    sc_trace(mVcdFile, max_index_i_reg_178, "max_index_i_reg_178");
    sc_trace(mVcdFile, max_value1_i_reg_191, "max_value1_i_reg_191");
    sc_trace(mVcdFile, max_index_reg_201, "max_index_reg_201");
    sc_trace(mVcdFile, grp_conv_1_fu_212_ap_start_reg, "grp_conv_1_fu_212_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, grp_conv_2_fu_225_ap_start_reg, "grp_conv_2_fu_225_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_conv_3_fu_235_ap_start_reg, "grp_conv_3_fu_235_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_conv_4_fu_245_ap_start_reg, "grp_conv_4_fu_245_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_conv_5_fu_255_ap_start_reg, "grp_conv_5_fu_255_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_max_pool_2D_1_fu_265_ap_start_reg, "grp_max_pool_2D_1_fu_265_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, grp_max_pool_2D_fu_271_ap_start_reg, "grp_max_pool_2D_fu_271_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_i_fu_323_p1, "tmp_i_fu_323_p1");
    sc_trace(mVcdFile, tmp_fu_304_p1, "tmp_fu_304_p1");
    sc_trace(mVcdFile, ap_reg_ioackin_gmem_AWREADY, "ap_reg_ioackin_gmem_AWREADY");
    sc_trace(mVcdFile, ap_reg_ioackin_gmem_WREADY, "ap_reg_ioackin_gmem_WREADY");
    sc_trace(mVcdFile, ap_sig_ioackin_gmem_WREADY, "ap_sig_ioackin_gmem_WREADY");
    sc_trace(mVcdFile, tmp_i_5_fu_277_p2, "tmp_i_5_fu_277_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("top_net.hdltvin.dat");
    mHdltvoutHandle.open("top_net.hdltvout.dat");
}

top_net::~top_net() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete top_net_AXILiteS_s_axi_U;
    delete top_net_gmem_m_axi_U;
    delete c1_output_U;
    delete p1_output_U;
    delete c2_output_U;
    delete p2_output_U;
    delete c3_output_U;
    delete c4_output_U;
    delete c5_output_U;
    delete grp_conv_1_fu_212;
    delete grp_conv_2_fu_225;
    delete grp_conv_3_fu_235;
    delete grp_conv_4_fu_245;
    delete grp_conv_5_fu_255;
    delete grp_max_pool_2D_1_fu_265;
    delete grp_max_pool_2D_fu_271;
    delete top_net_fcmp_32nsdEe_U41;
}

void top_net::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void top_net::thread_ap_var_for_const6() {
    ap_var_for_const6 = ap_const_logic_0;
}

void top_net::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv1_0;
}

void top_net::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv32_1;
}

void top_net::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_lv3_0;
}

void top_net::thread_ap_var_for_const4() {
    ap_var_for_const4 = ap_const_lv2_0;
}

void top_net::thread_ap_var_for_const5() {
    ap_var_for_const5 = ap_const_lv4_0;
}

void top_net::thread_ap_var_for_const7() {
    ap_var_for_const7 = ap_const_lv4_F;
}

void top_net::thread_ap_var_for_const8() {
    ap_var_for_const8 = ap_const_lv5_2;
}

void top_net::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_gmem_AWREADY = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_1))) {
            if (esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0)) {
                ap_reg_ioackin_gmem_AWREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, gmem_AWREADY.read())) {
                ap_reg_ioackin_gmem_AWREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_reg_ioackin_gmem_WREADY = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
            if (esl_seteq<1,1,1>(ap_sig_ioackin_gmem_WREADY.read(), ap_const_logic_1)) {
                ap_reg_ioackin_gmem_WREADY = ap_const_logic_0;
            } else if (esl_seteq<1,1,1>(ap_const_logic_1, gmem_WREADY.read())) {
                ap_reg_ioackin_gmem_WREADY = ap_const_logic_1;
            }
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_conv_1_fu_212_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            grp_conv_1_fu_212_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_1_fu_212_ap_ready.read())) {
            grp_conv_1_fu_212_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_conv_2_fu_225_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            grp_conv_2_fu_225_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_2_fu_225_ap_ready.read())) {
            grp_conv_2_fu_225_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_conv_3_fu_235_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
            grp_conv_3_fu_235_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_3_fu_235_ap_ready.read())) {
            grp_conv_3_fu_235_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_conv_4_fu_245_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
            grp_conv_4_fu_245_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_4_fu_245_ap_ready.read())) {
            grp_conv_4_fu_245_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_conv_5_fu_255_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            grp_conv_5_fu_255_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_5_fu_255_ap_ready.read())) {
            grp_conv_5_fu_255_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_max_pool_2D_1_fu_265_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            grp_max_pool_2D_1_fu_265_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_max_pool_2D_1_fu_265_ap_ready.read())) {
            grp_max_pool_2D_1_fu_265_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_max_pool_2D_fu_271_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            grp_max_pool_2D_fu_271_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_max_pool_2D_fu_271_ap_ready.read())) {
            grp_max_pool_2D_fu_271_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        max_index_i_reg_178 = max_index_1_fu_334_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        max_index_i_reg_178 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        max_index_reg_201 = i_reg_388.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        max_index_reg_201 = ap_const_lv4_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        max_value1_i_reg_191 = max_value_2_fu_341_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        max_value1_i_reg_191 = c5_output_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        gmem_addr_reg_364 =  (sc_lv<32>) (tmp_fu_304_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_0))) {
        i_reg_388 = i_fu_328_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        in1_reg_354 = in_r.read().range(31, 2);
        result3_reg_349 = result.read().range(31, 2);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0))) {
        max_index_cast1_reg_375 = max_index_cast1_fu_313_p1.read();
    }
}

void top_net::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void top_net::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void top_net::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void top_net::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void top_net::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void top_net::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void top_net::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void top_net::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void top_net::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void top_net::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void top_net::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void top_net::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void top_net::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void top_net::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void top_net::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void top_net::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void top_net::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void top_net::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void top_net::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void top_net::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void top_net::thread_ap_block_state17_io() {
    ap_block_state17_io = (esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, ap_sig_ioackin_gmem_AWREADY.read()));
}

void top_net::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void top_net::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void top_net::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void top_net::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void top_net::thread_ap_sig_ioackin_gmem_AWREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_AWREADY.read())) {
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY.read();
    } else {
        ap_sig_ioackin_gmem_AWREADY = ap_const_logic_1;
    }
}

void top_net::thread_ap_sig_ioackin_gmem_WREADY() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_WREADY.read())) {
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY.read();
    } else {
        ap_sig_ioackin_gmem_WREADY = ap_const_logic_1;
    }
}

void top_net::thread_c1_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c1_output_address0 = grp_max_pool_2D_1_fu_265_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c1_output_address0 = grp_conv_1_fu_212_output_r_address0.read();
    } else {
        c1_output_address0 = "XXXXXXXXXXXXX";
    }
}

void top_net::thread_c1_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c1_output_ce0 = grp_max_pool_2D_1_fu_265_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c1_output_ce0 = grp_conv_1_fu_212_output_r_ce0.read();
    } else {
        c1_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_c1_output_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        c1_output_ce1 = grp_max_pool_2D_1_fu_265_in_r_ce1.read();
    } else {
        c1_output_ce1 = ap_const_logic_0;
    }
}

void top_net::thread_c1_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        c1_output_we0 = grp_conv_1_fu_212_output_r_we0.read();
    } else {
        c1_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_c2_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c2_output_address0 = grp_max_pool_2D_fu_271_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c2_output_address0 = grp_conv_2_fu_225_output_r_address0.read();
    } else {
        c2_output_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void top_net::thread_c2_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c2_output_ce0 = grp_max_pool_2D_fu_271_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c2_output_ce0 = grp_conv_2_fu_225_output_r_ce0.read();
    } else {
        c2_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_c2_output_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c2_output_ce1 = grp_max_pool_2D_fu_271_in_r_ce1.read();
    } else {
        c2_output_ce1 = ap_const_logic_0;
    }
}

void top_net::thread_c2_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c2_output_we0 = grp_conv_2_fu_225_output_r_we0.read();
    } else {
        c2_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_c3_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c3_output_address0 = grp_conv_4_fu_245_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        c3_output_address0 = grp_conv_3_fu_235_output_r_address0.read();
    } else {
        c3_output_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void top_net::thread_c3_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c3_output_ce0 = grp_conv_4_fu_245_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        c3_output_ce0 = grp_conv_3_fu_235_output_r_ce0.read();
    } else {
        c3_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_c3_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        c3_output_we0 = grp_conv_3_fu_235_output_r_we0.read();
    } else {
        c3_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_c4_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        c4_output_address0 = grp_conv_5_fu_255_in_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c4_output_address0 = grp_conv_4_fu_245_output_r_address0.read();
    } else {
        c4_output_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void top_net::thread_c4_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        c4_output_ce0 = grp_conv_5_fu_255_in_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c4_output_ce0 = grp_conv_4_fu_245_output_r_ce0.read();
    } else {
        c4_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_c4_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c4_output_we0 = grp_conv_4_fu_245_output_r_we0.read();
    } else {
        c4_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_c5_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        c5_output_address0 =  (sc_lv<4>) (tmp_i_fu_323_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        c5_output_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        c5_output_address0 = grp_conv_5_fu_255_output_r_address0.read();
    } else {
        c5_output_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void top_net::thread_c5_output_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
          esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0)))) {
        c5_output_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        c5_output_ce0 = grp_conv_5_fu_255_output_r_ce0.read();
    } else {
        c5_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_c5_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        c5_output_we0 = grp_conv_5_fu_255_output_r_we0.read();
    } else {
        c5_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_exitcond_i_fu_317_p2() {
    exitcond_i_fu_317_p2 = (!max_index_reg_201.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(max_index_reg_201.read() == ap_const_lv4_A);
}

void top_net::thread_gmem_ARVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        gmem_ARVALID = grp_conv_1_fu_212_m_axi_in_r_ARVALID.read();
    } else {
        gmem_ARVALID = ap_const_logic_0;
    }
}

void top_net::thread_gmem_AWVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_AWREADY.read()))) {
        gmem_AWVALID = ap_const_logic_1;
    } else {
        gmem_AWVALID = ap_const_logic_0;
    }
}

void top_net::thread_gmem_BREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && 
         esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
        gmem_BREADY = ap_const_logic_1;
    } else {
        gmem_BREADY = ap_const_logic_0;
    }
}

void top_net::thread_gmem_RREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        gmem_RREADY = grp_conv_1_fu_212_m_axi_in_r_RREADY.read();
    } else {
        gmem_RREADY = ap_const_logic_0;
    }
}

void top_net::thread_gmem_WVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_reg_ioackin_gmem_WREADY.read()))) {
        gmem_WVALID = ap_const_logic_1;
    } else {
        gmem_WVALID = ap_const_logic_0;
    }
}

void top_net::thread_gmem_blk_n_AW() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_1))) {
        gmem_blk_n_AW = m_axi_gmem_AWREADY.read();
    } else {
        gmem_blk_n_AW = ap_const_logic_1;
    }
}

void top_net::thread_gmem_blk_n_B() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        gmem_blk_n_B = m_axi_gmem_BVALID.read();
    } else {
        gmem_blk_n_B = ap_const_logic_1;
    }
}

void top_net::thread_gmem_blk_n_W() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        gmem_blk_n_W = m_axi_gmem_WREADY.read();
    } else {
        gmem_blk_n_W = ap_const_logic_1;
    }
}

void top_net::thread_grp_conv_1_fu_212_ap_start() {
    grp_conv_1_fu_212_ap_start = grp_conv_1_fu_212_ap_start_reg.read();
}

void top_net::thread_grp_conv_2_fu_225_ap_start() {
    grp_conv_2_fu_225_ap_start = grp_conv_2_fu_225_ap_start_reg.read();
}

void top_net::thread_grp_conv_3_fu_235_ap_start() {
    grp_conv_3_fu_235_ap_start = grp_conv_3_fu_235_ap_start_reg.read();
}

void top_net::thread_grp_conv_4_fu_245_ap_start() {
    grp_conv_4_fu_245_ap_start = grp_conv_4_fu_245_ap_start_reg.read();
}

void top_net::thread_grp_conv_5_fu_255_ap_start() {
    grp_conv_5_fu_255_ap_start = grp_conv_5_fu_255_ap_start_reg.read();
}

void top_net::thread_grp_max_pool_2D_1_fu_265_ap_start() {
    grp_max_pool_2D_1_fu_265_ap_start = grp_max_pool_2D_1_fu_265_ap_start_reg.read();
}

void top_net::thread_grp_max_pool_2D_fu_271_ap_start() {
    grp_max_pool_2D_fu_271_ap_start = grp_max_pool_2D_fu_271_ap_start_reg.read();
}

void top_net::thread_i_fu_328_p2() {
    i_fu_328_p2 = (!max_index_reg_201.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(max_index_reg_201.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void top_net::thread_max_index_1_fu_334_p3() {
    max_index_1_fu_334_p3 = (!tmp_i_5_fu_277_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i_5_fu_277_p2.read()[0].to_bool())? max_index_cast1_reg_375.read(): max_index_i_reg_178.read());
}

void top_net::thread_max_index_cast1_fu_313_p1() {
    max_index_cast1_fu_313_p1 = esl_zext<32,4>(max_index_reg_201.read());
}

void top_net::thread_max_value_2_fu_341_p3() {
    max_value_2_fu_341_p3 = (!tmp_i_5_fu_277_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_i_5_fu_277_p2.read()[0].to_bool())? c5_output_q0.read(): max_value1_i_reg_191.read());
}

void top_net::thread_p1_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p1_output_address0 = grp_max_pool_2D_1_fu_265_output_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p1_output_address0 = grp_conv_2_fu_225_in_r_address0.read();
    } else {
        p1_output_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void top_net::thread_p1_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p1_output_ce0 = grp_max_pool_2D_1_fu_265_output_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p1_output_ce0 = grp_conv_2_fu_225_in_r_ce0.read();
    } else {
        p1_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_p1_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p1_output_we0 = grp_max_pool_2D_1_fu_265_output_r_we0.read();
    } else {
        p1_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_p2_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p2_output_address0 = grp_max_pool_2D_fu_271_output_r_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p2_output_address0 = grp_conv_3_fu_235_in_r_address0.read();
    } else {
        p2_output_address0 =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void top_net::thread_p2_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p2_output_ce0 = grp_max_pool_2D_fu_271_output_r_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p2_output_ce0 = grp_conv_3_fu_235_in_r_ce0.read();
    } else {
        p2_output_ce0 = ap_const_logic_0;
    }
}

void top_net::thread_p2_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        p2_output_we0 = grp_max_pool_2D_fu_271_output_r_we0.read();
    } else {
        p2_output_we0 = ap_const_logic_0;
    }
}

void top_net::thread_tmp_fu_304_p1() {
    tmp_fu_304_p1 = esl_zext<64,30>(result3_reg_349.read());
}

void top_net::thread_tmp_i_fu_323_p1() {
    tmp_i_fu_323_p1 = esl_zext<64,4>(max_index_reg_201.read());
}

void top_net::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_conv_1_fu_212_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_max_pool_2D_1_fu_265_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_conv_2_fu_225_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_max_pool_2D_fu_271_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(grp_conv_3_fu_235_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(grp_conv_4_fu_245_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(grp_conv_5_fu_255_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state19;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(ap_block_state17_io.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_i_fu_317_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 262144 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && esl_seteq<1,1,1>(ap_sig_ioackin_gmem_WREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read()) && esl_seteq<1,1,1>(gmem_BVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state24;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void top_net::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"m_axi_gmem_AWVALID\" :  \"" << m_axi_gmem_AWVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_AWREADY\" :  \"" << m_axi_gmem_AWREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWADDR\" :  \"" << m_axi_gmem_AWADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWID\" :  \"" << m_axi_gmem_AWID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWLEN\" :  \"" << m_axi_gmem_AWLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWSIZE\" :  \"" << m_axi_gmem_AWSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWBURST\" :  \"" << m_axi_gmem_AWBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWLOCK\" :  \"" << m_axi_gmem_AWLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWCACHE\" :  \"" << m_axi_gmem_AWCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWPROT\" :  \"" << m_axi_gmem_AWPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWQOS\" :  \"" << m_axi_gmem_AWQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWREGION\" :  \"" << m_axi_gmem_AWREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_AWUSER\" :  \"" << m_axi_gmem_AWUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WVALID\" :  \"" << m_axi_gmem_WVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_WREADY\" :  \"" << m_axi_gmem_WREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WDATA\" :  \"" << m_axi_gmem_WDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WSTRB\" :  \"" << m_axi_gmem_WSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WLAST\" :  \"" << m_axi_gmem_WLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WID\" :  \"" << m_axi_gmem_WID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_WUSER\" :  \"" << m_axi_gmem_WUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARVALID\" :  \"" << m_axi_gmem_ARVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_ARREADY\" :  \"" << m_axi_gmem_ARREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARADDR\" :  \"" << m_axi_gmem_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARID\" :  \"" << m_axi_gmem_ARID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARLEN\" :  \"" << m_axi_gmem_ARLEN.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARSIZE\" :  \"" << m_axi_gmem_ARSIZE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARBURST\" :  \"" << m_axi_gmem_ARBURST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARLOCK\" :  \"" << m_axi_gmem_ARLOCK.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARCACHE\" :  \"" << m_axi_gmem_ARCACHE.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARPROT\" :  \"" << m_axi_gmem_ARPROT.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARQOS\" :  \"" << m_axi_gmem_ARQOS.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARREGION\" :  \"" << m_axi_gmem_ARREGION.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_ARUSER\" :  \"" << m_axi_gmem_ARUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RVALID\" :  \"" << m_axi_gmem_RVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_RREADY\" :  \"" << m_axi_gmem_RREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RDATA\" :  \"" << m_axi_gmem_RDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RLAST\" :  \"" << m_axi_gmem_RLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RID\" :  \"" << m_axi_gmem_RID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RUSER\" :  \"" << m_axi_gmem_RUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_RRESP\" :  \"" << m_axi_gmem_RRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BVALID\" :  \"" << m_axi_gmem_BVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"m_axi_gmem_BREADY\" :  \"" << m_axi_gmem_BREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BRESP\" :  \"" << m_axi_gmem_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BID\" :  \"" << m_axi_gmem_BID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"m_axi_gmem_BUSER\" :  \"" << m_axi_gmem_BUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

